import assert from 'node:assert/strict';
import fs from 'node:fs';

const booking = fs.readFileSync('online-booking/booking.js', 'utf8');
const accountShell = fs.readFileSync('online-booking/account-shell.js', 'utf8');
const personalData = fs.readFileSync('online-booking/personal-data.js', 'utf8');
const passwordSettings = fs.readFileSync('online-booking/password-settings.js', 'utf8');
const consentSettings = fs.readFileSync('online-booking/consent-settings.js', 'utf8');
const bookingSettingsUi = fs.readFileSync('settings/online-booking/online-booking.js', 'utf8');
const accountApi = fs.readFileSync('core/account/index.js', 'utf8');
const onlineBookingController = fs.readFileSync('server/src/online-booking/online-booking.controller.ts', 'utf8');
const accountSettingsController = fs.readFileSync('server/src/online-booking/account-settings.controller.ts', 'utf8');
const onlineBookingService = fs.readFileSync('server/src/online-booking/online-booking.service.ts', 'utf8');
const communicationService = fs.readFileSync('server/src/communication/communication.service.ts', 'utf8');
const communicationHistory = fs.readFileSync('server/src/communication/communication-history.service.ts', 'utf8');
const messageAttachmentMigration = fs.readFileSync('server/prisma/migrations/20260914010000_message_attachments/migration.sql', 'utf8');
const consentPolicy = fs.readFileSync('server/src/tenant-document-archive/consent-policy.service.ts', 'utf8');
const telegramBot = fs.readFileSync('server/src/communication/telegram-bot.service.ts', 'utf8');
const inputsUi = fs.readFileSync('ui/inputs/index.js', 'utf8');
const repeatedFields = fs.readFileSync('ui/repeated-fields/index.js', 'utf8');
const chatUi = fs.readFileSync('ui/chat/index.js', 'utf8');
const chatRuntime = fs.readFileSync('core/chat/runtime.js', 'utf8');
const chatCss = fs.readFileSync('ui/chat/chat.css', 'utf8');
const styleCss = fs.readFileSync('css/style.css', 'utf8');
const accountMobileCss = fs.readFileSync('ui/booking/account-mobile.css', 'utf8');
const accountThemeCss = fs.readFileSync('ui/booking/account-theme.css', 'utf8');
const indexHtml = fs.readFileSync('index.html', 'utf8');
const bookingUi = fs.readFileSync('ui/booking/index.js', 'utf8');
const v2Ui = fs.readFileSync('ui/v2/index.js', 'utf8');
const v2Css = fs.readFileSync('ui/v2/v2.css', 'utf8');
const coreJs = fs.readFileSync('core.js', 'utf8');
const buttonCss = fs.readFileSync('ui/buttons/buttons.css', 'utf8');
const segmentUi = fs.readFileSync('ui/selection/segment-control.js', 'utf8');
const segmentCss = fs.readFileSync('ui/selection/segment-control.css', 'utf8');
const entityCardCss = fs.readFileSync('ui/cards/entity-card.css', 'utf8');
const infoUi = fs.readFileSync('ui/info/index.js', 'utf8');
const infoCss = fs.readFileSync('ui/info/info.css', 'utf8');
const timeUi = fs.readFileSync('ui/time/index.js', 'utf8');
const headerUi = fs.readFileSync('ui/header/index.js', 'utf8');
const journalListUi = fs.readFileSync('journal/список.js', 'utf8');

// Public booking selection comes first. UI Reference V2 is the end-user target.
assert.match(booking, /renderAccount/);
assert.match(booking, /v2Header\(\{/);
assert.match(booking, /v2Shell\(\{/);
assert.match(booking, /v2Sticker\(\{/);
assert.match(booking, /v2LegalCards\(/);
assert.match(booking, /v2ServiceStickers\(/);
assert.match(booking, /initV2Swipe\(/);
assert.match(booking, /initV2StickerSwipe\(/);
assert.match(booking, /function renderLegalSticker/);
assert.match(booking, /function renderAccountEntry/);
assert.match(booking, /function renderAccountDetails/);
assert.match(booking, /function renderWorkplaces/);
assert.match(booking, /function renderProcedures/);
assert.match(booking, /function renderDates/);
assert.match(booking, /function renderTimes/);
assert.match(booking, /function renderConfirmation/);
assert.match(booking, /step: 'workplaces'/);
assert.match(booking, /step: 'procedures'/);
assert.match(booking, /step: 'dates'/);
assert.match(booking, /step: 'times'/);
assert.match(booking, /step: 'confirmation'/);
assert.doesNotMatch(booking, /data-booking-workplaces-next/);
assert.match(booking, /data-booking-procedures-next/);
assert.doesNotMatch(booking, /data-booking-dates-next/);
assert.doesNotMatch(booking, /data-booking-times-next/);
assert.match(booking, /state\.workplaceKey = node\.dataset\.bookingWorkplace \|\| '';[\s\S]*?renderProcedures\(root, state\);/);
assert.match(booking, /onDateSelect: \(date\) => \{[\s\S]*?state\.date = date;[\s\S]*?renderTimes\(root, state\);/);
assert.match(booking, /node\.addEventListener\('click', \(\) => \{[\s\S]*?state\.from = slot\.from;[\s\S]*?renderConfirmation\(root, state\);/);
assert.doesNotMatch(booking, /data-booking-workplaces-back/);
assert.doesNotMatch(booking, /data-booking-dates-back/);
assert.doesNotMatch(booking, /data-booking-times-back/);
assert.doesNotMatch(booking, /data-booking-confirm-back/);
assert.match(booking, /label: 'Телефон или email'/);
assert.match(booking, /label: 'Пароль'/);
assert.match(booking, /data-booking-register/);
assert.match(booking, /data-booking-forgot/);
assert.match(booking, /label: 'Повтор пароля'/);
assert.match(booking, /prepareAccount\(state\.tenantId, \{ identifier \}\)/);
assert.match(booking, /prepareAccount\(state\.tenantId, \{ email, phone \}\)/);
assert.match(booking, /loginAccount\(state\.tenantId, identifier, password\)/);
assert.match(booking, /accountTerms: currentAccountTermsFact\(state\)/);
assert.match(booking, /saveTenantConsents\(state\)/);
assert.match(booking, /getAccountPlatformState/);
assert.match(booking, /getAccountConsentState/);
const globalAccountHomeBlock = booking.slice(
  booking.indexOf('async function renderGlobalClientHome'),
  booking.indexOf('async function continueGlobalIdentity'),
);
assert.doesNotMatch(globalAccountHomeBlock, /entry', 'account'/);
assert.doesNotMatch(globalAccountHomeBlock, /onOpenRelationship|onOpenRecord/);
assert.match(globalAccountHomeBlock, /onStartBooking: \(tenantId\)/);
assert.match(booking, /slotStillAvailable/);
assert.match(booking, /Выбранное время уже недоступно/);
assert.doesNotMatch(booking, /consentState\.allowed/);
assert.match(booking, /const account = await getAccount\(state\.tenantId\);[\s\S]*?if \(account\) state\.account = account;[\s\S]*?renderWelcome\(root, state\);/);
assert.match(booking, /function backFromFirstBookingStep[\s\S]*?state\.bookingOrigin === 'profile'[\s\S]*?renderWelcome\(root, state\);/);
const bookingBackBlock = booking.slice(
  booking.indexOf('function backFromFirstBookingStep'),
  booking.indexOf('function renderWelcome'),
);
assert.doesNotMatch(bookingBackBlock, /renderAccountEntry\(root, state\);/);
assert.doesNotMatch(booking, /renderAccountHome\(/);
assert.doesNotMatch(booking, /import \{ renderAccount,/);
assert.match(booking, /exitBookingContext\(state, \{ tab: 'contact-detail', tenantId: state\.tenantId \}\)/);
assert.match(booking, /exitBookingContext\(state, \{ tab: 'messages', tenantId: state\.tenantId \}\)/);

// End-user account is the first consumer of shared UI Reference V2.
assert.match(accountShell, /v2Header\(\{/);
assert.match(accountShell, /v2Shell\(\{/);
assert.match(accountShell, /v2FDeck\(/);
assert.match(accountShell, /v2Section\(/);
assert.match(accountShell, /v2HorizontalRail\(/);
assert.match(accountShell, /entityCard\(\{/);
assert.match(accountShell, /data-account-deck-item/);
assert.match(accountShell, /GLOBAL_ACCOUNT_ROOTS = Object\.freeze\(\[[\s\S]*?id: 'profile', label: 'Профиль'[\s\S]*?id: 'home', label: 'Обзор'[\s\S]*?id: 'contacts', label: 'Контакты'[\s\S]*?id: 'history', label: 'История'/);
assert.match(accountShell, /async function renderGlobalProfile\(/);
assert.match(accountShell, /async function renderGlobalProfileSettings\(/);
assert.match(accountShell, /openGlobalConsentSettingsByContact/);
assert.match(accountShell, /data-account-consent-contact/);
assert.match(accountShell, /openAccountConsentSettings\(state, \{[\s\S]*?tenantId/);
assert.match(accountShell, /label: 'Согласия', data: 'data-account-consents'/);
assert.match(accountShell, /async function renderGlobalContacts\(/);
assert.match(accountShell, /async function renderGlobalContactDetail\(/);
assert.match(accountShell, /state\.accountTab = 'contact-detail'/);
assert.match(accountShell, /async function renderGlobalHistoryDetail\(/);
assert.doesNotMatch(accountShell, /onOpenRelationship: callbacks\.onOpenRelationship/);
assert.match(accountShell, /relationships\.length <= 15/);
assert.match(accountShell, /data-account-contact-search/);
assert.doesNotMatch(accountShell, /async function renderGlobalRepresentatives\(/);
assert.doesNotMatch(accountShell, /export async function renderAccount\(/);
assert.doesNotMatch(accountShell, /async function renderHome\(/);
assert.doesNotMatch(accountShell, /async function renderRepresentatives\(/);
assert.doesNotMatch(accountShell, /async function renderRepresentative\(/);
assert.doesNotMatch(accountShell, /async function renderHistory\(/);
assert.doesNotMatch(accountShell, /async function renderMessages\(/);
assert.doesNotMatch(accountShell, /label: 'Обзор'\s*\},\s*\{ id: 'history'/);
assert.match(accountShell, /async function renderGlobalHome\([\s\S]*?futureRequests\(state\.accountRecords \|\| \[\]\)/);
assert.match(accountShell, /async function renderGlobalContacts\([\s\S]*?const relationships = Array\.isArray\(state\.relationships\)/);
assert.match(accountShell, /async function renderGlobalHistory\([\s\S]*?state\.accountRecords/);
const globalHomeBlock = accountShell.slice(
  accountShell.indexOf('async function renderGlobalHome'),
  accountShell.indexOf('function contactsBody'),
);
assert.doesNotMatch(globalHomeBlock, /relationshipCard\(/);
assert.doesNotMatch(accountShell, /accountBottomNavigation/);
assert.doesNotMatch(accountShell, /bindBottomNavigation/);
assert.match(accountShell, /mountChatThread\(/);
assert.match(chatRuntime, /kind: 'contacts'/);
assert.match(accountShell, /mountChatList\(/);
assert.match(accountShell, /selected \? 'v2-app--chat' : 'v2-app--chat-list'/);
assert.match(accountShell, /sendAccountChatMessage\(selectedTenantId, body, attachments\)/);
assert.match(accountShell, /loadMessages\(state, selectedTenantId\)/);
assert.match(accountShell, /getAccountChatSettings\(state\.tenantId\)/);
assert.doesNotMatch(accountShell, /messageComposer\(|messageThread\(|bindMessageAttachments\(/);
assert.match(accountShell, /projectRecordStatuses/);
assert.match(accountShell, /booked: 'Записался'/);
assert.match(accountShell, /rescheduled: 'Перенёс'/);
assert.match(accountShell, /cancelled: 'Отменил'/);
assert.match(accountShell, /due: 'К оплате'/);
assert.match(accountShell, /paid: 'Оплачено'/);
assert.match(accountShell, /debt: 'Задолженность'/);
assert.match(accountShell, /openAccountPersonalData/);
assert.match(accountShell, /openAccountPasswordSettings/);
assert.match(accountShell, /openAccountConsentSettings/);
assert.match(accountShell, /mountModal\(document\.body, modal/);
assert.doesNotMatch(accountShell, /mountV2Layer\(|v2Layer\(/);
assert.match(accountShell, /async function renderGlobalHistoryDetail/);
assert.match(accountShell, /label: 'Записаться', data: 'data-global-history-repeat'/);
assert.match(accountShell, /state\.accountSelectedChatTenantId/);
assert.match(accountShell, /state\.accountDeckOpen = true/);
assert.doesNotMatch(accountShell, /requestMoment\(request\)\s*[<>]=?\s*nowMoment\(\)\s*\?\s*'Задолженность'/);
assert.doesNotMatch(accountShell, /bookingThemeStyle/);
assert.doesNotMatch(accountShell, /booking-shape--|booking-choice-style--/);
assert.doesNotMatch(accountShell, /accountThemeClasses/);
assert.match(accountShell, /root\.innerHTML = shell;/);

// Personal-data modal uses the Book controls, including Book calendar.
assert.match(personalData, /photoField\(\{ name: 'photo'/);
assert.match(personalData, /addLabel: '\+ Телефон'/);
assert.match(personalData, /addLabel: '\+ Email'/);
assert.match(personalData, /showEmptyRow: false/);
assert.match(personalData, /label: 'Telegram'/);
assert.match(personalData, /\{ value: 'male', label: 'Мужской' \}/);
assert.match(personalData, /\{ value: 'female', label: 'Женский' \}/);
assert.doesNotMatch(personalData, /label: 'Другой'/);
assert.doesNotMatch(personalData, /type: 'date'/);
assert.match(personalData, /initCalendar\(calendarHost/);
assert.match(personalData, /links\(\{ links:/);
assert.match(personalData, /button\('Сохранить', \{ type: 'submit' \}\)/);
assert.match(personalData, /updateAccount\(state\.tenantId/);
assert.match(personalData, /profileData:/);
assert.match(personalData, /phones: unique/);
assert.match(personalData, /emails: unique/);
assert.match(personalData, /telegram:/);
assert.match(personalData, /links: collectLinks/);

assert.match(repeatedFields, /showEmptyRow = true/);
assert.match(inputsUi, /phoneCountryLabel/);
assert.match(inputsUi, /full\.match\(\/\\\+\\d\{1,4\}\\b\/\)/);

// Password and consent account settings are functional server-backed controls.
assert.match(passwordSettings, /Текущий пароль/);
assert.match(passwordSettings, /Новый пароль/);
assert.match(passwordSettings, /Повторите новый пароль/);
assert.match(passwordSettings, /changeAccountPassword\(state\.tenantId/);
assert.match(passwordSettings, /newPassword !== repeatPassword/);
assert.match(consentSettings, /getAccountConsentState\(scopeTenantId\)/);
assert.match(consentSettings, /revokeAccountConsent\(scopeTenantId, consent\.documentId\)/);
assert.match(consentSettings, /Отозвать согласие/);
assert.match(consentSettings, /Отмена/);
assert.match(accountApi, /account\/password/);
assert.match(accountSettingsController, /@Put\(':tenantId\/account\/password'\)/);
assert.match(accountSettingsController, /changeAccountPassword/);
assert.match(onlineBookingService, /async changeAccountPassword/);
const publicAccountBlock = onlineBookingService.slice(
  onlineBookingService.indexOf('function publicAccount('),
  onlineBookingService.indexOf('@Injectable()'),
);
assert.doesNotMatch(publicAccountBlock, /\buei\s*:/, 'Public Account projection must not expose internal UEI');
assert.match(onlineBookingService, /async accountTenantContactContext\(/);
assert.match(onlineBookingService, /compare\(current, account\.passwordHash\)/);
assert.match(onlineBookingService, /passwordHash: await hash\(next, 12\)/);
assert.match(onlineBookingService, /photo: text\(source\.photo\)/);
assert.match(onlineBookingService, /phones: uniqueStrings/);
assert.match(onlineBookingService, /emails: uniqueStrings/);
assert.match(onlineBookingService, /telegram: text\(source\.telegram\)/);
assert.match(onlineBookingService, /links,/);

// Online booking settings stay inside the single Shared workspace Z and expose only header/action sources.
assert.match(bookingSettingsUi, /workspaceHeaderContext\(\{/);
assert.match(bookingSettingsUi, /back: \{ data: 'data-online-booking-back'/);
assert.match(bookingSettingsUi, /data-v2-primary-action/);
assert.match(bookingSettingsUi, /data-v2-primary-visible="false"/);
assert.doesNotMatch(bookingSettingsUi, /\bappShell\s*\(/);
assert.doesNotMatch(bookingSettingsUi, /\bappHeader\s*\(/);
assert.doesNotMatch(bookingSettingsUi, /app-content--book-shell/);
assert.match(headerUi, /data-workspace-back-source/);
assert.match(headerUi, /actionData/);
assert.match(bookingSettingsUi, /folderList\(\[/);
assert.match(bookingSettingsUi, /Приветствие/);
assert.match(bookingSettingsUi, /Внешний вид/);
assert.match(bookingSettingsUi, /Время записи/);
assert.match(bookingSettingsUi, /function renderWelcome/);
assert.match(bookingSettingsUi, /function renderAppearance/);
assert.match(bookingSettingsUi, /function renderTime/);
assert.match(bookingSettingsUi, /setSaveVisible\(root, false\)/);
assert.match(bookingSettingsUi, /form\.addEventListener\('input', updatePreview\)/);
assert.match(bookingSettingsUi, /form\.addEventListener\('change', updatePreview\)/);
assert.match(bookingSettingsUi, /twoColumnLayout\(/);
assert.match(bookingSettingsUi, /label: 'Отменить'/);
assert.match(bookingSettingsUi, /label: 'Сбросить'/);
assert.match(bookingSettingsUi, /variant: 'outline'/);
assert.match(bookingSettingsUi, /saveBookingSettings\(settingsDraft\(form, saved\)\)/);
assert.match(bookingSettingsUi, /BOOKING_SLOT_STEPS\.map/);
assert.doesNotMatch(bookingSettingsUi, /Сохранить оформление/);
assert.match(indexHtml, /settings\/online-booking\/online-booking\.css/);

// Mini App owns legal consent management; Chat settings must not mutate advertising consent.
assert.match(accountApi, /account\/consents/);
assert.match(accountApi, /account\/consents\/\$\{encodeURIComponent\(documentId\)\}\/revoke/);
assert.match(accountApi, /account\/chat\/settings/);
assert.doesNotMatch(accountApi, /account\/chat\/telegram-consent/);
assert.doesNotMatch(accountApi, /setBookingTelegramConsent/);
assert.doesNotMatch(onlineBookingController, /messages-consent/);
assert.doesNotMatch(onlineBookingController, /telegram-consent/);
assert.doesNotMatch(consentPolicy, /async canSendMessages\(/);
assert.match(consentPolicy, /async canSendMarketing\(/);
assert.match(telegramBot, /purpose === 'MARKETING'[\s\S]*canSendMarketing\(tenantId, 'TELEGRAM', identity\.externalUserId\)/);

// Media is a real persisted message property, not a decorative paperclip.
assert.match(accountApi, /sendAccountChatMessage\(tenantId, body, attachments = \[\]\)/);
assert.match(onlineBookingController, /@Body\(\) body: \{ body\?: unknown; attachments\?: unknown \}/);
assert.match(onlineBookingController, /attachments,/);
assert.match(communicationService, /function normalizeAttachments/);
assert.match(communicationService, /"attachments"/);
assert.match(communicationService, /\$\{attachmentsJson\}::jsonb/);
assert.match(communicationHistory, /m\."attachments"/);
assert.match(communicationHistory, /'\[\]'::jsonb AS "attachments"/);
assert.match(messageAttachmentMigration, /ADD COLUMN "attachments" JSONB NOT NULL DEFAULT '\[\]'::jsonb/);

// Shared V2 owns H / Z / F geometry while legacy Shared UI remains available to non-migrated contours.
assert.match(v2Ui, /export function v2Header/);
assert.match(v2Ui, /export function v2Shell/);
assert.match(v2Ui, /export function v2EList/);
assert.match(v2Ui, /export function v2FDeck/);
assert.match(v2Ui, /export function v2Layer/);
assert.match(v2Ui, /export function initV2Swipe/);
assert.match(v2Ui, /app\?\.classList\.add\('is-revealing-deck'\)/);
assert.match(v2Ui, /const visualDepth = \(index - activeIndex \+ count\) % count/);
assert.match(v2Ui, /const tabStep = 48/);
assert.match(v2Ui, /const tabOrder = count - 1 - visualDepth/);
assert.match(v2Ui, /const depthY = tabOrder \* tabStep/);
assert.match(v2Ui, /\.slice\(0, 7\)/);
assert.match(v2Ui, /data-v2-f-index="\$\{index\}"/);
assert.doesNotMatch(v2Ui, /data-v2-f-level/);
assert.match(v2Ui, /export function initV2WorkspaceInteraction/);
assert.match(v2Ui, /stage\.addEventListener\('pointerdown', down\)/);
assert.match(v2Ui, /stage\.addEventListener\('pointermove', move/);
assert.match(v2Ui, /const leftOrDownLeft = dx < -5 && dy >= -8/);
assert.match(v2Ui, /const downOnly = dy > 5/);
assert.match(v2Ui, /--v2-e-drag-y/);
assert.match(v2Ui, /directPickThreshold = 14/);
const workspaceOwner = v2Ui.slice(v2Ui.indexOf('export function initV2WorkspaceInteraction'), v2Ui.indexOf('export function initV2StickerSwipe'));
assert.doesNotMatch(workspaceOwner, /initV2DeckSwipe\(/);
assert.doesNotMatch(workspaceOwner, /initV2Swipe\(/);
assert.doesNotMatch(workspaceOwner, /--v2-e-drag-x/);
assert.match(v2Ui, /axis = Math\.abs\(nextX\) >= Math\.abs\(nextY\) \* 1\.08 \? 'horizontal' : 'vertical'/);
assert.match(v2Css, /\.v2-z\{[\s\S]*?touch-action:pan-y/);
assert.match(v2Css, /\.v2-sticker-screen\{[\s\S]*?touch-action:pan-y/);
assert.match(styleCss, /--surface-dark:#2F3338/);
assert.match(v2Css, /--v2-base:var\(--surface-dark\)/);
assert.match(v2Css, /--v2-f-open-x:min\(30vw,117px\)/);
assert.match(v2Css, /--v2-fe-open-x:min\(40vw,156px\)/);
assert.match(v2Css, /--v2-deck-width:calc\(var\(--v2-f-open-x\) - var\(--v2-gap\)\)/);
assert.match(v2Css, /--v2-card-handle:48px/);
assert.match(v2Css, /--v2-card-handle-min:44px/);
assert.match(v2Css, /--v2-deck-top:34px/);
assert.match(v2Css, /--v2-gap:20px/);
assert.match(v2Css, /border:1px solid rgba\(17,17,17,.32\)/);
assert.match(v2Css, /\.v2-deck__card strong\{[\s\S]*?height:var\(--v2-card-handle\);[\s\S]*?transform:none/);
assert.match(v2Css, /--v2-e-max-height:66\.667%/);
assert.match(v2Css, /\.v2-app\.has-e-deck \.v2-deck\{width:calc\(var\(--v2-fe-open-x\) - var\(--v2-gap\)\)\}/);
assert.match(v2Css, /\.v2-e-deck\{[\s\S]*?z-index:11;[\s\S]*?bottom:0;[\s\S]*?height:var\(--v2-e-height,var\(--v2-e-max-height\)\);[\s\S]*?max-height:var\(--v2-e-max-height\)/);
assert.match(v2Css, /\.v2-app\.has-e-deck \.v2-e-deck\{width:calc\(var\(--v2-fe-open-x\) - var\(--v2-gap\)\)\}/);
assert.match(v2Css, /\.v2-deck__card\{[\s\S]*?bottom:0;[\s\S]*?height:auto;[\s\S]*?pointer-events:none/);
assert.match(v2Css, /\.v2-deck__card strong\{[\s\S]*?height:var\(--v2-card-handle\);[\s\S]*?pointer-events:auto;[\s\S]*?touch-action:none/);
assert.match(v2Css, /\.v2-e-card\{[\s\S]*?bottom:0;[\s\S]*?pointer-events:none/);
assert.match(v2Css, /\.v2-e-card strong\{[\s\S]*?min-width:var\(--v2-card-handle-min\);[\s\S]*?height:var\(--v2-card-handle\);[\s\S]*?pointer-events:auto;[\s\S]*?touch-action:none/);
assert.doesNotMatch(v2Css, /--v2-e-pull/);
assert.match(v2Css, /\.v2-front\{[\s\S]*?background:var\(--v2-base\)/);
assert.match(v2Css, /\.v2-app\.is-deck-open > \.v2-app__stage > \.v2-front/);
assert.match(v2Css, /\.v2-fe-deck\{[\s\S]*?transform:none/);
assert.doesNotMatch(v2Css, /\.v2-app\.is-deck-open[^\{]*\.v2-z[^\{]*\{[^}]*transform:/s);
assert.match(v2Css, /box-shadow:-18px 12px 34px rgba\(0,0,0,.18\)/);
assert.match(v2Css, /box-shadow:-9px 8px 14px -11px rgba\(0,0,0,.34\)/);
assert.match(v2Css, /\.v2-z \.entity-card\{transform:translateY\(-2px\)/);
assert.match(v2Css, /\.v2-app\.is-revealing-deck \.v2-fe-deck/);
assert.match(accountMobileCss, /\.app-shell\.app-shell--booking\{[\s\S]*?background:var\(--v2-base\)/);
assert.match(coreJs, /setThemeColor\('#2F3338'\)/);
assert.match(coreJs, /setThemeColor\('#F5F5F3'\)/);
assert.match(v2Css, /\.v2-z[\s\S]*?border-radius:var\(--v2-z-radius\) 0 0 0/);
assert.match(v2Css, /\.v2-app__stage\{[\s\S]*?height:calc\(var\(--visual-vh,100dvh\) - 72px\)/);
assert.match(v2Css, /\.v2-front\{[\s\S]*?height:calc\(var\(--visual-vh,100dvh\) - 72px\)/);
assert.match(v2Css, /\.v2-z\{[\s\S]*?box-sizing:border-box;[\s\S]*?height:calc\(var\(--visual-vh,100dvh\) - 72px\);[\s\S]*?overflow-y:auto/);
assert.match(v2Css, /\.v2-header__slot--a \.v2-header__control\{[\s\S]*?border:2px solid var\(--v2-yellow\)/);
assert.match(v2Css, /\.v2-header__slot--c \.v2-header__control--white\{border-color:#111;background:#fff;color:#111\}/);
assert.match(v2Ui, /slot\.variant === 'white' \|\| slot\.variant === 'secondary'/);
assert.match(v2Ui, /host\.classList\.add\('has-v2-layer'\)/);
assert.match(v2Css, /\.v2-z:not\(\.v2-z--layer\)\.has-v2-layer\{transform:translateZ\(0\);overflow:hidden\}/);
assert.match(v2Css, /\.v2-layer--top[\s\S]*?border-radius:var\(--v2-z-radius\) 0 0 0/);
assert.match(v2Css, /\.v2-layer--standard[\s\S]*?inset:0;[\s\S]*?border-radius:var\(--v2-z-radius\) 0 0 0/);
assert.match(v2Css, /\.v2-layer--bottom[\s\S]*?bottom:0;[\s\S]*?border-radius:0/);
assert.match(v2Css, /\.v2-layer--technical[\s\S]*?border-radius:0;[\s\S]*?box-shadow:0 18px 46px/);
assert.match(v2Css, /\.v2-legal-cards\{display:flex;gap:10px;overflow-x:auto/);
assert.match(v2Css, /\.v2-deck__card[\s\S]*?border-radius:0 var\(--v2-z-radius\) 0 0/);
assert.match(v2Css, /\.booking-account--account \.v2-app \.booking-time-grid\{grid-template-columns:repeat\(3,minmax\(0,1fr\)\)\}/);
assert.match(v2Css, /\.booking-account--account \.v2-app \.booking-time-slot\{border-radius:0/);
assert.match(indexHtml, /ui\/v2\/v2\.css/);
assert.match(indexHtml, /ui\/selection\/segment-control\.css/);
assert.match(indexHtml, /ui\/info\/info\.css/);
assert.match(buttonCss, /\.ui-button\{[\s\S]*?border:1px solid var\(--white\);[\s\S]*?border-radius:14px[\s\S]*?background:var\(--text\);color:var\(--white\)/);
assert.match(buttonCss, /\.ui-button--secondary,\.ui-button--outline\{border-color:var\(--text\);background:var\(--white\);color:var\(--text\)\}/);
assert.match(buttonCss, /\.ui-button:disabled\{/);
assert.match(segmentUi, /filter\(Boolean\)\.map/);
assert.doesNotMatch(segmentUi, /\.slice\(0, 3\)/);
assert.match(segmentCss, /\.segment-control\{[\s\S]*?border:1px solid var\(--text\);[\s\S]*?border-radius:14px;[\s\S]*?background:var\(--white\)/);
assert.match(segmentCss, /\.segment-control button\.is-active\{[\s\S]*?background:var\(--text\);[\s\S]*?color:var\(--white\)/);
assert.match(entityCardCss, /--entity-card-depth:#2C2A28/);
assert.match(entityCardCss, /--entity-card-mid:#817A73/);
assert.match(entityCardCss, /--entity-card-light:#D7D1CA/);
assert.doesNotMatch(entityCardCss, /--entity-card-neutral|var\(--v2-disabled\)|var\(--button-secondary\)/);
assert.match(entityCardCss, /\.entity-card\.has-image \.entity-card__background/);
assert.match(infoUi, /export function infoUI/);
assert.match(infoUi, /export function initInfoUI/);
assert.match(infoCss, /\.ui-info__trigger\{[\s\S]*?border:1px solid #111;[\s\S]*?border-radius:0/);
assert.match(infoCss, /\.ui-info--inverse/);
assert.match(timeUi, /variant:'top'/);
assert.match(styleCss, /--app-max-width:390px/);
assert.doesNotMatch(accountMobileCss, /--app-max-width:/);
assert.match(accountMobileCss, /\.app-shell\.app-shell--booking\s*\{[\s\S]*?width:min\(100%,var\(--app-max-width\)\);[\s\S]*?max-width:var\(--app-max-width\);/);
assert.match(chatUi, /messageThread/);
assert.match(chatUi, /attachmentTrigger = 'composer'/);
assert.match(chatCss, /\.message-composer\{position:fixed/);
assert.equal(fs.existsSync('ui/shell/index.js'), false);
assert.equal(fs.existsSync('ui/shell/shell.css'), false);

assert.doesNotMatch(journalListUi, /getBoundingPersonRect/);
assert.match(journalListUi, /getBoundingClientRect\(\)/);

assert.match(bookingUi, /Утро/);
assert.match(bookingUi, /День/);
assert.match(bookingUi, /Вечер/);

console.log('booking account UI tests passed');
