import assert from 'node:assert/strict';
import fs from 'node:fs';

const booking = fs.readFileSync('online-booking/booking.js', 'utf8');
const accountShell = fs.readFileSync('online-booking/account-shell.js', 'utf8');
const personalData = fs.readFileSync('online-booking/personal-data.js', 'utf8');
const passwordSettings = fs.readFileSync('online-booking/password-settings.js', 'utf8');
const consentSettings = fs.readFileSync('online-booking/consent-settings.js', 'utf8');
const bookingSettingsUi = fs.readFileSync('settings/online-booking/online-booking.js', 'utf8');
const bookingAccountApi = fs.readFileSync('core/booking-account/index.js', 'utf8');
const onlineBookingController = fs.readFileSync('server/src/online-booking/online-booking.controller.ts', 'utf8');
const accountSettingsController = fs.readFileSync('server/src/online-booking/booking-account-settings.controller.ts', 'utf8');
const onlineBookingService = fs.readFileSync('server/src/online-booking/online-booking.service.ts', 'utf8');
const communicationService = fs.readFileSync('server/src/communication/communication.service.ts', 'utf8');
const communicationHistory = fs.readFileSync('server/src/communication/communication-history.service.ts', 'utf8');
const messageAttachmentMigration = fs.readFileSync('server/prisma/migrations/20260914010000_message_attachments/migration.sql', 'utf8');
const consentPolicy = fs.readFileSync('server/src/document-state/consent-policy.service.ts', 'utf8');
const telegramBot = fs.readFileSync('server/src/communication/telegram-bot.service.ts', 'utf8');
const inputsUi = fs.readFileSync('ui/inputs/index.js', 'utf8');
const repeatedFields = fs.readFileSync('ui/repeated-fields/index.js', 'utf8');
const shellUi = fs.readFileSync('ui/shell/index.js', 'utf8');
const shellCss = fs.readFileSync('ui/shell/shell.css', 'utf8');
const styleCss = fs.readFileSync('css/style.css', 'utf8');
const clientMobileCss = fs.readFileSync('ui/shell/client-mobile.css', 'utf8');
const clientAccountThemeCss = fs.readFileSync('ui/shell/client-account-theme.css', 'utf8');
const indexHtml = fs.readFileSync('index.html', 'utf8');
const bookingUi = fs.readFileSync('ui/booking/index.js', 'utf8');

// Registration owns agreements. Booking starts only after account resolution.
assert.match(booking, /renderClientAccount/);
assert.match(booking, /appHeader\(\{ title, back, action \}\)/);
assert.match(booking, /appShell\(\{/);
assert.match(booking, /bookingThemeStyle\(state\.settings\)/);
assert.match(booking, /bookingChoiceCards\(/);
assert.match(booking, /bookingTimeGroups\(/);
assert.match(booking, /function renderRegistrationAgreements/);
assert.match(booking, /function renderAccountEntry/);
assert.match(booking, /function renderAccountDetails/);
assert.match(booking, /function renderPassword/);
assert.match(booking, /function renderWorkplaces/);
assert.match(booking, /function renderProcedures/);
assert.match(booking, /function renderDates/);
assert.match(booking, /function renderTimes/);
assert.match(booking, /function renderConfirmation/);
assert.match(booking, /subtitle: 'Согласия относятся к регистрации и аккаунту клиента'/);
assert.match(booking, /if \(prepared\.exists\) renderPassword\(root, state\);/);
assert.match(booking, /else renderAccountDetails\(root, state\);/);
assert.match(booking, /if \(payload\.clientCardExisted\)/);
assert.match(booking, /nextBookingStep\(root, state\)/);
assert.match(booking, /saveRegistrationConsents\(state\)/);
assert.match(booking, /submitBookingConsents\(state\.tenantId, consents\)/);
assert.match(booking, /data-booking-workplaces-back[\s\S]*?backFromFirstBookingStep\(root, state\)/);
assert.match(booking, /if \(state\.lockedWorkplaceKey\) backFromFirstBookingStep\(root, state\)/);
assert.match(booking, /data-booking-dates-back[\s\S]*?renderProcedures\(root, state\)/);
assert.match(booking, /data-booking-times-back[\s\S]*?renderDates\(root, state\)/);
assert.match(booking, /data-booking-confirm-back[\s\S]*?renderTimes\(root, state\)/);
assert.match(booking, /meta:\s*\[\s*\{ value: money\(subtotal\), label: 'Стоимость' \}/);
assert.match(booking, /\{ value: state\.from, row: 3 \}/);
assert.doesNotMatch(booking, /\$\{state\.from\} - \$\{state\.to\}/);
assert.match(booking, /onRepeat:/);
assert.doesNotMatch(booking, /−\$\{discount\}/);
assert.doesNotMatch(booking, /durationText\(duration\)/);
assert.doesNotMatch(booking, /personalDataAccordion/);
assert.doesNotMatch(booking, /type:\s*'date'/);
assert.match(booking, /getBookingConsentState/);
assert.match(booking, /async function refreshAccountConsentState/);
assert.match(booking, /if \(consentState\.allowed\) \{[\s\S]*?nextBookingStep\(root, state\)/);
assert.match(booking, /state\.registrationMode = 'repair'/);

// Client profile/account stays on canonical shared primitives.
assert.match(accountShell, /entityCard\(\{/);
assert.match(accountShell, /className: 'entity-card--hero'/);
assert.match(accountShell, /image: profile\.photo \|\| ''/);
assert.doesNotMatch(accountShell, /clientProfileCard\(/);
assert.match(accountShell, /bookingThemeStyle\(state\.settings\)/);
assert.match(accountShell, /booking-client booking-client--account booking-shape--\$\{shape\}/);
assert.match(accountShell, /label: 'Стоимость'/);
assert.match(accountShell, /label: 'Скидка'/);
assert.match(accountShell, /label: 'Оплачено'/);
assert.match(accountShell, /const source = Array\.isArray\(account\.programs\) \? account\.programs : \[\]/);
assert.doesNotMatch(accountShell, /label: 'Депозит'/);
assert.doesNotMatch(accountShell, /label: 'Личный счёт'/);
assert.match(accountShell, /app-media-rail--placeholder/);
assert.match(accountShell, /openClientPersonalData/);
assert.match(accountShell, /openClientPasswordSettings/);
assert.match(accountShell, /openClientConsentSettings/);
assert.match(accountShell, /label: 'Изменить пароль'/);
assert.match(accountShell, /label: 'Согласия'/);
assert.match(accountShell, /data-client-consents/);
assert.match(accountShell, /data-chat-consents/);
assert.match(accountShell, /listEntry\(\{\s*columns:/s);
assert.match(accountShell, /variant: 'large'/);
assert.match(accountShell, /readOnlyReceipt\(/);
assert.match(accountShell, /label: 'Повторить запись'/);
assert.doesNotMatch(accountShell, /label: 'Повторить процедуру'/);
assert.match(accountShell, /action: \{ label: 'Записаться'/);
assert.match(accountShell, /messageComposer\(\{ attachments: true \}\)/);
assert.match(accountShell, /data-message-attachment/);
assert.match(accountShell, /sendBookingChatMessage\(state\.tenantId, body, attachments\)/);
assert.match(accountShell, /className: 'app-view-shell--chat'/);
assert.match(accountShell, /getBookingRequests\(state\.tenantId\)\.catch\(\(\) => \[\]\)/);
assert.match(accountShell, /data-client-chat-settings/);
assert.match(accountShell, /getBookingChatSettings\(state\.tenantId\)/);
assert.match(accountShell, /setBookingTelegramConsent\(state\.tenantId, !telegram\.enabled\)/);
assert.match(accountShell, /label: 'Telegram'.*checked: Boolean\(telegram\.enabled\).*disabled: !telegram\.linked/s);
assert.doesNotMatch(accountShell, /Promise\.allSettled\(unread/);
assert.doesNotMatch(accountShell, /markBookingNotificationRead\(state\.tenantId, item\.notificationId\)/);
assert.match(accountShell, /markBookingNotificationRead\(state\.tenantId, message\.notificationId\)/);
assert.match(accountShell, /node\.addEventListener\('click', \(\) => void openNotification\(\)\)/);

// Personal-data modal uses the Book controls, including Book calendar.
assert.match(personalData, /photoField\(\{ name: 'photo'/);
assert.match(personalData, /addLabel: '\+ Телефон'/);
assert.match(personalData, /addLabel: '\+ Email'/);
assert.match(personalData, /showEmptyRow: false/);
assert.match(personalData, /label: 'Telegram'/);
assert.match(personalData, /\{ value: 'male', label: 'Мужской' \}/);
assert.match(personalData, /\{ value: 'female', label: 'Женский' \}/);
assert.doesNotMatch(personalData, /label: 'Другой'/);
assert.doesNotMatch(personalData, /type: 'date'/);
assert.match(personalData, /initCalendar\(calendarHost/);
assert.match(personalData, /links\(\{ links:/);
assert.match(personalData, /button\('Сохранить', \{ type: 'submit' \}\)/);
assert.match(personalData, /updateBookingAccount\(state\.tenantId/);
assert.match(personalData, /profileData:/);
assert.match(personalData, /phones: unique/);
assert.match(personalData, /emails: unique/);
assert.match(personalData, /telegram:/);
assert.match(personalData, /links: collectLinks/);

assert.match(repeatedFields, /showEmptyRow = true/);
assert.match(inputsUi, /phoneCountryLabel/);
assert.match(inputsUi, /full\.match\(\/\\\+\\d\{1,4\}\\b\/\)/);

// Password and consent account settings are functional server-backed controls.
assert.match(passwordSettings, /Текущий пароль/);
assert.match(passwordSettings, /Новый пароль/);
assert.match(passwordSettings, /Повторите новый пароль/);
assert.match(passwordSettings, /changeBookingPassword\(state\.tenantId/);
assert.match(passwordSettings, /newPassword !== repeatPassword/);
assert.match(consentSettings, /getBookingConsentState\(state\.tenantId\)/);
assert.match(consentSettings, /revokeBookingConsent\(state\.tenantId, consent\.documentId\)/);
assert.match(consentSettings, /Отозвать согласие/);
assert.match(consentSettings, /Отмена/);
assert.match(bookingAccountApi, /account\/password/);
assert.match(accountSettingsController, /@Put\(':tenantId\/account\/password'\)/);
assert.match(accountSettingsController, /changeAccountPassword/);
assert.match(onlineBookingService, /async changeAccountPassword/);
assert.match(onlineBookingService, /compare\(current, account\.passwordHash\)/);
assert.match(onlineBookingService, /passwordHash: await hash\(next, 12\)/);
assert.match(onlineBookingService, /photo: text\(source\.photo\)/);
assert.match(onlineBookingService, /phones: uniqueStrings/);
assert.match(onlineBookingService, /emails: uniqueStrings/);
assert.match(onlineBookingService, /telegram: text\(source\.telegram\)/);
assert.match(onlineBookingService, /links,/);

// Online booking settings use the shared Book shell and three focused screens.
assert.match(bookingSettingsUi, /appShell\(\{/);
assert.match(bookingSettingsUi, /appHeader\(\{/);
assert.match(bookingSettingsUi, /folderList\(\[/);
assert.match(bookingSettingsUi, /Приветствие/);
assert.match(bookingSettingsUi, /Внешний вид/);
assert.match(bookingSettingsUi, /Время записи/);
assert.match(bookingSettingsUi, /function renderWelcome/);
assert.match(bookingSettingsUi, /function renderAppearance/);
assert.match(bookingSettingsUi, /function renderTime/);
assert.match(bookingSettingsUi, /setSaveVisible\(root, false\)/);
assert.match(bookingSettingsUi, /form\.addEventListener\('input', updatePreview\)/);
assert.match(bookingSettingsUi, /form\.addEventListener\('change', updatePreview\)/);
assert.match(bookingSettingsUi, /twoColumnLayout\(/);
assert.match(bookingSettingsUi, /label: 'Отменить'/);
assert.match(bookingSettingsUi, /label: 'Сбросить'/);
assert.match(bookingSettingsUi, /variant: 'outline'/);
assert.match(bookingSettingsUi, /saveBookingSettings\(settingsDraft\(form, saved\)\)/);
assert.match(bookingSettingsUi, /BOOKING_SLOT_STEPS\.map/);
assert.doesNotMatch(bookingSettingsUi, /Сохранить оформление/);
assert.match(indexHtml, /settings\/online-booking\/online-booking\.css/);

// Chat consent remains exact Contact Point policy.
assert.match(bookingAccountApi, /account\/chat\/settings/);
assert.match(bookingAccountApi, /account\/chat\/telegram-consent/);
assert.match(onlineBookingController, /contactPointConsentState\([\s\S]*?'TELEGRAM'[\s\S]*?identity\.externalUserId[\s\S]*?'messages-consent'/);
assert.match(onlineBookingController, /acceptContactPointConsent\([\s\S]*?'TELEGRAM'[\s\S]*?identity\.externalUserId[\s\S]*?'client-chat-settings'/);
assert.match(onlineBookingController, /revokeContactPointConsent\([\s\S]*?'TELEGRAM'[\s\S]*?identity\.externalUserId[\s\S]*?'client-chat-settings'/);
assert.match(consentPolicy, /async canSendMessages\(tenantId: string, typeValue: unknown, value: unknown\)/);
assert.match(telegramBot, /canSendMessages\(tenantId, 'TELEGRAM', identity\.externalUserId\)/);
assert.doesNotMatch(telegramBot, /canSendMessages\(tenantId, personKey/);

// Media is a real persisted message property, not a decorative paperclip.
assert.match(bookingAccountApi, /sendBookingChatMessage\(tenantId, body, attachments = \[\]\)/);
assert.match(onlineBookingController, /@Body\(\) body: \{ body\?: unknown; attachments\?: unknown \}/);
assert.match(onlineBookingController, /attachments,/);
assert.match(communicationService, /function normalizeAttachments/);
assert.match(communicationService, /"attachments"/);
assert.match(communicationService, /\$\{attachmentsJson\}::jsonb/);
assert.match(communicationHistory, /m\."attachments"/);
assert.match(communicationHistory, /'\[\]'::jsonb AS "attachments"/);
assert.match(messageAttachmentMigration, /ADD COLUMN "attachments" JSONB NOT NULL DEFAULT '\[\]'::jsonb/);

// Shared shell owns A/B/C roles and compact mobile geometry.
assert.match(shellUi, /appHeader/);
assert.match(shellUi, /clientBottomNavigation/);
assert.match(shellUi, /messageThread/);
assert.match(shellUi, /readOnlyReceipt/);
assert.match(shellUi, /label: 'Сообщения', icon: '💬'/);
assert.match(shellUi, /back\.aria \|\| 'Назад', variant: 'secondary'/);
assert.match(shellUi, /settings\.aria \|\| 'Настройки', variant: 'secondary'/);
assert.match(shellUi, /disabled: Boolean\(action\.disabled\)/);
assert.match(shellUi, /attachments = false/);
assert.match(shellUi, /data-message-attachment/);
assert.match(shellCss, /grid-template-columns:var\(--shell-icon-slot\) minmax\(0,1fr\) var\(--shell-action-slot\) var\(--shell-icon-slot\)/);
assert.match(shellCss, /bottom-nav--client/);
assert.match(shellCss, /\.app-view-shell--chat/);
assert.match(shellCss, /\.app-view-shell--chat \.app-view-shell__screen[\s\S]*?overflow-y:auto/);
assert.match(shellCss, /\.message-composer\{position:fixed/);
assert.match(shellCss, /\.message-composer__attach/);
assert.match(indexHtml, /ui\/shell\/client-mobile\.css/);
assert.match(indexHtml, /ui\/shell\/client-account-theme\.css/);
assert.match(styleCss, /--app-max-width:390px/);
assert.doesNotMatch(clientMobileCss, /--app-max-width:/);
assert.match(clientMobileCss, /\.app-shell\.app-shell--booking\s*\{[\s\S]*?width:min\(100%,var\(--app-max-width\)\);[\s\S]*?max-width:var\(--app-max-width\);/);
assert.match(clientMobileCss, /\.app-shell\.app-shell--booking \.app-view-shell[\s\S]*?max-width:100%/);
assert.doesNotMatch(clientMobileCss, /max-width:none/);
assert.match(clientAccountThemeCss, /--text:var\(--booking-dark\)/);
assert.match(clientAccountThemeCss, /--button-secondary:var\(--booking-light\)/);
assert.match(clientAccountThemeCss, /\.app-view-shell--booking-flow/);
assert.match(clientAccountThemeCss, /\.app-view-shell--profile \.app-view-shell__screen\s*\{[\s\S]*?align-content:center;[\s\S]*?place-items:center;/);
assert.match(clientAccountThemeCss, /\.booking-client--account\.booking-shape--round/);
assert.match(clientAccountThemeCss, /\.booking-client--account\.booking-shape--straight/);
assert.match(clientAccountThemeCss, /\.booking-client--account\.booking-shape--cut/);
assert.match(bookingUi, /Утро/);
assert.match(bookingUi, /День/);
assert.match(bookingUi, /Вечер/);

console.log('booking client UI tests passed');