import assert from 'node:assert/strict';
import fs from 'node:fs';

const booking = fs.readFileSync('online-booking/booking.js', 'utf8');
const accountShell = fs.readFileSync('online-booking/account-shell.js', 'utf8');
const personalData = fs.readFileSync('online-booking/personal-data.js', 'utf8');
const passwordSettings = fs.readFileSync('online-booking/password-settings.js', 'utf8');
const consentSettings = fs.readFileSync('online-booking/consent-settings.js', 'utf8');
const bookingSettingsUi = fs.readFileSync('settings/online-booking/online-booking.js', 'utf8');
const accountApi = fs.readFileSync('core/account/index.js', 'utf8');
const onlineBookingController = fs.readFileSync('server/src/online-booking/online-booking.controller.ts', 'utf8');
const accountSettingsController = fs.readFileSync('server/src/online-booking/account-settings.controller.ts', 'utf8');
const onlineBookingService = fs.readFileSync('server/src/online-booking/online-booking.service.ts', 'utf8');
const communicationService = fs.readFileSync('server/src/communication/communication.service.ts', 'utf8');
const communicationHistory = fs.readFileSync('server/src/communication/communication-history.service.ts', 'utf8');
const messageAttachmentMigration = fs.readFileSync('server/prisma/migrations/20260914010000_message_attachments/migration.sql', 'utf8');
const consentPolicy = fs.readFileSync('server/src/tenant-document-archive/consent-policy.service.ts', 'utf8');
const telegramBot = fs.readFileSync('server/src/communication/telegram-bot.service.ts', 'utf8');
const inputsUi = fs.readFileSync('ui/inputs/index.js', 'utf8');
const repeatedFields = fs.readFileSync('ui/repeated-fields/index.js', 'utf8');
const shellUi = fs.readFileSync('ui/shell/index.js', 'utf8');
const shellCss = fs.readFileSync('ui/shell/shell.css', 'utf8');
const styleCss = fs.readFileSync('css/style.css', 'utf8');
const accountMobileCss = fs.readFileSync('ui/shell/account-mobile.css', 'utf8');
const accountThemeCss = fs.readFileSync('ui/shell/account-theme.css', 'utf8');
const indexHtml = fs.readFileSync('index.html', 'utf8');
const bookingUi = fs.readFileSync('ui/booking/index.js', 'utf8');
const v2Ui = fs.readFileSync('ui/v2/index.js', 'utf8');
const v2Css = fs.readFileSync('ui/v2/v2.css', 'utf8');
const coreJs = fs.readFileSync('core.js', 'utf8');

// Public booking selection comes first. UI Reference V2 is the end-user target.
assert.match(booking, /renderAccount/);
assert.match(booking, /v2Header\(\{/);
assert.match(booking, /v2Shell\(\{/);
assert.match(booking, /v2Sticker\(\{/);
assert.match(booking, /v2LegalCards\(/);
assert.match(booking, /v2ServiceStickers\(/);
assert.match(booking, /initV2Swipe\(/);
assert.match(booking, /initV2StickerSwipe\(/);
assert.match(booking, /function renderLegalSticker/);
assert.match(booking, /function renderAccountEntry/);
assert.match(booking, /function renderAccountDetails/);
assert.match(booking, /function renderWorkplaces/);
assert.match(booking, /function renderProcedures/);
assert.match(booking, /function renderDates/);
assert.match(booking, /function renderTimes/);
assert.match(booking, /function renderConfirmation/);
assert.match(booking, /step: 'workplaces'/);
assert.match(booking, /step: 'procedures'/);
assert.match(booking, /step: 'dates'/);
assert.match(booking, /step: 'times'/);
assert.match(booking, /step: 'confirmation'/);
assert.doesNotMatch(booking, /data-booking-workplaces-next/);
assert.match(booking, /data-booking-procedures-next/);
assert.doesNotMatch(booking, /data-booking-dates-next/);
assert.doesNotMatch(booking, /data-booking-times-next/);
assert.match(booking, /state\.workplaceKey = node\.dataset\.bookingWorkplace \|\| '';[\s\S]*?renderProcedures\(root, state\);/);
assert.match(booking, /onDateSelect: \(date\) => \{[\s\S]*?state\.date = date;[\s\S]*?renderTimes\(root, state\);/);
assert.match(booking, /node\.addEventListener\('click', \(\) => \{[\s\S]*?state\.from = slot\.from;[\s\S]*?renderConfirmation\(root, state\);/);
assert.doesNotMatch(booking, /data-booking-workplaces-back/);
assert.doesNotMatch(booking, /data-booking-dates-back/);
assert.doesNotMatch(booking, /data-booking-times-back/);
assert.doesNotMatch(booking, /data-booking-confirm-back/);
assert.match(booking, /label: 'Телефон или email'/);
assert.match(booking, /label: 'Пароль'/);
assert.match(booking, /data-booking-register/);
assert.match(booking, /data-booking-forgot/);
assert.match(booking, /label: 'Повтор пароля'/);
assert.match(booking, /prepareAccount\(state\.tenantId, \{ identifier \}\)/);
assert.match(booking, /prepareAccount\(state\.tenantId, \{ email, phone \}\)/);
assert.match(booking, /loginAccount\(state\.tenantId, identifier, password\)/);
assert.match(booking, /accountTerms: currentAccountTermsFact\(state\)/);
assert.match(booking, /saveTenantConsents\(state\)/);
assert.match(booking, /getAccountPlatformState/);
assert.match(booking, /getAccountConsentState/);
assert.match(booking, /state\.accountTab = 'representative'/);
assert.match(booking, /onChatBack: \(\) => resumeBookingStep\(root, state\)/);
assert.match(booking, /state\.accountChatReturn = 'booking'/);
assert.match(booking, /slotStillAvailable/);
assert.match(booking, /Выбранное время уже недоступно/);
assert.doesNotMatch(booking, /consentState\.allowed/);
assert.match(booking, /const account = await getAccount\(state\.tenantId\);[\s\S]*?if \(account\) state\.account = account;[\s\S]*?renderWelcome\(root, state\);/);
assert.match(booking, /function backFromFirstBookingStep[\s\S]*?state\.bookingOrigin === 'profile'[\s\S]*?renderWelcome\(root, state\);/);
const bookingBackBlock = booking.slice(
  booking.indexOf('function backFromFirstBookingStep'),
  booking.indexOf('function renderWelcome'),
);
assert.doesNotMatch(bookingBackBlock, /renderAccountEntry\(root, state\);/);

// End-user account is the first consumer of shared UI Reference V2.
assert.match(accountShell, /v2Header\(\{/);
assert.match(accountShell, /v2Shell\(\{/);
assert.match(accountShell, /v2FDeck\(/);
assert.match(accountShell, /v2Section\(/);
assert.match(accountShell, /v2HorizontalRail\(/);
assert.match(accountShell, /entityCard\(\{/);
assert.match(accountShell, /data-account-deck-item/);
assert.match(accountShell, /'Представители'/);
assert.match(accountShell, /'История'/);
assert.doesNotMatch(accountShell, /accountBottomNavigation/);
assert.doesNotMatch(accountShell, /bindBottomNavigation/);
assert.match(accountShell, /messageComposer\(\{ attachments: true, attachmentTrigger: 'external' \}\)/);
assert.match(accountShell, /kind: 'contacts'/);
assert.match(accountShell, /kind: 'attachment'/);
assert.match(accountShell, /className: 'v2-app--chat'/);
assert.match(accountShell, /sendAccountChatMessage\(state\.tenantId, messageBody, attachments\)/);
assert.match(accountShell, /getAccountRecords\(state\.tenantId\)\.catch\(\(\) => \[\]\)/);
assert.match(accountShell, /getAccountChatSettings\(state\.tenantId\)/);
assert.match(accountShell, /projectRecordStatuses/);
assert.match(accountShell, /booked: 'Записался'/);
assert.match(accountShell, /rescheduled: 'Перенёс'/);
assert.match(accountShell, /cancelled: 'Отменил'/);
assert.match(accountShell, /due: 'К оплате'/);
assert.match(accountShell, /paid: 'Оплачено'/);
assert.match(accountShell, /debt: 'Задолженность'/);
assert.match(accountShell, /openAccountPersonalData/);
assert.match(accountShell, /openAccountPasswordSettings/);
assert.match(accountShell, /openAccountConsentSettings/);
assert.match(accountShell, /mountV2Layer\(v2Layer/);
assert.match(accountShell, /function renderHistoryDetail/);
assert.match(accountShell, /label: 'Записаться', data: 'data-account-history-repeat'/);
assert.match(accountShell, /state\.accountChatReturn === 'booking'/);
assert.match(accountShell, /state\.accountDeckOpen = true/);
assert.doesNotMatch(accountShell, /requestMoment\(request\)\s*[<>]=?\s*nowMoment\(\)\s*\?\s*'Задолженность'/);

// Personal-data modal uses the Book controls, including Book calendar.
assert.match(personalData, /photoField\(\{ name: 'photo'/);
assert.match(personalData, /addLabel: '\+ Телефон'/);
assert.match(personalData, /addLabel: '\+ Email'/);
assert.match(personalData, /showEmptyRow: false/);
assert.match(personalData, /label: 'Telegram'/);
assert.match(personalData, /\{ value: 'male', label: 'Мужской' \}/);
assert.match(personalData, /\{ value: 'female', label: 'Женский' \}/);
assert.doesNotMatch(personalData, /label: 'Другой'/);
assert.doesNotMatch(personalData, /type: 'date'/);
assert.match(personalData, /initCalendar\(calendarHost/);
assert.match(personalData, /links\(\{ links:/);
assert.match(personalData, /button\('Сохранить', \{ type: 'submit' \}\)/);
assert.match(personalData, /updateAccount\(state\.tenantId/);
assert.match(personalData, /profileData:/);
assert.match(personalData, /phones: unique/);
assert.match(personalData, /emails: unique/);
assert.match(personalData, /telegram:/);
assert.match(personalData, /links: collectLinks/);

assert.match(repeatedFields, /showEmptyRow = true/);
assert.match(inputsUi, /phoneCountryLabel/);
assert.match(inputsUi, /full\.match\(\/\\\+\\d\{1,4\}\\b\/\)/);

// Password and consent account settings are functional server-backed controls.
assert.match(passwordSettings, /Текущий пароль/);
assert.match(passwordSettings, /Новый пароль/);
assert.match(passwordSettings, /Повторите новый пароль/);
assert.match(passwordSettings, /changeAccountPassword\(state\.tenantId/);
assert.match(passwordSettings, /newPassword !== repeatPassword/);
assert.match(consentSettings, /getAccountConsentState\(state\.tenantId\)/);
assert.match(consentSettings, /revokeAccountConsent\(state\.tenantId, consent\.documentId\)/);
assert.match(consentSettings, /Отозвать согласие/);
assert.match(consentSettings, /Отмена/);
assert.match(accountApi, /account\/password/);
assert.match(accountSettingsController, /@Put\(':tenantId\/account\/password'\)/);
assert.match(accountSettingsController, /changeAccountPassword/);
assert.match(onlineBookingService, /async changeAccountPassword/);
const publicAccountBlock = onlineBookingService.slice(
  onlineBookingService.indexOf('function publicAccount('),
  onlineBookingService.indexOf('@Injectable()'),
);
assert.doesNotMatch(publicAccountBlock, /\buei\s*:/, 'Public Account projection must not expose internal UEI');
assert.match(onlineBookingService, /async accountTenantContactContext\(/);
assert.match(onlineBookingService, /compare\(current, account\.passwordHash\)/);
assert.match(onlineBookingService, /passwordHash: await hash\(next, 12\)/);
assert.match(onlineBookingService, /photo: text\(source\.photo\)/);
assert.match(onlineBookingService, /phones: uniqueStrings/);
assert.match(onlineBookingService, /emails: uniqueStrings/);
assert.match(onlineBookingService, /telegram: text\(source\.telegram\)/);
assert.match(onlineBookingService, /links,/);

// Online booking settings use the shared Book shell and three focused screens.
assert.match(bookingSettingsUi, /appShell\(\{/);
assert.match(bookingSettingsUi, /appHeader\(\{/);
assert.match(bookingSettingsUi, /folderList\(\[/);
assert.match(bookingSettingsUi, /Приветствие/);
assert.match(bookingSettingsUi, /Внешний вид/);
assert.match(bookingSettingsUi, /Время записи/);
assert.match(bookingSettingsUi, /function renderWelcome/);
assert.match(bookingSettingsUi, /function renderAppearance/);
assert.match(bookingSettingsUi, /function renderTime/);
assert.match(bookingSettingsUi, /setSaveVisible\(root, false\)/);
assert.match(bookingSettingsUi, /form\.addEventListener\('input', updatePreview\)/);
assert.match(bookingSettingsUi, /form\.addEventListener\('change', updatePreview\)/);
assert.match(bookingSettingsUi, /twoColumnLayout\(/);
assert.match(bookingSettingsUi, /label: 'Отменить'/);
assert.match(bookingSettingsUi, /label: 'Сбросить'/);
assert.match(bookingSettingsUi, /variant: 'outline'/);
assert.match(bookingSettingsUi, /saveBookingSettings\(settingsDraft\(form, saved\)\)/);
assert.match(bookingSettingsUi, /BOOKING_SLOT_STEPS\.map/);
assert.doesNotMatch(bookingSettingsUi, /Сохранить оформление/);
assert.match(indexHtml, /settings\/online-booking\/online-booking\.css/);

// Mini App owns legal consent management; Chat settings must not mutate advertising consent.
assert.match(accountApi, /account\/consents/);
assert.match(accountApi, /account\/consents\/\$\{encodeURIComponent\(documentId\)\}\/revoke/);
assert.match(accountApi, /account\/chat\/settings/);
assert.doesNotMatch(accountApi, /account\/chat\/telegram-consent/);
assert.doesNotMatch(accountApi, /setBookingTelegramConsent/);
assert.doesNotMatch(onlineBookingController, /messages-consent/);
assert.doesNotMatch(onlineBookingController, /telegram-consent/);
assert.doesNotMatch(consentPolicy, /async canSendMessages\(/);
assert.match(consentPolicy, /async canSendMarketing\(/);
assert.match(telegramBot, /purpose === 'MARKETING'[\s\S]*canSendMarketing\(tenantId, 'TELEGRAM', identity\.externalUserId\)/);

// Media is a real persisted message property, not a decorative paperclip.
assert.match(accountApi, /sendAccountChatMessage\(tenantId, body, attachments = \[\]\)/);
assert.match(onlineBookingController, /@Body\(\) body: \{ body\?: unknown; attachments\?: unknown \}/);
assert.match(onlineBookingController, /attachments,/);
assert.match(communicationService, /function normalizeAttachments/);
assert.match(communicationService, /"attachments"/);
assert.match(communicationService, /\$\{attachmentsJson\}::jsonb/);
assert.match(communicationHistory, /m\."attachments"/);
assert.match(communicationHistory, /'\[\]'::jsonb AS "attachments"/);
assert.match(messageAttachmentMigration, /ADD COLUMN "attachments" JSONB NOT NULL DEFAULT '\[\]'::jsonb/);

// Shared V2 owns H / Z / F geometry while legacy Shared UI remains available to non-migrated contours.
assert.match(v2Ui, /export function v2Header/);
assert.match(v2Ui, /export function v2Shell/);
assert.match(v2Ui, /export function v2FDeck/);
assert.match(v2Ui, /export function v2Layer/);
assert.match(v2Ui, /export function initV2Swipe/);
assert.match(v2Ui, /app\?\.classList\.add\('is-revealing-deck'\)/);
assert.match(v2Ui, /const visualDepth = \(index - activeIndex \+ count\) % count/);
assert.match(v2Ui, /const depthStepX = count > 1 \? Math\.min\(10, 18 \/ \(count - 1\)\) : 0/);
assert.match(v2Ui, /const depthY = visualDepth \* 8/);
assert.match(v2Ui, /\.slice\(0, 7\)/);
assert.match(v2Ui, /data-v2-f-level="F\$\{index \+ 1\}"/);
assert.match(v2Ui, /const direction = finalDx < 0 \? 1 : -1/);
assert.match(v2Ui, /const nextIndex = \(activeIndex \+ direction \+ cards\.length\) % cards\.length/);
assert.match(v2Ui, /is-cycling-under/);
assert.match(v2Ui, /axis = Math\.abs\(nextX\) > Math\.abs\(nextY\) \* 1\.25 \? 'horizontal' : 'vertical'/);
assert.match(v2Css, /\.v2-z\{[\s\S]*?touch-action:pan-y/);
assert.match(v2Css, /\.v2-sticker-screen\{[\s\S]*?touch-action:pan-y/);
assert.match(v2Css, /--v2-base:#2F3338/);
assert.match(v2Css, /--v2-z-open-x:min\(33\.333vw,130px\)/);
assert.match(v2Css, /--v2-deck-width:calc\(var\(--v2-z-open-x\) - var\(--v2-gap\)\)/);
assert.match(v2Css, /--v2-deck-top:34px/);
assert.match(v2Css, /--v2-gap:20px/);
assert.match(v2Css, /border:1px solid rgba\(17,17,17,.32\)/);
assert.match(v2Css, /transform:rotate\(-90deg\)/);
assert.match(v2Css, /transform-origin:left bottom/);
assert.match(v2Css, /box-shadow:-18px 12px 34px rgba\(0,0,0,.18\)/);
assert.match(v2Css, /box-shadow:-9px 8px 14px -11px rgba\(0,0,0,.34\)/);
assert.match(v2Css, /\.v2-z \.entity-card\{transform:translateY\(-2px\)/);
assert.match(v2Css, /\.v2-app\.is-revealing-deck \.v2-deck/);
assert.match(accountMobileCss, /\.app-shell\.app-shell--booking\{[\s\S]*?background:var\(--v2-base\)/);
assert.match(coreJs, /setThemeColor\('#2F3338'\)/);
assert.match(coreJs, /setThemeColor\('#F5F5F3'\)/);
assert.match(v2Css, /\.v2-z[\s\S]*?border-radius:var\(--v2-z-radius\) 0 0 0/);
assert.match(v2Css, /\.v2-layer--quick[\s\S]*?border-radius:0/);
assert.match(v2Css, /\.v2-layer--standard[\s\S]*?border-radius:0/);
assert.match(v2Css, /\.v2-layer--system[\s\S]*?border-radius:var\(--v2-z-radius\) 0 0 0/);
assert.match(v2Css, /\.v2-legal-cards\{display:grid;gap:12px\}/);
assert.match(v2Css, /\.v2-deck__card[\s\S]*?border-radius:0 var\(--v2-z-radius\) 0 0/);
assert.match(v2Css, /\.booking-account--account \.v2-app \.booking-time-grid\{grid-template-columns:repeat\(3,minmax\(0,1fr\)\)\}/);
assert.match(v2Css, /\.booking-account--account \.v2-app \.booking-time-slot\{border-radius:0/);
assert.match(indexHtml, /ui\/v2\/v2\.css/);
assert.match(styleCss, /--app-max-width:390px/);
assert.doesNotMatch(accountMobileCss, /--app-max-width:/);
assert.match(accountMobileCss, /\.app-shell\.app-shell--booking\s*\{[\s\S]*?width:min\(100%,var\(--app-max-width\)\);[\s\S]*?max-width:var\(--app-max-width\);/);
assert.match(shellUi, /messageThread/);
assert.match(shellUi, /attachmentTrigger = 'composer'/);
assert.match(shellCss, /\.message-composer\{position:fixed/);

assert.match(bookingUi, /Утро/);
assert.match(bookingUi, /День/);
assert.match(bookingUi, /Вечер/);

console.log('booking account UI tests passed');
