import assert from 'node:assert/strict';
import fs from 'node:fs';

const booking = fs.readFileSync('online-booking/booking.js', 'utf8');
const accountShell = fs.readFileSync('online-booking/account-shell.js', 'utf8');
const personalData = fs.readFileSync('online-booking/personal-data.js', 'utf8');
const passwordSettings = fs.readFileSync('online-booking/password-settings.js', 'utf8');
const bookingAccountApi = fs.readFileSync('core/booking-account/index.js', 'utf8');
const onlineBookingController = fs.readFileSync('server/src/online-booking/online-booking.controller.ts', 'utf8');
const accountSettingsController = fs.readFileSync('server/src/online-booking/booking-account-settings.controller.ts', 'utf8');
const onlineBookingService = fs.readFileSync('server/src/online-booking/online-booking.service.ts', 'utf8');
const consentPolicy = fs.readFileSync('server/src/document-state/consent-policy.service.ts', 'utf8');
const telegramBot = fs.readFileSync('server/src/communication/telegram-bot.service.ts', 'utf8');
const inputsUi = fs.readFileSync('ui/inputs/index.js', 'utf8');
const repeatedFields = fs.readFileSync('ui/repeated-fields/index.js', 'utf8');
const shellUi = fs.readFileSync('ui/shell/index.js', 'utf8');
const shellCss = fs.readFileSync('ui/shell/shell.css', 'utf8');
const clientMobileCss = fs.readFileSync('ui/shell/client-mobile.css', 'utf8');
const clientAccountThemeCss = fs.readFileSync('ui/shell/client-account-theme.css', 'utf8');
const indexHtml = fs.readFileSync('index.html', 'utf8');
const bookingUi = fs.readFileSync('ui/booking/index.js', 'utf8');

assert.match(booking, /renderClientAccount/);
assert.match(booking, /bookingChoiceCards\(/);
assert.match(booking, /bookingTimeGroups\(/);
assert.match(booking, /meta:\s*\[\s*\{ value: money\(subtotal\), label: 'Стоимость' \}/);
assert.match(booking, /onRepeat:/);
assert.doesNotMatch(booking, /−\$\{discount\}/);
assert.doesNotMatch(booking, /durationText\(duration\)/);

assert.match(accountShell, /entityCard\(\{/);
assert.match(accountShell, /className: 'entity-card--hero'/);
assert.match(accountShell, /image: profile\.photo \|\| ''/);
assert.doesNotMatch(accountShell, /clientProfileCard\(/);
assert.match(accountShell, /bookingThemeStyle\(state\.settings\)/);
assert.match(accountShell, /booking-client booking-client--account booking-shape--\$\{shape\}/);
assert.match(accountShell, /label: 'Стоимость'/);
assert.match(accountShell, /label: 'Скидка'/);
assert.match(accountShell, /label: 'Оплачено'/);
assert.match(accountShell, /const source = Array\.isArray\(account\.programs\) \? account\.programs : \[\]/);
assert.doesNotMatch(accountShell, /label: 'Депозит'/);
assert.doesNotMatch(accountShell, /label: 'Личный счёт'/);
assert.match(accountShell, /app-media-rail--placeholder/);
assert.match(accountShell, /openClientPersonalData/);
assert.match(accountShell, /openClientPasswordSettings/);
assert.match(accountShell, /label: 'Изменить пароль'/);
assert.match(accountShell, /listEntry\(\{\s*columns:/s);
assert.match(accountShell, /variant: 'large'/);
assert.match(accountShell, /readOnlyReceipt\(/);
assert.match(accountShell, /label: 'Повторить процедуру'/);
assert.match(accountShell, /action: \{ label: 'Записаться'/);
assert.match(accountShell, /messageComposer\(/);
assert.match(accountShell, /data-client-chat-settings/);
assert.match(accountShell, /getBookingChatSettings\(state\.tenantId\)/);
assert.match(accountShell, /setBookingTelegramConsent\(state\.tenantId, !telegram\.enabled\)/);
assert.match(accountShell, /label: 'Telegram'.*checked: Boolean\(telegram\.enabled\).*disabled: !telegram\.linked/s);
assert.doesNotMatch(accountShell, /Promise\.allSettled\(unread/);
assert.doesNotMatch(accountShell, /markBookingNotificationRead\(state\.tenantId, item\.notificationId\)/);
assert.match(accountShell, /markBookingNotificationRead\(state\.tenantId, message\.notificationId\)/);
assert.match(accountShell, /node\.addEventListener\('click', \(\) => void openNotification\(\)\)/);

assert.match(personalData, /photoField\(\{ name: 'photo'/);
assert.match(personalData, /addLabel: '\+ Телефон'/);
assert.match(personalData, /addLabel: '\+ Email'/);
assert.match(personalData, /showEmptyRow: false/);
assert.match(personalData, /label: 'Telegram'/);
assert.match(personalData, /\{ value: 'male', label: 'Мужской' \}/);
assert.match(personalData, /\{ value: 'female', label: 'Женский' \}/);
assert.doesNotMatch(personalData, /label: 'Другой'/);
assert.doesNotMatch(personalData, /type: 'date'/);
assert.match(personalData, /initCalendar\(calendarHost/);
assert.match(personalData, /links\(\{ links:/);
assert.match(personalData, /button\('Сохранить', \{ type: 'submit' \}\)/);
assert.match(personalData, /updateBookingAccount\(state\.tenantId/);
assert.match(personalData, /profileData:/);
assert.match(personalData, /phones: unique/);
assert.match(personalData, /emails: unique/);
assert.match(personalData, /telegram:/);
assert.match(personalData, /links: collectLinks/);

assert.match(repeatedFields, /showEmptyRow = true/);
assert.match(inputsUi, /phoneCountryLabel/);
assert.match(inputsUi, /full\.match\(\/\\\+\\d\{1,4\}\\b\/\)/);

assert.match(passwordSettings, /Текущий пароль/);
assert.match(passwordSettings, /Новый пароль/);
assert.match(passwordSettings, /Повторите новый пароль/);
assert.match(passwordSettings, /changeBookingPassword\(state\.tenantId/);
assert.match(passwordSettings, /newPassword !== repeatPassword/);
assert.match(bookingAccountApi, /account\/password/);
assert.match(accountSettingsController, /@Put\(':tenantId\/account\/password'\)/);
assert.match(accountSettingsController, /changeAccountPassword/);
assert.match(onlineBookingService, /async changeAccountPassword/);
assert.match(onlineBookingService, /compare\(current, account\.passwordHash\)/);
assert.match(onlineBookingService, /passwordHash: await hash\(next, 12\)/);
assert.match(onlineBookingService, /photo: text\(source\.photo\)/);
assert.match(onlineBookingService, /phones: uniqueStrings/);
assert.match(onlineBookingService, /emails: uniqueStrings/);
assert.match(onlineBookingService, /telegram: text\(source\.telegram\)/);
assert.match(onlineBookingService, /links,/);

assert.match(bookingAccountApi, /account\/chat\/settings/);
assert.match(bookingAccountApi, /account\/chat\/telegram-consent/);
assert.match(onlineBookingController, /contactPointConsentState\([\s\S]*?'TELEGRAM'[\s\S]*?identity\.externalUserId[\s\S]*?'messages-consent'/);
assert.match(onlineBookingController, /acceptContactPointConsent\([\s\S]*?'TELEGRAM'[\s\S]*?identity\.externalUserId[\s\S]*?'client-chat-settings'/);
assert.match(onlineBookingController, /revokeContactPointConsent\([\s\S]*?'TELEGRAM'[\s\S]*?identity\.externalUserId[\s\S]*?'client-chat-settings'/);
assert.match(consentPolicy, /async canSendMessages\(tenantId: string, typeValue: unknown, value: unknown\)/);
assert.match(telegramBot, /canSendMessages\(tenantId, 'TELEGRAM', identity\.externalUserId\)/);
assert.doesNotMatch(telegramBot, /canSendMessages\(tenantId, personKey/);

assert.match(shellUi, /appHeader/);
assert.match(shellUi, /clientBottomNavigation/);
assert.match(shellUi, /messageThread/);
assert.match(shellUi, /readOnlyReceipt/);
assert.match(shellCss, /grid-template-columns:var\(--shell-icon-slot\) minmax\(0,1fr\) var\(--shell-action-slot\) var\(--shell-icon-slot\)/);
assert.match(shellCss, /bottom-nav--client/);
assert.match(indexHtml, /ui\/shell\/client-mobile\.css/);
assert.match(indexHtml, /ui\/shell\/client-account-theme\.css/);
assert.match(clientMobileCss, /\.app-shell\.app-shell--booking\s*\{[\s\S]*?width:min\(100%,var\(--app-max-width\)\);[\s\S]*?max-width:var\(--app-max-width\);/);
assert.match(clientMobileCss, /\.app-shell\.app-shell--booking \.app-view-shell[\s\S]*?max-width:100%/);
assert.doesNotMatch(clientMobileCss, /max-width:none/);
assert.match(clientAccountThemeCss, /--text:var\(--booking-dark\)/);
assert.match(clientAccountThemeCss, /--button-secondary:var\(--booking-light\)/);
assert.match(clientAccountThemeCss, /\.app-view-shell--profile \.app-view-shell__screen\s*\{[\s\S]*?align-content:center;[\s\S]*?place-items:center;/);
assert.match(clientAccountThemeCss, /\.booking-client--account\.booking-shape--round/);
assert.match(clientAccountThemeCss, /\.booking-client--account\.booking-shape--straight/);
assert.match(clientAccountThemeCss, /\.booking-client--account\.booking-shape--cut/);
assert.match(bookingUi, /Утро/);
assert.match(bookingUi, /День/);
assert.match(bookingUi, /Вечер/);

console.log('booking client UI tests passed');
