import assert from 'node:assert/strict';
import fs from 'node:fs';

const booking = fs.readFileSync('online-booking/booking.js', 'utf8');
const accountShell = fs.readFileSync('online-booking/account-shell.js', 'utf8');
const personalData = fs.readFileSync('online-booking/personal-data.js', 'utf8');
const passwordSettings = fs.readFileSync('online-booking/password-settings.js', 'utf8');
const consentSettings = fs.readFileSync('online-booking/consent-settings.js', 'utf8');
const bookingSettingsUi = fs.readFileSync('settings/online-booking/online-booking.js', 'utf8');
const accountApi = fs.readFileSync('core/account/index.js', 'utf8');
const onlineBookingController = fs.readFileSync('server/src/online-booking/online-booking.controller.ts', 'utf8');
const accountSettingsController = fs.readFileSync('server/src/online-booking/account-settings.controller.ts', 'utf8');
const onlineBookingService = fs.readFileSync('server/src/online-booking/online-booking.service.ts', 'utf8');
const profileService = fs.readFileSync('server/src/profile/profile.service.ts', 'utf8');
const communicationService = fs.readFileSync('server/src/communication/communication.service.ts', 'utf8');
const communicationHistory = fs.readFileSync('server/src/communication/communication-history.service.ts', 'utf8');
const messageAttachmentMigration = fs.readFileSync('server/prisma/migrations/20260914010000_message_attachments/migration.sql', 'utf8');
const consentPolicy = fs.readFileSync('server/src/tenant-document-archive/consent-policy.service.ts', 'utf8');
const telegramBot = fs.readFileSync('server/src/communication/telegram-bot.service.ts', 'utf8');
const inputsUi = fs.readFileSync('ui/inputs/index.js', 'utf8');
const repeatedFields = fs.readFileSync('ui/repeated-fields/index.js', 'utf8');
const chatUi = fs.readFileSync('ui/chat/index.js', 'utf8');
const chatRuntime = fs.readFileSync('core/chat/runtime.js', 'utf8');
const chatCss = fs.readFileSync('ui/chat/chat.css', 'utf8');
const styleCss = fs.readFileSync('css/style.css', 'utf8');
const accountMobileCss = fs.readFileSync('ui/booking/account-mobile.css', 'utf8');
const accountThemeCss = fs.readFileSync('ui/booking/account-theme.css', 'utf8');
const bookingCss = fs.readFileSync('ui/booking/booking.css', 'utf8');
const indexHtml = fs.readFileSync('index.html', 'utf8');
const bookingUi = fs.readFileSync('ui/booking/index.js', 'utf8');
const v2Ui = fs.readFileSync('ui/v2/index.js', 'utf8');
const v2Css = fs.readFileSync('ui/v2/v2.css', 'utf8');
const sharedProfile = fs.readFileSync('ui/profile/index.js', 'utf8');
const calendarUi = fs.readFileSync('ui/calendar/calendar.js', 'utf8');
const coreJs = fs.readFileSync('core.js', 'utf8');
const buttonCss = fs.readFileSync('ui/buttons/buttons.css', 'utf8');
const segmentUi = fs.readFileSync('ui/selection/segment-control.js', 'utf8');
const segmentCss = fs.readFileSync('ui/selection/segment-control.css', 'utf8');
const entityCardCss = fs.readFileSync('ui/cards/entity-card.css', 'utf8');
const infoUi = fs.readFileSync('ui/info/index.js', 'utf8');
const infoCss = fs.readFileSync('ui/info/info.css', 'utf8');
const timeUi = fs.readFileSync('ui/time/index.js', 'utf8');
const timeCss = fs.readFileSync('ui/time/time.css', 'utf8');
const headerUi = fs.readFileSync('ui/header/index.js', 'utf8');
const journalListUi = fs.readFileSync('journal/список.js', 'utf8');
const recordRuntime = fs.readFileSync('ui/record/runtime.js', 'utf8');
const recordCss = fs.readFileSync('ui/record/record.css', 'utf8');

// Public booking selection comes first. UI Reference V2 is the end-user target.
assert.match(booking, /renderAccount/);
assert.match(booking, /v2Header\(\{/);
assert.match(booking, /v2Shell\(\{/);
assert.match(booking, /v2Sticker\(\{/);
assert.match(booking, /v2LegalCards\(/);
assert.match(booking, /recordWorkplaceCards\(/);
assert.match(booking, /recordProcedureList\(/);
assert.match(booking, /recordTimeRows\(/);
assert.match(booking, /recordConfirmationMiniCard\(/);
assert.doesNotMatch(booking, /bookingChoiceCards\(|bookingTimeGroups\(|v2ServiceStickers\(|v2-confirmation/);
assert.match(booking, /mountV2ZLayer\(root/);
assert.match(booking, /className: 'booking-step-z'/);
assert.match(booking, /stack: true/);
assert.match(booking, /initV2StickerSwipe\(/);
assert.match(booking, /function renderLegalSticker/);
assert.match(booking, /function renderAccountEntry/);
assert.match(booking, /function renderAccountDetails/);
assert.match(booking, /function renderWorkplaces/);
assert.match(booking, /function renderProcedures/);
assert.match(booking, /function renderDates/);
assert.match(booking, /function renderTimes/);
assert.match(booking, /function renderConfirmation/);
assert.match(booking, /step: 'workplaces'/);
assert.match(booking, /step: 'procedures'/);
assert.match(booking, /step: 'dates'/);
assert.match(booking, /step: 'times'/);
assert.match(booking, /step: 'confirmation'/);
assert.doesNotMatch(booking, /data-booking-workplaces-next/);
assert.match(booking, /data-booking-procedures-next/);
assert.doesNotMatch(booking, /data-booking-dates-next/);
assert.doesNotMatch(booking, /data-booking-times-next/);
assert.match(booking, /state\.workplaceKey = node\.dataset\.bookingWorkplace \|\| '';[\s\S]*?renderProcedures\(root, state\);/);
assert.match(booking, /onDateSelect: \(date\) => \{[\s\S]*?state\.date = date;[\s\S]*?renderTimes\(root, state\);/);
assert.match(booking, /node\.addEventListener\('click', \(\) => \{[\s\S]*?state\.from = slot\.from;[\s\S]*?renderConfirmation\(root, state\);/);
assert.doesNotMatch(booking, /data-booking-workplaces-back/);
assert.doesNotMatch(booking, /data-booking-dates-back/);
assert.doesNotMatch(booking, /data-booking-times-back/);
assert.doesNotMatch(booking, /data-booking-confirm-back/);
assert.match(booking, /label: 'Телефон или email'/);
assert.match(booking, /label: 'Пароль'/);
assert.match(booking, /data-booking-register/);
assert.match(booking, /data-booking-forgot/);
assert.match(booking, /label: 'Повтор пароля'/);
assert.match(booking, /prepareAccount\(state\.tenantId, \{ identifier \}\)/);
assert.match(booking, /prepareAccount\(state\.tenantId, \{ email, phone \}\)/);
assert.match(booking, /loginAccount\(state\.tenantId, identifier, password\)/);
assert.match(booking, /accountTerms: currentAccountTermsFact\(state\)/);
assert.match(booking, /saveTenantConsents\(state\)/);
assert.match(booking, /getAccountPlatformState/);
assert.match(booking, /getAccountConsentState/);
const globalAccountHomeBlock = booking.slice(
  booking.indexOf('async function renderGlobalClientHome'),
  booking.indexOf('async function continueGlobalIdentity'),
);
assert.doesNotMatch(globalAccountHomeBlock, /entry', 'account'/);
assert.doesNotMatch(globalAccountHomeBlock, /onOpenRelationship|onOpenRecord/);
assert.match(globalAccountHomeBlock, /onStartBooking: \(tenantId, options = \{\}\)/);
assert.match(booking, /slotStillAvailable/);
assert.match(booking, /Выбранное время уже недоступно/);
assert.doesNotMatch(booking, /consentState\.allowed/);
assert.match(booking, /const account = await getAccount\(state\.tenantId\);[\s\S]*?if \(account\) state\.account = account;[\s\S]*?renderWelcome\(root, state\);/);
assert.match(booking, /function backFromFirstBookingStep[\s\S]*?state\.bookingOrigin === 'profile'[\s\S]*?renderWelcome\(root, state\);/);
const bookingBackBlock = booking.slice(
  booking.indexOf('function backFromFirstBookingStep'),
  booking.indexOf('function renderWelcome'),
);
assert.doesNotMatch(bookingBackBlock, /renderAccountEntry\(root, state\);/);
assert.doesNotMatch(booking, /renderAccountHome\(/);
assert.doesNotMatch(booking, /import \{ renderAccount,/);
assert.match(booking, /exitBookingContext\(state, \{ tab: 'contact-detail', tenantId: state\.tenantId \}\)/);
assert.match(booking, /params\.set\('entry', 'account-booking'\)/, 'Known contact booking must skip the welcome screen');
assert.match(booking, /params\.set\('workplace', workplaceKey\)/, 'Workplace booking must preserve the selected workplace');
assert.match(booking, /params\.set\('procedures', procedureIds\.join\(','\)\)/, 'Repeat booking must preserve selected procedures');
assert.match(booking, /state\.entry === 'account-booking'/);
assert.match(booking, /data-booking-u-close[\s\S]*?state\.entry === 'account-booking'[\s\S]*?exitBookingContext\(state, \{ tab: 'contact-detail', tenantId: state\.tenantId \}\)/, 'Closing auth from Contacts booking must return to the professional profile, not welcome');
assert.match(booking, /state\.identityDestination === 'booking-start'[\s\S]*nextBookingStep\(root, state\)/);
assert.match(coreJs, /procedureIds:\s*String\(params\.get\('procedures'\)/);
assert.match(booking, /d:\s*null/);
const bookingHeaderStart = booking.indexOf('function bookingHeaderMarkup');
const bookingHeaderEnd = booking.indexOf('function bookingActionForStep', bookingHeaderStart);
const bookingHeader = booking.slice(bookingHeaderStart, bookingHeaderEnd);
assert.match(bookingHeader, /d:\s*null/);
assert.doesNotMatch(bookingHeader, /data-booking-flow-chat|kind:\s*'chat'/);

// End-user account is the first consumer of shared UI Reference V2.
assert.match(accountShell, /v2Header\(\{/);
assert.match(accountShell, /v2Shell\(\{/);
assert.match(accountShell, /v2CardDeck\(GLOBAL_ACCOUNT_ROOTS/);
assert.match(accountShell, /v2Section\(/);
assert.match(accountShell, /v2HorizontalRail\(/);
assert.match(accountShell, /entityVisualCard\(\{/);
assert.match(accountShell, /data-account-deck-item/);
assert.match(accountShell, /GLOBAL_ACCOUNT_ROOTS = Object\.freeze\(\[[\s\S]*?id: 'profile', label: 'Профиль'[\s\S]*?id: 'home', label: 'Обзор'[\s\S]*?id: 'contacts', label: 'Контакты'[\s\S]*?id: 'history', label: 'История'/);
assert.match(accountShell, /async function renderGlobalProfile\(/);
assert.match(accountShell, /async function renderGlobalProfileSettings\(/);
const endUserProfileCardBlock = accountShell.slice(
  accountShell.indexOf('function profileSummary'),
  accountShell.indexOf('function bindGlobalRelationships'),
);
assert.match(endUserProfileCardBlock, /entityVisualCard\(\{/);
assert.match(endUserProfileCardBlock, /data-account-profile-card/);
assert.match(endUserProfileCardBlock, /ACCOUNT_PROFILE_CARD_APPEARANCE/);
assert.match(endUserProfileCardBlock, /value:'name'/);
assert.match(endUserProfileCardBlock, /value:'phone'/);
assert.doesNotMatch(endUserProfileCardBlock, /entityCard\(\{/);
assert.doesNotMatch(endUserProfileCardBlock, /entity-card--hero|className\s*:\s*['\"][^'\"]*account-profile-card/);
assert.doesNotMatch(bookingCss, /booking-account--account \.entity-card--hero/);
assert.match(accountShell, /openSharedProfileSettingsMenu\(\{/);
assert.match(sharedProfile, /variant: 'bottom'/);
assert.doesNotMatch(accountShell, /openGlobalProfileSettingsZ|data-account-profile-settings-z/);
assert.match(accountShell, /openAccountPersonalDataZ\(root, state/);
assert.match(accountShell, /data-account-profile-save/);
assert.match(accountShell, /openSharedPhotoAction\(\{/);
assert.match(sharedProfile, /selectPhotoFile\(\)/);
assert.doesNotMatch(accountShell, /document\.createElement\('input'\)|new FileReader\(/);
assert.match(accountShell, /id:'controls',label:'Согласия \/ Уведомления'/);
assert.match(accountShell, /data-account-consent-contact/);
assert.match(accountShell, /async function openGlobalAccountControls\(root, state, handlers, relationships = state\.relationships\)/);
assert.match(accountShell, /const scopedRelationships = Array\.isArray\(relationships\)/);
assert.match(accountShell, /miniCardRail\(/);
assert.match(accountShell, /openAccountConsentSettings\(state, \{[\s\S]*?tenantId/);
assert.match(accountShell, /id:'delete',label:'Удалить профиль',variant:'critical'/);
assert.doesNotMatch(accountShell, /label: 'Личные данные', data: 'data-account-personal-data'/);
assert.match(accountShell, /async function renderGlobalContacts\(/);
assert.match(accountShell, /async function renderGlobalContactDetail\(/);
assert.match(accountShell, /state\.accountTab = 'contact-detail'/);
assert.match(accountShell, /async function renderGlobalHistoryDetail\(/);
assert.doesNotMatch(accountShell, /onOpenRelationship: callbacks\.onOpenRelationship/);
const relationshipCardBlock = accountShell.slice(
  accountShell.indexOf('function relationshipCard'),
  accountShell.indexOf('const ACCOUNT_PROFILE_CARD_APPEARANCE'),
);
assert.match(relationshipCardBlock, /profileCardAppearance\(profile\)/);
assert.match(relationshipCardBlock, /profileCardFields\(profile, \[\]\)/);
assert.doesNotMatch(relationshipCardBlock, /CONTACT_PROFILE_CARD_APPEARANCE|entity-card--compact|v2HorizontalRail|v2ListEntr/);

const contactsBlock = accountShell.slice(
  accountShell.indexOf('function relationshipSearchText'),
  accountShell.indexOf('function selectedGlobalRelationship'),
);
assert.match(contactsBlock, /entityCardStack\(filtered\.map\(relationshipCard\)\)/);
assert.match(contactsBlock, /const searchable = relationships\.length > 15/);
assert.match(contactsBlock, /data-account-contact-search/);
assert.match(contactsBlock, /data: 'data-account-profile-settings'/);
assert.doesNotMatch(contactsBlock, /disabled: true, aria: 'Настройки контактов'/);
assert.match(contactsBlock, /profile\.profession/);
assert.match(contactsBlock, /profile\.phone/);
assert.doesNotMatch(contactsBlock, /CONTACT_PROFILE_CARD_APPEARANCE|entity-card--compact|v2HorizontalRail\(filtered|v2ListEntr/);

const contactDetailBlock = accountShell.slice(
  accountShell.indexOf('function confirmDeleteGlobalContact'),
  accountShell.indexOf('async function renderGlobalHistory'),
);
assert.match(contactDetailBlock, /mountV2ZLayer\(root, v2ZLayer\([\s\S]*stack:\s*true/, 'Contact profile must open as stacked Z over Contacts Z1');
assert.match(contactDetailBlock, /v2Section\('Рабочие пространства'/);
assert.match(contactDetailBlock, /v2Section\('История'/);
assert.match(contactDetailBlock, /workplaceCardAppearance\(workplace\)/);
assert.match(contactDetailBlock, /workplaceCardFields\(workplace, workplace\.cardProfile \|\| profile\)/);
assert.match(contactDetailBlock, /miniCardRail\(/);
assert.match(contactDetailBlock, /label:\s*'Согласия \/ Уведомления'/);
assert.match(contactDetailBlock, /openGlobalAccountControls\(document\.body, state, handlers, \[relationship\]\)/, 'Contact controls must use the existing Shared notifications/consents owner scoped to that professional profile');
assert.match(contactDetailBlock, /label:\s*'Удалить',[\s\S]*variant:\s*'critical'/);
assert.match(contactDetailBlock, /button\('Удалить', \{ variant: 'danger'/);
assert.match(contactDetailBlock, /button\('Отмена', \{ variant: 'secondary'/);
assert.match(contactDetailBlock, /data-contact-delete-error/);
assert.match(contactDetailBlock, /deleteGlobalAccountRelationship\(tenantId\)/);
assert.match(contactDetailBlock, /label:\s*'Записаться'/);
assert.match(contactDetailBlock, /label:\s*'Повторить'/);

assert.match(profileService, /async accountRelationshipProfile\(tenantId: string\)[\s\S]*?phone: row\.phone/);
assert.doesNotMatch(profileService.slice(profileService.indexOf('async publicBookingBundle')), /profile:\s*\{[\s\S]*?phone: row\.phone/, 'Public booking profile must not expose the professional phone just for Contacts');
assert.match(onlineBookingService, /this\.profile\.accountRelationshipProfile\(link\.tenantId\)/);
assert.doesNotMatch(accountShell, /async function renderGlobalRepresentatives\(/);
assert.doesNotMatch(accountShell, /export async function renderAccount\(/);
assert.doesNotMatch(accountShell, /async function renderHome\(/);
assert.doesNotMatch(accountShell, /async function renderRepresentatives\(/);
assert.doesNotMatch(accountShell, /async function renderRepresentative\(/);
assert.doesNotMatch(accountShell, /async function renderHistory\(/);
assert.doesNotMatch(accountShell, /async function renderMessages\(/);
assert.doesNotMatch(accountShell, /label: 'Обзор'\s*\},\s*\{ id: 'history'/);
assert.match(accountShell, /async function renderGlobalHome\([\s\S]*?futureRequests\(state\.accountRecords \|\| \[\]\)/);
assert.match(accountShell, /async function renderGlobalContacts\([\s\S]*?const relationships = Array\.isArray\(state\.relationships\)/);
assert.match(accountShell, /async function renderGlobalHistory\([\s\S]*?state\.accountRecords/);
const globalHomeBlock = accountShell.slice(
  accountShell.indexOf('async function renderGlobalHome'),
  accountShell.indexOf('function contactsBody'),
);
assert.doesNotMatch(globalHomeBlock, /relationshipCard\(/);
assert.doesNotMatch(accountShell, /accountBottomNavigation/);
assert.doesNotMatch(accountShell, /bindBottomNavigation/);
assert.match(accountShell, /mountChatThread\(/);
assert.match(chatRuntime, /kind: 'contacts'/);
assert.match(accountShell, /mountChatList\(/);
assert.match(accountShell, /selected \? 'v2-app--chat' : 'v2-app--chat-list'/);
assert.match(accountShell, /sendAccountChatMessage\(selectedTenantId, body, attachments\)/);
assert.match(accountShell, /loadMessages\(state, selectedTenantId\)/);
assert.match(accountShell, /getAccountChatSettings\(state\.tenantId\)/);
assert.doesNotMatch(accountShell, /messageComposer\(|messageThread\(|bindMessageAttachments\(/);
assert.match(accountShell, /projectRecordStatuses/);
assert.match(accountShell, /booked: 'Записался'/);
assert.match(accountShell, /rescheduled: 'Перенёс'/);
assert.match(accountShell, /cancelled: 'Отменил'/);
assert.match(accountShell, /due: 'К оплате'/);
assert.match(accountShell, /paid: 'Оплачено'/);
assert.match(accountShell, /debt: 'Задолженность'/);
assert.match(accountShell, /openAccountPersonalData/);
assert.match(accountShell, /openAccountPasswordSettings/);
assert.match(accountShell, /openAccountConsentSettings/);
assert.match(accountShell, /mountModal\(document\.body, modal/);
assert.doesNotMatch(accountShell, /mountV2Layer\(|v2Layer\(/);
assert.match(accountShell, /async function renderGlobalHistoryDetail/);
assert.match(accountShell, /label: 'Записаться', data: 'data-global-history-repeat'/);
assert.match(accountShell, /state\.accountSelectedChatTenantId/);
const rootChatBlock = accountShell.slice(
  accountShell.indexOf('function bindGlobalChatButton'),
  accountShell.indexOf('function bindGlobalProfileSettingsEntry'),
);
assert.match(rootChatBlock, /state\.accountSelectedChatTenantId = '';/, 'Root Header D must always open the chat contact list');
assert.match(contactDetailBlock, /state\.accountSelectedChatTenantId = tenantId;/, 'Contact Header D must open chat with that professional profile');
assert.match(accountShell, /state\.accountDeckOpen = true/);
assert.doesNotMatch(accountShell, /requestMoment\(request\)\s*[<>]=?\s*nowMoment\(\)\s*\?\s*'Задолженность'/);
assert.doesNotMatch(accountShell, /bookingThemeStyle/);
assert.doesNotMatch(accountShell, /booking-shape--|booking-choice-style--/);
assert.doesNotMatch(accountShell, /accountThemeClasses/);
assert.match(accountShell, /if \(!canReuseScene\) \{/);
assert.match(accountShell, /root\.innerHTML = v2Shell\(\{/);
assert.match(accountShell, /if \(z\) z\.innerHTML = body;/);

// Personal data is a stacked Z editor. Photo is owned separately by Profile settings.
assert.match(personalData, /openAccountPersonalDataZ\(root, state/);
assert.match(personalData, /mountV2ZLayer\(root, v2ZLayer/);
assert.match(personalData, /v2Section\('Личные данные', fields\)/);
assert.doesNotMatch(personalData, /accordion\(|initAccordions/);
assert.doesNotMatch(personalData, /photoField\(/);
assert.doesNotMatch(personalData, /name: 'photo'/);
assert.match(personalData, /addLabel: '\+ Телефон'/);
assert.match(personalData, /addLabel: '\+ Email'/);
assert.match(personalData, /showEmptyRow: false/);
assert.match(personalData, /label: 'Telegram'/);
assert.match(personalData, /\{ value: 'male', label: 'Мужской' \}/);
assert.match(personalData, /\{ value: 'female', label: 'Женский' \}/);
assert.doesNotMatch(personalData, /label: 'Другой'/);
assert.doesNotMatch(personalData, /type: 'date'/);
assert.match(personalData, /datePicker\(\{label:'Дата рождения'/);
assert.match(personalData, /initDatePickers\(layer\)/);
assert.doesNotMatch(personalData, /birthDateField|openBirthDatePicker|data-account-birth-|ui-select__control|initCalendar\(calendarHost|mountModal\(|modal\(/);
assert.match(calendarUi, /export function datePicker\(/);
assert.match(calendarUi, /export function initDatePickers\(/);
assert.match(calendarUi, /initCalendar\(calendarHost/);
assert.match(calendarUi, /select\(\{/);
assert.match(calendarUi, /mountModal\(document\.body, modal/);
assert.match(personalData, /links\(\{ label:'Ссылки'/);
assert.doesNotMatch(personalData, /<div class="array-group"><span class="array-label">Ссылки/);
assert.doesNotMatch(personalData, /button\('Сохранить', \{ type: 'submit' \}\)/);
assert.match(personalData, /layer\.v2Submit = \(\) => form\?\.requestSubmit\(\)/);
assert.match(personalData, /formSignature\(form\)!==|formSignature\(form\) !== initialSignature/);
assert.match(personalData, /updateAccount\(state\.tenantId/);
assert.match(personalData, /profileData:/);
assert.match(personalData, /phones: unique/);
assert.match(personalData, /emails: unique/);
assert.match(personalData, /telegram:/);
assert.match(personalData, /links: collectLinks/);

assert.match(repeatedFields, /showEmptyRow = true/);
assert.match(inputsUi, /phoneCountryLabel/);
assert.match(inputsUi, /full\.match\(\/\\\+\\d\{1,4\}\\b\/\)/);

// Password and consent account settings are functional server-backed controls.
assert.match(passwordSettings, /openSharedPasswordAction/);
assert.match(passwordSettings, /changeAccountPassword\(state\.tenantId/);
assert.match(sharedProfile, /Текущий пароль/);
assert.match(sharedProfile, /Новый пароль/);
assert.match(sharedProfile, /Повторите новый пароль/);
assert.match(sharedProfile, /newPassword !== repeatPassword/);
assert.match(consentSettings, /getAccountConsentState\(scopeTenantId\)/);
assert.match(consentSettings, /revokeAccountConsent\(scopeTenantId, consent\.documentId\)/);
assert.match(consentSettings, /Отозвать согласие/);
assert.match(consentSettings, /Отмена/);
assert.match(consentSettings, /variant: 'bottom'/);
assert.match(consentSettings, /v2LegalCards\(/);
assert.match(consentSettings, /openSharedConsentDocument\(/);
assert.match(sharedProfile, /variant: 'technical'/);
assert.match(sharedProfile, /v2Document\(/);
assert.match(consentSettings, /submitAccountConsents\(scopeTenantId/);
assert.match(accountApi, /account\/password/);
assert.match(accountApi, /deleteGlobalAccount/);
assert.match(accountApi, /method: 'DELETE'/);
assert.match(accountSettingsController, /@Put\(':tenantId\/account\/password'\)/);
assert.match(accountSettingsController, /changeAccountPassword/);
assert.match(onlineBookingService, /async changeAccountPassword/);
assert.match(onlineBookingService, /async deleteGlobalAccount/);
assert.match(onlineBookingService, /revokeAllForAccount/);
assert.match(onlineBookingService, /accountContact\.deleteMany|accountContact\.deleteMany/);
assert.match(onlineBookingController, /@Delete\('account\/me'\)/);
const publicAccountBlock = onlineBookingService.slice(
  onlineBookingService.indexOf('function publicAccount('),
  onlineBookingService.indexOf('@Injectable()'),
);
assert.doesNotMatch(publicAccountBlock, /\buei\s*:/, 'Public Account projection must not expose internal UEI');
assert.match(onlineBookingService, /async accountTenantContactContext\(/);
assert.match(onlineBookingService, /compare\(current, account\.passwordHash\)/);
assert.match(onlineBookingService, /passwordHash: await hash\(next, 12\)/);
assert.match(onlineBookingService, /photo: text\(source\.photo\)/);
assert.match(onlineBookingService, /phones: uniqueStrings/);
assert.match(onlineBookingService, /emails: uniqueStrings/);
assert.match(onlineBookingService, /telegram: text\(source\.telegram\)/);
assert.match(onlineBookingService, /links,/);

// Online booking settings stay inside the single Shared workspace Z; return navigation is gesture-owned.
assert.match(bookingSettingsUi, /workspaceHeaderContext\(\{/);
assert.doesNotMatch(bookingSettingsUi, /data-online-booking-back/);
assert.match(bookingSettingsUi, /data-v2-primary-action/);
assert.match(bookingSettingsUi, /data-v2-primary-visible="false"/);
assert.doesNotMatch(bookingSettingsUi, /\bappShell\s*\(/);
assert.doesNotMatch(bookingSettingsUi, /\bappHeader\s*\(/);
assert.doesNotMatch(bookingSettingsUi, /app-content--book-shell/);
assert.doesNotMatch(headerUi, /data-workspace-back-source/);
assert.match(headerUi, /actionData/);
assert.match(bookingSettingsUi, /folderList\(\[/);
assert.match(bookingSettingsUi, /Приветствие/);
assert.match(bookingSettingsUi, /Внешний вид/);
assert.match(bookingSettingsUi, /Время записи/);
assert.match(bookingSettingsUi, /function renderWelcome/);
assert.match(bookingSettingsUi, /function renderAppearance/);
assert.match(bookingSettingsUi, /function renderTime/);
assert.match(bookingSettingsUi, /setSaveVisible\(root, false\)/);
assert.match(bookingSettingsUi, /form\.addEventListener\('input', updatePreview\)/);
assert.match(bookingSettingsUi, /form\.addEventListener\('change', updatePreview\)/);
assert.match(bookingSettingsUi, /twoColumnLayout\(/);
assert.match(bookingSettingsUi, /label: 'Отменить'/);
assert.match(bookingSettingsUi, /label: 'Сбросить'/);
assert.match(bookingSettingsUi, /variant: 'outline'/);
assert.match(bookingSettingsUi, /saveBookingSettings\(settingsDraft\(form, saved\)\)/);
assert.match(bookingSettingsUi, /BOOKING_SLOT_STEPS\.map/);
assert.doesNotMatch(bookingSettingsUi, /Сохранить оформление/);
assert.match(indexHtml, /settings\/online-booking\/online-booking\.css/);

// Mini App owns legal consent management; Chat settings must not mutate advertising consent.
assert.match(accountApi, /account\/consents/);
assert.match(accountApi, /account\/consents\/\$\{encodeURIComponent\(documentId\)\}\/revoke/);
assert.match(accountApi, /account\/chat\/settings/);
assert.doesNotMatch(accountApi, /account\/chat\/telegram-consent/);
assert.doesNotMatch(accountApi, /setBookingTelegramConsent/);
assert.doesNotMatch(onlineBookingController, /messages-consent/);
assert.doesNotMatch(onlineBookingController, /telegram-consent/);
assert.doesNotMatch(consentPolicy, /async canSendMessages\(/);
assert.match(consentPolicy, /async canSendMarketing\(/);
assert.match(telegramBot, /purpose === 'MARKETING'[\s\S]*canSendMarketing\(tenantId, 'TELEGRAM', identity\.externalUserId\)/);

// Media is a real persisted message property, not a decorative paperclip.
assert.match(accountApi, /sendAccountChatMessage\(tenantId, body, attachments = \[\]\)/);
assert.match(onlineBookingController, /@Body\(\) body: \{ body\?: unknown; attachments\?: unknown \}/);
assert.match(onlineBookingController, /attachments,/);
assert.match(communicationService, /function normalizeAttachments/);
assert.match(communicationService, /"attachments"/);
assert.match(communicationService, /\$\{attachmentsJson\}::jsonb/);
assert.match(communicationHistory, /m\."attachments"/);
assert.match(communicationHistory, /'\[\]'::jsonb AS "attachments"/);
assert.match(messageAttachmentMigration, /ADD COLUMN "attachments" JSONB NOT NULL DEFAULT '\[\]'::jsonb/);

// Shared V2 owns one persistent geometry-driven FEZ CardDeck for both contours.
assert.match(v2Ui, /export function v2Header/);
assert.match(v2Ui, /export function v2Shell/);
assert.match(v2Ui, /export function v2CardDeck/);
assert.doesNotMatch(v2Ui, /export function v2EList|export function v2FDeck/);
assert.match(v2Ui, /export function v2Layer/);
assert.match(v2Ui, /export function initV2Swipe/);
assert.match(v2Ui, /export function initV2WorkspaceInteraction/);
assert.match(v2Ui, /data-v2-card-deck/);
assert.match(v2Ui, /data-v2-deck-axis="\$\{resolvedAxis\}"/);
assert.match(v2Ui, /data-v2-deck-level="\$\{text\(level\)\}"/);
assert.match(v2Ui, /data-v2-card-item="\$\{text\(id\)\}"/);
assert.match(v2Ui, /data-v2-card-index="\$\{index\}"/);
assert.doesNotMatch(v2Ui, /data-v2-f-index|data-v2-e-index|data-v2-e-step|--v2-e-active-offset/);

assert.match(v2Ui, /const updateDeckGeometry = \(deck, cards, axis\) =>/);
assert.match(v2Ui, /card\.offsetLeft/);
assert.match(v2Ui, /deck\.scrollLeft/);
assert.match(v2Ui, /card\.offsetTop/);
assert.match(v2Ui, /deck\.scrollTop/);
assert.match(v2Ui, /--v2-card-depth/);
assert.match(v2Ui, /--v2-card-rotation/);
assert.match(v2Ui, /--v2-card-scale/);
assert.match(v2Ui, /--v2-card-opacity/);
assert.match(v2Ui, /--v2-card-brightness/);
assert.match(v2Ui, /--v2-card-stack/);
assert.match(v2Ui, /deck\.addEventListener\('scroll', refresh, \{ passive: true \}\)/);
assert.match(v2Ui, /deck\.addEventListener\('scroll', settle, \{ passive: true \}\)/);
assert.match(v2Ui, /Math\.hypot\(dx, dy\) >= 9/);
assert.match(v2Ui, /suppressClick = pointer\.dragged/);
assert.match(v2Ui, /setActiveIndex\(index\)/);
assert.match(v2Ui, /setActiveCard\(cards, index\)/);
assert.doesNotMatch(v2Ui, /if \(index !== activeIndex\)/);
assert.doesNotMatch(v2Ui, /const projected = current\.dx \+ velocity|const projected = current\.dy \+ velocity|deck\.scrollLeft = clampScroll/);

assert.match(v2Ui, /const eDown = \(event\) =>/);
assert.match(v2Ui, /Math\.abs\(dy\) >= Math\.abs\(dx\) \* 1\.05 \|\| dx <= 0/);
assert.match(v2Ui, /--v2-e-dismiss-x/);
assert.doesNotMatch(v2Ui, /--v2-e-drag-x|--v2-e-drag-y/);

assert.match(v2Ui, /if \(Number\(event\.clientX \|\| 0\) > rect\.left \+ edgeWidth\) return/);
assert.match(v2Ui, /const edgeHost = onRight \? app\?\.querySelector\?\.\('\[data-v2-edge-swipe\]'\) : null/);
assert.match(v2Ui, /const gestureHost = edgeHost \|\| stage \|\| surface/);
assert.match(v2Ui, /const leftEdge = Number\(stageRect\?\.left \|\| 0\) \+ Number\(edgeWidth \|\| 36\)/);
assert.match(v2Ui, /const wantsRight = Boolean\(onRight\)/);
assert.match(v2Ui, /const dragSurface = isBaseZ && front \? front : surface/);
assert.match(v2Ui, /const dragProperty = isBaseZ && front \? '--v2-front-drag-x' : '--v2-drag-x'/);
assert.doesNotMatch(v2Ui, /inNavigationGutter|horizontalGestureContext|forceNavigation|nestedHorizontalScroller/);
assert.match(v2Ui, /disposeSwipe = initV2Swipe\(node, \{ onRight: close, revealDeck: false, threshold: 28, edgeWidth: 36 \}\)/);

assert.match(v2Css, /\.v2-card-deck\{[\s\S]*?--v2-card-width:min\(68vw,258px\);[\s\S]*?--v2-card-height:min\(47vh,344px\)/);
assert.match(v2Css, /\.v2-card-deck--x\{[\s\S]*?overflow-x:auto;overflow-y:hidden[\s\S]*?scroll-snap-type:x mandatory[\s\S]*?touch-action:pan-x/);
assert.match(v2Css, /\.v2-card-deck--y\{[\s\S]*?overflow-x:hidden;overflow-y:auto[\s\S]*?scroll-snap-type:y mandatory[\s\S]*?touch-action:pan-y/);
assert.match(v2Css, /\.v2-z\{[\s\S]*?touch-action:auto/);
assert.match(v2Css, /\.v2-edge-swipe-zone\{[\s\S]*?width:36px;[\s\S]*?pointer-events:none;[\s\S]*?touch-action:none/);
assert.match(v2Css, /\.v2-edge-swipe-zone\.is-active\{pointer-events:auto\}/);
assert.match(v2Ui, /function retainV2EdgeHost\(host\)/);
assert.match(v2Ui, /host\.dataset\.v2EdgeOwners/);
assert.doesNotMatch(v2Css, /scroll-snap-stop:always/);
assert.match(v2Css, /\.v2-card-deck__card\{[\s\S]*?width:var\(--v2-card-width\);height:var\(--v2-card-height\)/);
assert.match(v2Css, /rotateY\(var\(--v2-card-rotation\)\)/);
assert.match(v2Css, /rotateX\(var\(--v2-card-rotation\)\)/);
assert.match(v2Css, /translate3d\(var\(--v2-card-shift\),0,var\(--v2-card-depth\)\)/);
assert.match(v2Css, /translate3d\(0,var\(--v2-card-shift\),var\(--v2-card-depth\)\)/);
assert.match(v2Css, /\.v2-card-deck__card\.is-active\{[\s\S]*?border:2px solid var\(--v2-yellow\)/);
assert.match(v2Css, /\.v2-app\.is-e-open \.v2-card-deck--x\{[\s\S]*?translateZ\(-150px\) scale\(\.86\)[\s\S]*?pointer-events:none/);
assert.match(v2Css, /\.v2-app\.is-e-open \.v2-card-deck--y\{opacity:1;pointer-events:auto\}/);
assert.doesNotMatch(v2Css, /\.v2-e-card\{|\.v2-deck__card\{|--v2-e-card-width|--v2-e-card-height|\.v2-card-deck__card:nth-child/);

assert.match(v2Css, /\.v2-app\.is-deck-open > \.v2-app__stage > \.v2-front\{transform:translate3d\(100%,0,0\)\}/);
assert.match(v2Ui, /if \(next\) app\.classList\.remove\('is-z-entering'\)/);
assert.match(v2Css, /\.v2-app\.is-z-entering > \.v2-app__stage > \.v2-front\{animation:v2-z-enter-from-right \.30s cubic-bezier\(\.16,1,\.3,1\)\}/);
assert.doesNotMatch(v2Css, /v2-z-enter-from-right \.30s cubic-bezier\(\.16,1,\.3,1\) (?:both|forwards)/);
assert.match(v2Css, /\.v2-z[\s\S]*?border-radius:var\(--v2-z-radius\) 0 0 0/);

assert.match(coreJs, /v2CardDeck\(rootItems, \{/);
assert.match(coreJs, /axis: 'x'/);
assert.match(coreJs, /v2CardDeck\(childItems, \{/);
assert.match(coreJs, /axis: 'y'/);
assert.match(coreJs, /level: 'e'/);
assert.match(coreJs, /let shell = app\.querySelector\(':scope > \[data-v2-app\]\.v2-app--workspace'\)/);
assert.match(coreJs, /if \(!shell\) \{/);
assert.match(coreJs, /persistentSurface\?\.replaceChildren\(\)/);
assert.match(accountShell, /const canReuseScene = Boolean\(deck && shell\?\.querySelector/);
assert.match(accountShell, /if \(!canReuseScene\) \{/);
assert.match(accountShell, /if \(z\) z\.innerHTML = body/);
assert.match(accountShell, /root\.v2WorkspaceInteractionDispose\?\.\(\)/);
assert.match(accountShell, /root\.v2WorkspaceInteractionDispose = dispose/);
assert.match(v2Ui, /node\.v2Dispose = dispose/);
const stickerSwipeSource = v2Ui.slice(v2Ui.indexOf('export function initV2StickerSwipe'));
assert.match(stickerSwipeSource, /surface\.setPointerCapture\?\.\(event\.pointerId\)/);
assert.doesNotMatch(stickerSwipeSource, /gestureHost\.setPointerCapture/);

assert.match(coreJs, /navigationLevel: 'f'/);
assert.match(coreJs, /state\.navigationLevel = hasE \? 'e' : 'f'/);
assert.match(accountShell, /initV2WorkspaceInteraction\(root/);
assert.match(accountShell, /state\.accountDeckOpen = false/);
const globalProfileBlock = accountShell.slice(accountShell.indexOf('async function renderGlobalProfile('), accountShell.indexOf('async function renderGlobalProfileSettings('));
const globalHomeFezBlock = accountShell.slice(accountShell.indexOf('async function renderGlobalHome('), accountShell.indexOf('function relationshipSearchText('));
const globalContactsBlock = accountShell.slice(accountShell.indexOf('async function renderGlobalContacts('), accountShell.indexOf('function selectedGlobalRelationship('));
const globalHistoryBlock = accountShell.slice(accountShell.indexOf('async function renderGlobalHistory('), accountShell.indexOf('async function renderGlobalHistoryDetail('));
assert.match(globalProfileBlock, /bindWorkspaceInteraction\(root, state, handlers\)/);
assert.match(globalHomeFezBlock, /bindWorkspaceInteraction\(root, state, handlers\)/);
assert.match(globalContactsBlock, /bindWorkspaceInteraction\(root, state, handlers\)/);
assert.match(globalHistoryBlock, /bindWorkspaceInteraction\(root, state, handlers\)/);
const contactDetailBlock2 = accountShell.slice(accountShell.indexOf('async function renderGlobalContactDetail('), accountShell.indexOf('async function renderGlobalHistory('));
assert.match(contactDetailBlock2, /await renderGlobalContacts\(root, state, handlers\)/);
assert.match(contactDetailBlock2, /mountV2ZLayer\(root, v2ZLayer/);
const historyDetailBlock2 = accountShell.slice(accountShell.indexOf('async function renderGlobalHistoryDetail('), accountShell.indexOf('export async function renderGlobalAccount('));
assert.match(historyDetailBlock2, /bindWorkspaceInteraction\(root, state, handlers, \{/);
assert.match(historyDetailBlock2, /onZRight:/);
const messagesBlock2 = accountShell.slice(accountShell.indexOf('async function renderGlobalMessages('), accountShell.indexOf('async function renderGlobalProfile('));
assert.match(messagesBlock2, /initV2Swipe\(root, \{/);
assert.match(messagesBlock2, /state\.accountDeckOpen = true/);

assert.match(accountMobileCss, /\.app-shell\.app-shell--booking\{[\s\S]*?background:var\(--v2-base\)/);
assert.match(coreJs, /setThemeColor\('#2F3338'\)/);
assert.match(coreJs, /setThemeColor\('#F5F5F3'\)/);
assert.match(v2Css, /\.v2-z[\s\S]*?border-radius:var\(--v2-z-radius\) 0 0 0/);
assert.match(v2Css, /\.v2-app__stage\{[\s\S]*?height:calc\(var\(--visual-vh,100dvh\) - 72px\)/);
assert.match(v2Css, /\.v2-front\{[\s\S]*?height:calc\(var\(--visual-vh,100dvh\) - 72px\)/);
assert.match(v2Css, /\.v2-z\{[\s\S]*?box-sizing:border-box;[\s\S]*?height:calc\(var\(--visual-vh,100dvh\) - 72px\);[\s\S]*?overflow-y:auto/);
assert.match(v2Css, /\.v2-header__slot--a \.v2-header__control\{[\s\S]*?border:2px solid var\(--v2-yellow\)/);
assert.match(v2Css, /\.v2-header__slot--c \.v2-header__control--white\{border-color:#111;background:#fff;color:#111\}/);
assert.match(v2Ui, /slot\.variant === 'white' \|\| slot\.variant === 'secondary'/);
assert.match(v2Ui, /mountV2ModalPortal\(host\)/);
assert.match(v2Ui, /document\.body\.appendChild\(portal\)/);
assert.match(v2Ui, /v2ModalPortalGeometry\(host\.getBoundingClientRect\(\), currentVisualViewport\(\)\)/);
assert.match(v2Css, /\.v2-layer-portal--viewport\{position:fixed/);
assert.match(v2Css, /\.v2-layer-portal>\.v2-layer-backdrop--contained\{position:absolute;inset:0/);
assert.doesNotMatch(v2Css, /\.v2-z:not\(\.v2-z--layer\)\.has-v2-layer\{transform:translateZ\(0\)/);
assert.match(coreJs, /if \(target\.closest\('\[data-v2-layer\]'\)\) return;/);
assert.match(v2Css, /\.v2-layer--top[\s\S]*?border-radius:var\(--v2-z-radius\) 0 0 0/);
assert.match(v2Css, /\.v2-layer--standard[\s\S]*?inset:0;[\s\S]*?border-radius:var\(--v2-z-radius\) 0 0 0/);
assert.match(v2Css, /\.v2-layer--bottom[\s\S]*?bottom:0;[\s\S]*?border-radius:0/);
assert.match(v2Css, /\.v2-layer--technical[\s\S]*?border-radius:0;[\s\S]*?box-shadow:0 18px 46px/);
assert.match(v2Css, /\.v2-legal-cards\{display:flex;gap:10px;overflow-x:auto/);
assert.match(recordRuntime, /export function recordTimeRows/);
assert.match(recordRuntime, /timeSlots\(/);
assert.match(timeCss, /\.time-slots--hour-rows\{display:flex/);
assert.match(timeCss, /overflow-x:auto/);
assert.match(timeCss, /calc\(\(100% - 16px\)\/3\)/);
assert.match(timeCss, /border-radius:0/);
assert.match(timeCss, /box-shadow:0 4px 10px/);
assert.match(timeCss, /\.time-slot\.is-emphasized\{font-weight:800\}/);
assert.match(indexHtml, /ui\/v2\/v2\.css/);
assert.match(indexHtml, /ui\/selection\/segment-control\.css/);
assert.match(indexHtml, /ui\/info\/info\.css/);
assert.match(buttonCss, /\.ui-button\{[\s\S]*?border:1px solid var\(--white\);[\s\S]*?border-radius:14px[\s\S]*?background:var\(--text\);color:var\(--white\)/);
assert.match(buttonCss, /\.ui-button--secondary,\.ui-button--outline\{border-color:var\(--text\);background:var\(--white\);color:var\(--text\)\}/);
assert.match(buttonCss, /\.ui-button:disabled\{/);
assert.match(segmentUi, /filter\(Boolean\)\.map/);
assert.doesNotMatch(segmentUi, /\.slice\(0, 3\)/);
assert.match(segmentCss, /\.segment-control\{[\s\S]*?display:inline-flex;[\s\S]*?width:max-content;[\s\S]*?border:1px solid var\(--text\);[\s\S]*?border-radius:10px;[\s\S]*?background:var\(--white\)/);
assert.match(segmentCss, /\.segment-control button\{[\s\S]*?min-height:30px;[\s\S]*?padding:0 8px/);
assert.match(segmentCss, /\.segment-control button\.is-active\{[\s\S]*?background:var\(--text\);[\s\S]*?color:var\(--white\)/);
assert.match(entityCardCss, /--entity-card-depth:#2C2A28/);
assert.match(entityCardCss, /--entity-card-mid:#817A73/);
assert.match(entityCardCss, /--entity-card-light:#D7D1CA/);
assert.doesNotMatch(entityCardCss, /--entity-card-neutral|var\(--v2-disabled\)|var\(--button-secondary\)/);
assert.match(entityCardCss, /\.entity-card\.has-image \.entity-card__background/);
assert.match(infoUi, /export function infoUI/);
assert.match(infoUi, /export function initInfoUI/);
assert.match(infoCss, /\.ui-info__trigger\{[\s\S]*?border:1px solid #111;[\s\S]*?border-radius:0/);
assert.match(infoCss, /\.ui-info--inverse/);
assert.match(timeUi, /variant:'bottom'/);
assert.match(timeUi, /className:'modal--time-picker-sheet'/);
assert.doesNotMatch(timeUi, /variant:'top'/);
assert.match(styleCss, /--app-max-width:390px/);
assert.doesNotMatch(accountMobileCss, /--app-max-width:/);
assert.match(accountMobileCss, /\.app-shell\.app-shell--booking\s*\{[\s\S]*?width:min\(100%,var\(--app-max-width\)\);[\s\S]*?max-width:var\(--app-max-width\);/);
assert.match(chatUi, /messageThread/);
assert.match(chatUi, /attachmentTrigger = 'composer'/);
assert.match(chatCss, /\.message-composer\{position:fixed/);
assert.equal(fs.existsSync('ui/shell/index.js'), false);
assert.equal(fs.existsSync('ui/shell/shell.css'), false);

assert.doesNotMatch(journalListUi, /getBoundingPersonRect/);
assert.match(journalListUi, /getBoundingClientRect\(\)/);

assert.doesNotMatch(bookingUi, /bookingChoiceCards|bookingTimeGroups|v2ServiceStickers|v2-confirmation/);
assert.match(booking, /workplaceCardAppearance\(workplace\)/);
assert.match(booking, /workplaceCardFields\(workplace, workplace\.cardProfile \|\| profile\)/);
assert.match(recordRuntime, /entityVisualCard\(/);
assert.match(recordRuntime, /v2ListEntry\(/);
assert.match(recordRuntime, /v2ListEntries\(/);
assert.match(recordRuntime, /miniCard\(/);
assert.match(recordRuntime, /className: 'record-confirmation-mini-card'/);
assert.doesNotMatch(recordRuntime, /record-confirmation-card__|record-confirmation-view__metrics|v2RailCard\(/);
assert.match(recordRuntime, /timeSlots\(/);

console.log('booking account UI tests passed');
