import assert from 'node:assert/strict';
import fs from 'node:fs';

const communication = fs.readFileSync('server/src/communication/communication.service.ts', 'utf8');
const dispatch = fs.readFileSync('server/src/communication/communication-dispatch.service.ts', 'utf8');
const controller = fs.readFileSync('server/src/communication/communication.controller.ts', 'utf8');
const emailChannel = fs.readFileSync('server/src/communication/email-channel.service.ts', 'utf8');
const professionalEmail = fs.readFileSync('server/src/communication/professional-email.service.ts', 'utf8');
const telegramBot = fs.readFileSync('server/src/communication/telegram-bot.service.ts', 'utf8');
const notification = fs.readFileSync('server/src/notification/notification.service.ts', 'utf8');
const broadcast = fs.readFileSync('server/src/communication/communication-broadcast.service.ts', 'utf8');
const compose = fs.readFileSync('chat/chat.js', 'utf8');
const coreChat = fs.readFileSync('core/communications/chat.js', 'utf8');
const chatRuntime = fs.readFileSync('core/chat/runtime.js', 'utf8');
const sharedChat = fs.readFileSync('ui/chat/index.js', 'utf8');
const transactional = fs.readFileSync('server/src/transactional-email/transactional-email.service.ts', 'utf8');
const envExample = fs.readFileSync('server/.env.example', 'utf8');

assert.match(communication, /async emailIdentity\(/);
assert.match(communication, /person\.emails/);
assert.match(communication, /AND "channel" = 'IN_APP'/);
assert.match(dispatch, /async availableChannels\(/);
assert.doesNotMatch(dispatch, /private async availableChannels\(/);
assert.match(dispatch, /const channels: string\[\] = \['PUSH'\]/);
assert.match(dispatch, /telegramIdentity/);
assert.match(dispatch, /channels\.push\('TELEGRAM'\)/);
assert.match(dispatch, /channels\.push\('EMAIL'\)/);
assert.match(dispatch, /email\.isAvailable\(tenantId\)/);
assert.match(dispatch, /channel === 'PUSH'/);
assert.match(dispatch, /channel: 'IN_APP'/);
assert.match(dispatch, /Вложения можно отправить только через Push/);
assert.match(dispatch, /channel === 'EMAIL'/);
assert.match(dispatch, /email\.sendMessage/);
assert.doesNotMatch(dispatch, /hasActivePdnConsent/);
assert.match(controller, /@Get\('chat\/channels'\)/);
assert.match(controller, /dispatch\.availableChannels/);
assert.match(coreChat, /getCommunicationChannels/);
assert.match(coreChat, /communications\/chat\/channels/);

assert.match(emailChannel, /ProfessionalEmailService/);
assert.doesNotMatch(emailChannel, /TransactionalEmailService/);
assert.doesNotMatch(emailChannel, /hasActivePdnConsentForContact\(tenantId, 'EMAIL'/);
assert.match(emailChannel, /purpose === 'MARKETING'/);
assert.match(emailChannel, /canSendMarketing\(tenantId, 'EMAIL'/);
assert.match(emailChannel, /pendingEmailDeliveries/);
assert.match(emailChannel, /markEmailSent/);
assert.match(emailChannel, /markEmailFailed/);
assert.match(emailChannel, /recordMessage[\s\S]*channel: 'EMAIL'/);
assert.match(emailChannel, /private dispatchPendingInBackground\(\)/);
assert.match(emailChannel, /dispatchPendingNotifications\(\)\.catch/);
assert.doesNotMatch(emailChannel, /setInterval\(\(\) => void this\.dispatchPendingNotifications\(\)/);
assert.doesNotMatch(emailChannel, /void this\.dispatchPendingNotifications\(\);/);

assert.match(professionalEmail, /mail:smtp/);
assert.match(professionalEmail, /smtp\.yandex\.com/);
assert.match(professionalEmail, /auth: \{ type: 'OAuth2'/);
assert.match(professionalEmail, /replyTo: row\.email/);
assert.match(professionalEmail, /PROFESSIONAL_EMAIL_CREDENTIALS_KEY/);
assert.match(professionalEmail, /aes-256-gcm/);
assert.doesNotMatch(professionalEmail, /mail:imap|imap\.yandex/i);

assert.match(telegramBot, /private dispatchAllTenantsInBackground\(\)/);
assert.match(telegramBot, /dispatchAllTenants\(\)\.catch/);
assert.match(telegramBot, /private dispatchTenantInBackground\(tenantId: string\)/);
assert.match(telegramBot, /dispatchTenant\(tenantId\)\.catch/);
assert.doesNotMatch(telegramBot, /hasActivePdnConsentForContact\(tenantId, 'TELEGRAM'/);
assert.doesNotMatch(telegramBot, /setInterval\(\(\) => void this\.dispatchAllTenants\(\)/);
assert.doesNotMatch(telegramBot, /void this\.dispatchTenant\(tenantId\);/);

assert.match(notification, /ACTIVE_EXTERNAL_CHANNELS = new Set\(\['TELEGRAM', 'EMAIL'\]\)/);
assert.match(notification, /purpose !== 'MARKETING'\) return true/);
assert.doesNotMatch(notification, /hasActivePdnConsent\(tenantId, identity\.accountId\)/);
assert.match(notification, /pendingEmailDeliveries/);
assert.match(notification, /canSendEmailDelivery/);

assert.match(broadcast, /channel === 'EMAIL'/);
assert.match(broadcast, /canSendMarketing\(tenantId, channel, destination\)/);
assert.doesNotMatch(broadcast, /hasActivePdnConsentFor(?:Contact|Identity)\(/);
assert.match(broadcast, /\['TELEGRAM', 'EMAIL'\]\.includes\(preview\.channel\)/);
assert.match(compose, /DIRECT_CHANNEL_LABELS/);
assert.match(compose, /getCommunicationChannels/);
assert.match(compose, /clearV2ZHeaderRows/);
assert.match(compose, /mountChatChannelHeader/);
assert.match(compose, /sendCommunicationMessage\(\{\s*channel:/);
assert.doesNotMatch(compose, /channelOptions:\s*recipient\.mode/);
assert.match(chatRuntime, /mountChatChannelHeader/);
assert.match(chatRuntime, /segmentControl/);
assert.match(chatRuntime, /setV2ZHeaderRows/);
assert.match(chatRuntime, /name: 'messageChannel'/);
assert.match(chatRuntime, /channel: selectedChannel\(\)/);
assert.doesNotMatch(chatRuntime, /formData\.get\('messageChannel'\)/);
assert.doesNotMatch(sharedChat, /messageChannel/);
assert.doesNotMatch(sharedChat, /channelOptions/);

assert.match(transactional, /import \* as nodemailer from 'nodemailer'/);
assert.match(transactional, /postbox\.cloud\.yandex\.net/);
assert.match(transactional, /POSTBOX_API_KEY_ID/);
assert.match(transactional, /POSTBOX_API_KEY_SECRET/);
assert.match(transactional, /X-Message-Tag/);
assert.doesNotMatch(transactional, /smtp\.yandex\.ru|YANDEX_SMTP|X-Book-Tag/i);
assert.match(envExample, /TRANSACTIONAL_EMAIL_PROVIDER="yandex-postbox"/);
assert.match(envExample, /POSTBOX_API_KEY_ID=/);
assert.match(envExample, /POSTBOX_API_KEY_SECRET=/);
assert.match(envExample, /TRANSACTIONAL_EMAIL_FROM_EMAIL=/);
assert.match(envExample, /PROFESSIONAL_EMAIL_OAUTH_ENABLED="false"/);
assert.match(envExample, /PROFESSIONAL_EMAIL_CREDENTIALS_KEY=/);
assert.match(envExample, /YANDEX_MAIL_OAUTH_CLIENT_ID=/);
assert.match(envExample, /YANDEX_MAIL_OAUTH_CLIENT_SECRET=/);
assert.match(envExample, /EMAIL_DELIVERY_POLL_MS=/);
assert.doesNotMatch(envExample, /YANDEX_SMTP/);

console.log('Email, direct chat Z Header channel, and background delivery contract tests passed');
