import assert from 'node:assert/strict';
import fs from 'node:fs';

const core = fs.readFileSync('core.js', 'utf8');
const booking = fs.readFileSync('online-booking/booking.js', 'utf8');
const accountShell = fs.readFileSync('online-booking/account-shell.js', 'utf8');
const accountRuntime = fs.readFileSync('online-booking/account-runtime.js', 'utf8');
const browserPush = fs.readFileSync('core/notifications/web-push.js', 'utf8');
const routingUi = fs.readFileSync('core/notifications/routing.js', 'utf8');
const notificationSettingsUi = fs.readFileSync('settings/notifications/notifications.js', 'utf8');
const onlineBookingSettingsUi = fs.readFileSync('settings/online-booking/online-booking.js', 'utf8');
const serviceWorker = fs.readFileSync('service-worker.js', 'utf8');
const notificationService = fs.readFileSync('server/src/notification/notification.service.ts', 'utf8');
const notificationEventService = fs.readFileSync('server/src/notification/notification-event.service.ts', 'utf8');
const notificationCatalog = fs.readFileSync('server/src/notification/notification-events.ts', 'utf8');
const notificationController = fs.readFileSync('server/src/notification/notification.controller.ts', 'utf8');
const businessStateController = fs.readFileSync('server/src/business-state/business-state.controller.ts', 'utf8');
const pushService = fs.readFileSync('server/src/notification/web-push.service.ts', 'utf8');
const migration = fs.readFileSync('server/prisma/migrations/20260913070000_web_push_subscription/migration.sql', 'utf8');
const templateMigration = fs.readFileSync('server/prisma/migrations/20261005223000_notification_message_templates/migration.sql', 'utf8');
const enabledMigration = fs.readFileSync('server/prisma/migrations/20261006123000_notification_event_enabled/migration.sql', 'utf8');
const platformNoticeService = fs.readFileSync('server/src/platform-notice/platform-notice.service.ts', 'utf8');
const platformNoticeController = fs.readFileSync('server/src/platform-notice/platform-notice.controller.ts', 'utf8');
const platformPushMigration = fs.readFileSync('server/prisma/migrations/20260922173000_platform_push_subscription/migration.sql', 'utf8');
const adminUi = fs.readFileSync('admin/admin.js', 'utf8');
const platformNoticesUi = fs.readFileSync('core/platform-notices.js', 'utf8');

assert.match(core, /params\.get\('tg_entry'\)/);
assert.doesNotMatch(core, /params\.get\('tg'\)|params\.get\('telegram'\)/);
assert.doesNotMatch(booking, /telegramId/);
assert.match(accountRuntime, /bindAccountTelegramEntry/);
assert.doesNotMatch(accountRuntime, /mountBookingNotifications/);

assert.match(accountShell, /getAccountNotifications/);
assert.match(accountShell, /markAccountNotificationRead/);
assert.match(accountShell, /notificationMessages/);
assert.match(accountShell, /label: 'Push'/);
assert.match(accountShell, /enableWebPush/);
assert.match(accountShell, /disableWebPush/);
assert.equal(fs.existsSync('online-booking/notifications.js'), false, 'Legacy notification bridge must stay removed');

assert.match(browserPush, /serviceWorker\.register\('\/service-worker\.js'/);
assert.match(browserPush, /PushManager/);
assert.match(browserPush, /enableWebPush/);
assert.match(browserPush, /disableWebPush/);
assert.match(serviceWorker, /addEventListener\('push'/);
assert.match(serviceWorker, /addEventListener\('notificationclick'/);

assert.match(notificationService, /DELIVERY_POLICY_TYPE = '__delivery__'/);
assert.match(notificationService, /private async getDeliveryPolicy/);
assert.match(notificationService, /routed\.push\(\.\.\.await this\.queueChannel\(tenantId, notificationId, 'PUSH'/);
assert.match(notificationService, /const externalChannels = policy\.channels\.filter\(\(channel\) => ACTIVE_EXTERNAL_CHANNELS\.has\(channel\)\)/);
assert.match(notificationService, /if \(policy\.mode === 'fallback'\)/);
assert.match(notificationService, /private async queueFallbackAfter/);
assert.doesNotMatch(notificationService, /pushResult\.sent === 0 && pushResult\.failed > 0/);
assert.match(notificationService, /listAccountEndpoints/);
assert.match(notificationService, /dispatchNotification/);

assert.match(routingUi, /NOTIFICATION_DELIVERY_POLICY_TYPE = '__delivery__'/);
assert.match(routingUi, /getNotificationCatalog/);
assert.match(routingUi, /getNotificationDeliveryRouting/);
assert.match(routingUi, /saveNotificationDeliveryRouting/);
assert.match(routingUi, /setNotificationEnabled/);
assert.match(routingUi, /\['PUSH', 'TELEGRAM', 'EMAIL'\]\.includes\(value\)/);
assert.match(routingUi, /titleTemplate/);
assert.match(routingUi, /bodyTemplate/);

assert.match(notificationCatalog, /booking\.created/);
assert.match(notificationCatalog, /booking\.rescheduled/);
assert.match(notificationCatalog, /booking\.cancelled/);
assert.match(notificationCatalog, /finance\.payment/);
assert.match(notificationCatalog, /loan\.received/);
assert.match(notificationCatalog, /investment\.received/);
assert.match(notificationCatalog, /consent\.revoked/);
assert.match(notificationCatalog, /person\.birthday/);
assert.match(notificationController, /@Get\('catalog'\)/);
assert.match(notificationEventService, /EVENT_DISABLED/);
assert.match(notificationEventService, /"enabled"/);
assert.match(businessStateController, /NotificationEventService/);
assert.match(enabledMigration, /ADD COLUMN "enabled" BOOLEAN NOT NULL DEFAULT FALSE/);

assert.match(notificationSettingsUi, /getNotificationCatalog/);
assert.match(notificationSettingsUi, /v2Section/);
assert.match(notificationSettingsUi, /mountV2ZLayer/);
assert.match(notificationSettingsUi, /v2ZLayer/);
assert.match(notificationSettingsUi, /messageBubble/);
assert.match(notificationSettingsUi, /data-notification-enabled/);
assert.match(notificationSettingsUi, /data-v2-primary-action/);
assert.match(notificationSettingsUi, /data-v2-primary-label="Сохранить"/);
assert.match(notificationSettingsUi, /Заголовок сообщения/);
assert.match(notificationSettingsUi, /Текст сообщения/);
assert.match(notificationSettingsUi, /Во все выбранные каналы/);
assert.match(notificationSettingsUi, /По очереди, если предыдущий не доставлен/);
assert.match(notificationSettingsUi, /Push — всегда/);
assert.doesNotMatch(notificationSettingsUi, /v2ListEntry|v2ListEntries/);
assert.doesNotMatch(notificationSettingsUi, /variant:\s*'q'/);
assert.doesNotMatch(notificationSettingsUi, /data-notification-modes/);
assert.doesNotMatch(notificationSettingsUi, /data-notification-channels/);
assert.doesNotMatch(onlineBookingSettingsUi, /Настройки уведомлений/);
assert.doesNotMatch(onlineBookingSettingsUi, /getNotificationRouting/);
assert.doesNotMatch(onlineBookingSettingsUi, /saveNotificationRouting/);

assert.match(pushService, /webpush\.sendNotification/);
assert.match(pushService, /WEB_PUSH_VAPID_PUBLIC_KEY/);
assert.match(migration, /CREATE TABLE "WebPushSubscription"/);
assert.match(migration, /UNIQUE INDEX "WebPushSubscription_endpoint_key"/);
assert.match(templateMigration, /titleTemplate/);
assert.match(templateMigration, /bodyTemplate/);

assert.match(platformPushMigration, /PlatformPushSubscription/);
assert.match(platformPushMigration, /PlatformAccount/);
assert.match(platformNoticeService, /createForPlatformAdmins/);
assert.match(platformNoticeService, /webpush\.sendNotification/);
assert.match(platformNoticeController, /push\/configuration/);
assert.match(platformNoticeController, /push\/subscription/);
assert.match(platformNoticeController, /@Get\('push\/subscription'\)/);
assert.match(platformNoticeService, /pushSubscriptionState/);
assert.match(platformNoticesUi, /getPlatformPushState/);
assert.match(platformNoticesUi, /platform-notices\/push\/subscription\?endpoint=/);
assert.match(platformNoticesUi, /enablePlatformPush/);
assert.match(platformNoticesUi, /disablePlatformPush/);
assert.match(adminUi, /navigator\.serviceWorker\.register\('\/service-worker\.js'/);
assert.match(adminUi, /Notification\.requestPermission/);
assert.match(adminUi, /data-enable-admin-push/);
assert.match(adminUi, /Включить PUSH/);
assert.doesNotMatch(adminUi, /data-live-request-count/);

console.log('account and platform notification Web Push tests passed');
