ALTER TABLE "BookingAccount"
ADD COLUMN "profileData" JSONB NOT NULL DEFAULT '{}',
ADD COLUMN "uei" TEXT NOT NULL DEFAULT '',
ADD COLUMN "discountPercent" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "visits" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "totalSpent" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "lastVisit" TEXT NOT NULL DEFAULT '',
ADD COLUMN "programs" JSONB NOT NULL DEFAULT '[]';

ALTER TABLE "BookingRequest"
ADD COLUMN "recordSnapshot" JSONB;