import { costField, collectCost, initCostFields } from '../cost/index.js';
import { escapeHtml } from '../utils/escape-html.js';
const read=()=>JSON.parse(localStorage.getItem('book.workplaces')||'[]').filter(x=>!x.deletedAt);
const CONTEXT_KEY='book:workplace-context';
function readContext(){try{const value=JSON.parse(localStorage.getItem(CONTEXT_KEY)||'{}');return value&&typeof value==='object'?value:{}}catch{return {}}}
function writeContext(next){localStorage.setItem(CONTEXT_KEY,JSON.stringify(next));}
export function getWorkplaceContext(workplaces=read()){const context=readContext();const first=workplaces[0]?.key||'';const workplaceId=workplaces.some((item)=>item.key===context.workplaceId)?context.workplaceId:first;const parsedDate=typeof context.date==='string'?new Date(`${context.date}T00:00:00`):null;const date=parsedDate&&!Number.isNaN(parsedDate.getTime())?parsedDate:new Date();return {workplaceId,date};}
export function setWorkplaceContext({workplaceId,date}={}){const current=readContext();const next={...current};if(workplaceId!==undefined)next.workplaceId=workplaceId||'';if(date instanceof Date&&!Number.isNaN(date.getTime()))next.date=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;writeContext(next);return next;}
export function workplaceSelector({name='workplaces',selected=[],allowMultiple=true,costPerWorkplace=false}={}){const items=read(),options=items.map(w=>`<option value="${escapeHtml(w.key)}">${escapeHtml(w.name||'Без названия')}</option>`).join(''),first=selected.map(x=>x.workplaceId||x.id||x.key)[0]||'';return `<div class="workplace-selector" data-workplace-selector="${escapeHtml(name)}" data-cost-per-workplace="${costPerWorkplace?'true':'false'}"><div data-workplace-rows>${row(name,first,options,selected[0],costPerWorkplace)}</div>${allowMultiple?`<button type="button" class="ui-button ui-button--small" data-add-workplace>+ Добавить место работы</button>`:''}</div>`}
function row(name,value,options,selected={},withCost=false){const cost=selected?.cost||{},selectedOptions=options.replace(new RegExp(`value="${escapeHtml(value)}"`,'g'),`value="${escapeHtml(value)}" selected`);return `<div class="workplace-select-row" data-workplace-row><label class="field"><span>Место работы</span><select data-workplace-value name="${escapeHtml(name)}"><option value="">Выбор места работы</option>${selectedOptions}</select></label>${withCost?costField({name:`${name}-cost-${Math.random().toString(36).slice(2,8)}`,value:cost}):''}<button type="button" class="remove-button" data-remove-workplace aria-label="Удалить место работы">×</button></div>`}
export function initWorkplaceSelectors(root){root.querySelectorAll('[data-workplace-selector]').forEach(host=>{initCostFields(host);host.querySelector('[data-add-workplace]')?.addEventListener('click',()=>{const rows=host.querySelector('[data-workplace-rows]'),select=rows.querySelector('select'),withCost=host.dataset.costPerWorkplace==='true';rows.insertAdjacentHTML('beforeend',row(host.dataset.workplaceSelector,'',[...select.options].map(o=>o.outerHTML).join(''),{},withCost));const added=rows.lastElementChild;if(withCost)initCostFields(added)});host.addEventListener('click',e=>{if(e.target.closest('[data-remove-workplace]'))e.target.closest('[data-workplace-row]')?.remove()})})}
export function collectWorkplaceSelections(root,name='workplaces'){const host=root.querySelector(`[data-workplace-selector="${CSS.escape(name)}"]`);if(!host)return [];return [...host.querySelectorAll('[data-workplace-row]')].map(r=>{const id=r.querySelector('[data-workplace-value]')?.value||'',w=read().find(x=>x.key===id),costHost=r.querySelector('[data-cost-field]');return w?{workplaceId:w.key,name:w.name||'',cost:costHost?collectCost(r,costHost.dataset.costField):{}}:null}).filter(Boolean)}

export function workplaceHeaderButton({ workplace = null, showStats = false, stats = null } = {}) {
  const name = workplace?.name || 'Место работы';
  const safeName = escapeHtml(name);
  const counter = showStats && stats
    ? `<span class="timetable-workplace__days">${stats.days} дней</span><span class="timetable-workplace__time">${stats.hours} ч ${String(stats.minutes).padStart(2, '0')} м</span>`
    : '';
  return `<button type="button" class="timetable-workplace-button ui-button--secondary" data-workplace-header-open aria-label="Место работы: ${safeName}"><span class="timetable-workplace-button__name">${safeName}</span>${counter}<span class="timetable-workplace-button__arrow" aria-hidden="true">⌄</span></button>`;
}