import { accordion, actionBlock, agreementBlock, button, emptyState, entityCard, escapeHtml, field, iconButton, initAccordions, initPhotoField, initUEI, initMonthDayPickers, mountModal, modal, monthDayPicker, page, pageHeader, photoField, select, links, initLinks, collectLinks, tags, initTags, collectTags, listEntry, listEntries, repeatedField, initRepeatedFields, collectRepeatedEntries, uei } from '../../ui/ui.js';
import { applyUEI, detachUEI, getMembers, getOptions, getUEI } from '../../core/uei.js';
import { getTags } from '../../settings/tags/data.js';
import { createClient, getAllClients, getClients, saveClients } from './data.js';
import { openClientCreate } from './create.js';
import { clientDisplay } from './presentation.js';
import { getClientSortMode, setClientSortMode } from './view-state.js';

const name=p=>[p.name,p.surname].filter(Boolean).join(' '), money=v=>new Intl.NumberFormat('ru-RU').format(Number(v||0))+' ₽';
function sortItems(items,mode){return [...items].sort((a,b)=>{if(mode.startsWith('name')){const n=name(a).localeCompare(name(b),'ru');return mode==='nameDesc'?-n:n}const av=a.lastVisit?Date.parse(a.lastVisit):0,bv=b.lastVisit?Date.parse(b.lastVisit):0;return mode==='lastDesc'?bv-av:av-bv})}
function initial(p){return name(p).slice(0,1).toUpperCase()||'?'}
function sortOptions(){return [['nameAsc','Имя ↑'],['nameDesc','Имя ↓'],['lastAsc','Последнее посещение ↑'],['lastDesc','Последнее посещение ↓']].map(([value,label])=>({value,label}))}
export function renderClients(root){renderList(root)}
export function openClientProfile({root=document.body,key,onClose}={}){if(!key)return null;const m=mountModal(root,modal('<div data-client-profile-host></div>',{variant:'large',surface:'app'}));if(!m)return null;const host=m.querySelector('[data-client-profile-host]');renderProfile(host,key,{onBack:()=>{m.remove();onClose?.()}});return m}
function renderList(root){const items=getClients(),mode=getClientSortMode();root.innerHTML=`${pageHeader('Клиенты','',items.length)}<div class="ui-list-toolbar"><div class="ui-list-toolbar__sort">${select({value:mode,options:sortOptions(),aria:'Сортировка',data:'data-sort'})}</div><div class="ui-list-toolbar__actions">${button('Excel',{className:'ui-button--secondary',data:'data-excel'})}${iconButton('+',{className:'icon-button--primary',data:'data-add',aria:'Добавить'})}</div></div>${listMarkup(sortItems(items,mode))}`;root.querySelector('[data-add]').onclick=()=>addMenu(root);root.querySelector('[data-excel]').onclick=()=>excelMenu(root);root.querySelector('[data-sort]').onchange=e=>{setClientSortMode(e.target.value);renderList(root)};root.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>renderProfile(root,b.dataset.person));}
function listMarkup(items){if(!items.length)return emptyState('Клиентов пока нет','Добавьте человека кнопкой «+».');return listEntries(items.map(p=>{const display=clientDisplay(p);return listEntry({overline:display.uei,title:display.name,subtitle:display.phone,image:p.photo||'',initial:initial(p),interactive:true,data:`data-person="${escapeHtml(p.key)}"`,aria:`Открыть профиль ${display.name}`})}))}
function addMenu(root){const m=mountModal(root,modal(`<div class="modal-title"><h2>Добавить</h2><p>Выберите способ.</p></div><div class="modal-actions">${button('Создать',{data:'data-create'})}${button('Добавить из контактов',{className:'ui-button--secondary',data:'data-contacts'})}</div>`,{variant:'compact'}));if(!m)return;m.querySelector('[data-create]').onclick=()=>{m.remove();createForm(root)};m.querySelector('[data-contacts]').onclick=()=>contacts(root,m)}
function createForm(root,preset={}){openClientCreate({root,preset,onCreated:()=>renderList(root)})}
async function contacts(root,m){if(!navigator.contacts?.select){m.querySelector('.modal-title').insertAdjacentHTML('beforeend','<p class="form-error">Доступ к системным контактам не поддерживается этим браузером.</p>');return}try{const c=(await navigator.contacts.select(['name','tel'],{multiple:false}))[0];if(c){m.remove();createForm(root,{name:c.name?.[0]||'',phone:c.tel?.[0]||''})}}catch{}}
function excelMenu(root){const m=mountModal(root,modal(`<div class="modal-title"><h2>Excel</h2><p>CSV с разделителем «;» совместим с Excel.</p></div><div class="modal-actions">${button('Выгрузить',{data:'data-export'})}${button('Загрузить',{className:'ui-button--secondary',data:'data-import'})}${button('Шаблон',{className:'ui-button--secondary',data:'data-template'})}<input class="file-input" type="file" accept=".csv,text/csv" data-file></div>`,{variant:'compact'}));if(!m)return;m.querySelector('[data-export]').onclick=()=>{download(false);m.remove()};m.querySelector('[data-template]').onclick=()=>{download(true);m.remove()};m.querySelector('[data-import]').onclick=()=>m.querySelector('[data-file]').click();m.querySelector('[data-file]').onchange=e=>importCsv(e.target.files?.[0],root,m)}
function download(template){const h=['Имя','Фамилия','Телефон','Email'],rows=template?[]:getClients().map(p=>[p.name,p.surname,p.phones?.[0],p.emails?.[0]]),text='\uFEFF'+[h,...rows].map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\r\n'),url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=template?'Book-шаблон.csv':'Book-клиенты.csv';a.click();URL.revokeObjectURL(url)}
function importCsv(file,root,m){if(!file)return;const r=new FileReader();r.onload=()=>{const rows=String(r.result).replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean).map(x=>x.split(';').map(c=>c.replace(/^"|"$/g,'').replaceAll('""','"'))),all=getAllClients();rows.slice(1).forEach(([n,s,phone,email])=>{if(!n||!phone)return;const p=createClient(n,s,phone);if(email)p.emails=[email];all.push(p)});saveClients(all);m.remove();renderList(root)};r.readAsText(file,'utf-8')}
function memberPeople(p,all){const members=getMembers(p.uei);if(members.length<=1)return[p];const ids=members.map(member=>member.startsWith('person:')?member.slice(7):member);return ids.map(id=>all.find(person=>person.key===id)).filter(Boolean)}
function businessEntries(p,all,fieldName){const people=memberPeople(p,all),entries=[],seen=new Set();for(const person of people){for(const value of Array.isArray(person[fieldName])?person[fieldName]:[]){const text=String(value??'').trim();if(!text||seen.has(text))continue;seen.add(text);entries.push({value:text,source:person.key})}}return entries}
function contactAnchor(person){const telegram=(person.telegrams||[]).map(v=>String(v||'').trim()).find(Boolean);if(telegram)return{value:person.key,label:telegram};const phone=(person.phones||[]).map(v=>String(v||'').trim()).find(Boolean);if(phone)return{value:person.key,label:phone};const email=(person.emails||[]).map(v=>String(v||'').trim()).find(Boolean);if(email)return{value:person.key,label:email};return null}
function hasContact(person){return Boolean(contactAnchor(person))}
function ueiData(p,all){const current=p.uei||getUEI('person',p.key)||'';const existing=getOptions('person',p.key);const members=getMembers(current);const detachable=members.map(member=>{const id=member.startsWith('person:')?member.slice(7):member;const person=all.find(x=>x.key===id);return person?contactAnchor(person):null}).filter(Boolean);return{value:current,existing,detachable,showApply:false}}
function renderProfile(root,key,options={}){const all=getAllClients(),p=all.find(x=>x.key===key);if(!p)return options.onBack?options.onBack():renderList(root);const currentUEI=p.uei||getUEI('person',p.key)||'';const memberCount=currentUEI?getMembers(currentUEI).length:0;const ueiValueLeft=currentUEI?`- ${currentUEI}`:'';const ueiCount=memberCount>1?String(memberCount):'';const items=[{title:'UEI',valueLeft:ueiValueLeft,value:ueiCount,content:uei(ueiData(p,all))},{title:'Личные данные',content:`<div class="form-grid">${photoField({name:'photo',value:p.photo||''})}${field({label:'Имя',name:'name',value:p.name,required:true})}${field({label:'Фамилия',name:'surname',value:p.surname})}${select({label:'Пол',name:'gender',value:p.gender||'',options:[{value:'',label:'Не указан'},{value:'female',label:'Женский'},{value:'male',label:'Мужской'}]})}${monthDayPicker({label:'Дата рождения',name:'birthDate',value:p.birthDate||''})}</div>`},{title:'Контактные данные',content:repeatedField({label:'Телефон',name:'phones',values:businessEntries(p,all,'phones'),type:'tel'})+repeatedField({label:'Telegram',name:'telegrams',values:businessEntries(p,all,'telegrams')})+repeatedField({label:'Email',name:'emails',values:businessEntries(p,all,'emails'),type:'email'})},{title:'Ссылки',content:links({links:p.links||[],name:'client-links'})},{title:'Ярлыки',content:tags({tags:getTags(),selected:p.tags||[],name:'client-tags'})}];const meta=[{value:p.visits||0,label:'записей'},{value:money(p.totalSpent),label:'сумма'},{value:p.lastVisit?new Date(p.lastVisit).toLocaleDateString('ru-RU',{day:'2-digit',month:'2-digit'}):'—',label:'посещение'}];root.innerHTML=page([entityCard({id:p.uei,title:name(p),subtitle:p.phones?.[0]||'',image:p.photo||'',initial:initial(p),meta,className:'entity-card--hero'}),accordion(items),agreementBlock([{label:'Согласие ПДН',checked:Boolean(p.agreements?.personalData)},{label:'Согласие на рассылки',checked:Boolean(p.agreements?.mailings)}]),actionBlock(`${button('Сохранить',{className:'accordion-save',data:'data-save'})}${button('Назад',{className:'ui-button--secondary',data:'data-back'})}${button('Удалить',{variant:'danger',data:'data-delete'})}`)]);initPhotoField(root);initUEI(root);initMonthDayPickers(root);initLinks(root);initTags(root);initAccordions(root,{onDirty:()=>root.querySelector('[data-save]')?.classList.add('is-visible')});initRepeatedFields(root);root.querySelector('[data-save]').onclick=()=>saveProfile(root,p.key,options);root.querySelector('[data-back]').onclick=()=>options.onBack?options.onBack():renderList(root);root.querySelector('[data-delete]').onclick=()=>confirmDelete(root,p,options)}
function confirmDelete(root,p,options={}){const m=mountModal(root,modal(`<div class="modal-title"><h2>Удалить?</h2><p>${escapeHtml(name(p)||'Клиент')} будет удалён.</p></div><div class="modal-actions">${button('Удалить',{variant:'danger',data:'data-confirm-delete'})}${button('Отмена',{className:'ui-button--secondary',data:'data-cancel-delete'})}</div>`,{variant:'compact'}));if(!m)return;m.querySelector('[data-cancel-delete]').onclick=()=>m.remove();m.querySelector('[data-confirm-delete]').onclick=()=>deleteClient(root,p.key,m,options)}
function deleteClient(root,key,m,options={}){const all=getAllClients(),p=all.find(item=>item.key===key);if(!p){m?.remove();return options.onBack?options.onBack():renderList(root)}const current=getUEI('person',key)||p.uei||'';if(current)detachUEI({entityType:'person',entityId:key,uei:current,explicit:false});saveClients(all.filter(item=>item.key!==key));m?.remove();return options.onBack?options.onBack():renderList(root)}
function saveBusinessEntries(all,ownerKey,fieldName,entries,memberKeys){const valuesBySource=new Map(memberKeys.map(key=>[key,[]]));for(const entry of entries){const source=memberKeys.includes(entry.source)?entry.source:ownerKey;if(!valuesBySource.has(source))valuesBySource.set(source,[]);if(!valuesBySource.get(source).includes(entry.value))valuesBySource.get(source).push(entry.value)}for(const key of memberKeys){const person=all.find(item=>item.key===key);if(person)person[fieldName]=valuesBySource.get(key)||[]}}
function saveProfile(root,key,options={}){const all=getAllClients(),p=all.find(x=>x.key===key);if(!p)return;try{const oldUEI=p.uei;const memberKeys=(getMembers(oldUEI).map(member=>member.startsWith('person:')?member.slice(7):member));if(!memberKeys.length)memberKeys.push(key);p.name=root.querySelector('[name="name"]')?.value.trim()||p.name;p.surname=root.querySelector('[name="surname"]')?.value.trim()||'';p.photo=root.querySelector('[data-photo-value]')?.value||'';p.gender=root.querySelector('[name="gender"]')?.value||'';p.birthDate=root.querySelector('[name="birthDate"]')?.value||'';saveBusinessEntries(all,key,'phones',collectRepeatedEntries(root,'phones'),memberKeys);saveBusinessEntries(all,key,'telegrams',collectRepeatedEntries(root,'telegrams'),memberKeys);saveBusinessEntries(all,key,'emails',collectRepeatedEntries(root,'emails'),memberKeys);p.links=collectLinks(root,'client-links');p.tags=collectTags(root,'client-tags');const identifiers=[...(p.phones||[]),...(p.telegrams||[]),...(p.emails||[])];const value=root.querySelector('[name="uei"]')?.value||'';const linkValue=root.querySelector('[name="ueiLink"]')?.value||'';const detachValue=root.querySelector('[name="ueiDetach"]')?.value||'';if(detachValue){detachUEI({entityType:'person',entityId:detachValue,uei:oldUEI,explicit:true})}else if(linkValue&&!hasContact(p)){const targetMembers=getMembers(linkValue);const targetOwner=targetMembers[0]?.startsWith('person:')?targetMembers[0].slice(7):targetMembers[0];const remaining=all.filter(person=>person.key!==p.key);saveClients(remaining);renderProfile(root,targetOwner,options);return}else{applyUEI({entityType:'person',entityId:key,currentUEI:oldUEI,value,linkValue,identifiers})}saveClients(all);renderProfile(root,key,options)}catch(e){showError(e.message)}}
function showError(message){mountModal(document.body,modal(`<div class="modal-title"><h2>Ошибка</h2><p>${escapeHtml(message)}</p></div>`,{variant:'compact'}))}
