import { accordion, button, emptyState, escapeHtml, field, iconButton, initAccordions, mountModal, modal, pageHeader } from '../../ui/ui.js';

const KEY='book.people', USED='book.usedIds', SORT='book.people.sort';
const read=(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d));
const list=()=>read(KEY,[]), save=(v)=>localStorage.setItem(KEY,JSON.stringify(v));
const ids=()=>new Set(read(USED,[])), saveIds=(v)=>localStorage.setItem(USED,JSON.stringify([...v]));
const name=p=>[p.name,p.surname].filter(Boolean).join(' '), money=v=>new Intl.NumberFormat('ru-RU').format(Number(v||0))+' ₽';
function normalizeId(v){const s=String(v||'').trim().toUpperCase();if(!s)return '';if(!/^[A-Z0-9]{1,4}$/.test(s))throw Error('ID должен содержать от 1 до 4 букв или цифр.');return s.padStart(4,'0')}
function newPerson(nameValue,surname,phone,id=''){return{key:crypto.randomUUID(),id,name:nameValue,surname,phones:[phone],telegrams:[],emails:[],links:[],tags:[],loyalty:{discount:0,programs:[]},agreements:{personalData:false,mailings:false},visits:0,totalSpent:0,lastVisit:'',createdAt:new Date().toISOString()}}
function sortItems(items,mode){return [...items].sort((a,b)=>{if(mode.startsWith('name')){const n=name(a).localeCompare(name(b),'ru');return mode==='nameDesc'?-n:n}const av=a.lastVisit?Date.parse(a.lastVisit):0,bv=b.lastVisit?Date.parse(b.lastVisit):0;return mode==='lastDesc'?bv-av:av-bv})}

export function renderClients(root){renderList(root)}
function renderList(root){const items=list(),mode=localStorage.getItem(SORT)||'nameAsc';root.innerHTML=`${pageHeader('Клиенты',`${items.length} профилей`)}<section class="clients-toolbar">${iconButton('+',{className:'icon-button--primary',data:'data-add',aria:'Добавить'})}${button('Excel',{className:'ui-button--secondary',data:'data-excel'})}<label class="select-control"><span class="sr-only">Сортировка</span><select data-sort aria-label="Сортировка">${[['nameAsc','Имя ↑'],['nameDesc','Имя ↓'],['lastAsc','Последнее посещение ↑'],['lastDesc','Последнее посещение ↓']].map(([k,v])=>`<option value="${k}" ${k===mode?'selected':''}>${v}</option>`).join('')}</select></label></section>${listMarkup(sortItems(items,mode))}`;
root.querySelector('[data-add]').onclick=()=>addMenu(root);root.querySelector('[data-excel]').onclick=()=>excelMenu(root);root.querySelector('[data-sort]').onchange=e=>{localStorage.setItem(SORT,e.target.value);renderList(root)};root.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>renderProfile(root,b.dataset.person));}
function listMarkup(items){if(!items.length)return emptyState('Клиентов пока нет','Добавьте человека кнопкой «+».');return `<div class="people-list">${items.map(p=>`<button type="button" class="person-row" data-person="${escapeHtml(p.key)}"><span class="person-row__main"><strong>${p.id?`<span class="person-id">${escapeHtml(p.id)}</span> — `:''}${escapeHtml(name(p))}</strong><span>${escapeHtml(p.phones?.[0]||'')}</span></span><span class="row-chevron">›</span></button>`).join('')}</div>`}
function addMenu(root){mountModal(root,modal(`<div class="modal-title"><h2>Добавить</h2><p>Выберите способ.</p></div><div class="modal-actions">${button('Создать',{data:'data-create'})}${button('Добавить из контактов',{className:'ui-button--secondary',data:'data-contacts'})}</div>`));const m=root.querySelector('[data-modal]:last-of-type');m.querySelector('[data-create]').onclick=()=>{m.remove();createForm(root)};m.querySelector('[data-contacts]').onclick=()=>contacts(root,m)}
function createForm(root,preset={}){mountModal(root,modal(`<form class="compact-form" data-form><div class="modal-title"><h2>Создать</h2></div>${field({label:'Имя',name:'name',value:preset.name||'',required:true})}${field({label:'Фамилия',name:'surname',value:preset.surname||''})}${field({label:'Телефон',name:'phone',value:preset.phone||'',type:'tel',required:true,inputmode:'tel'})}${field({label:'ID',name:'id',placeholder:'____',inputmode:'text'})}<div class="form-error" data-error></div>${button('Сохранить',{type:'submit'})}</form>`));root.querySelector('[data-form]').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),all=list();try{const id=normalizeId(f.get('id'));if(id&&(ids().has(id)||all.some(p=>p.id===id)))throw Error('Этот ID уже использовался или принадлежит другому профилю.');const p=newPerson(String(f.get('name')).trim(),String(f.get('surname')).trim(),String(f.get('phone')).trim(),id);if(!p.name||!p.phones[0])throw Error('Имя и телефон обязательны.');all.push(p);save(all);if(id){const s=ids();s.add(id);saveIds(s)}root.querySelector('[data-modal]')?.remove();renderList(root)}catch(err){e.currentTarget.querySelector('[data-error]').textContent=err.message}}}
async function contacts(root,m){if(!navigator.contacts?.select){m.querySelector('.modal-title').insertAdjacentHTML('beforeend','<p class="form-error">Доступ к системным контактам не поддерживается этим браузером.</p>');return}try{const c=(await navigator.contacts.select(['name','tel'],{multiple:false}))[0];if(c){m.remove();createForm(root,{name:c.name?.[0]||'',phone:c.tel?.[0]||''})}}catch{}}

function excelMenu(root){mountModal(root,modal(`<div class="modal-title"><h2>Excel</h2><p>CSV с разделителем «;» совместим с Excel.</p></div><div class="modal-actions">${button('Выгрузить',{data:'data-export'})}${button('Загрузить',{className:'ui-button--secondary',data:'data-import'})}${button('Шаблон',{className:'ui-button--secondary',data:'data-template'})}<input class="file-input" type="file" accept=".csv,text/csv" data-file></div>`));const m=root.querySelector('[data-modal]:last-of-type');m.querySelector('[data-export]').onclick=()=>{download(false);m.remove()};m.querySelector('[data-template]').onclick=()=>{download(true);m.remove()};m.querySelector('[data-import]').onclick=()=>m.querySelector('[data-file]').click();m.querySelector('[data-file]').onchange=e=>importCsv(e.target.files?.[0],root,m)}
function download(template){const h=['ID','Имя','Фамилия','Телефон','Email'],rows=template?[]:list().map(p=>[p.id,p.name,p.surname,p.phones?.[0],p.emails?.[0]]),text='\uFEFF'+[h,...rows].map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\r\n'),url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=template?'Book-шаблон.csv':'Book-клиенты.csv';a.click();URL.revokeObjectURL(url)}
function importCsv(file,root,m){if(!file)return;const r=new FileReader();r.onload=()=>{const rows=String(r.result).replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean).map(x=>x.split(';').map(c=>c.replace(/^"|"$/g,'').replaceAll('""','"'))),all=list(),used=ids();rows.slice(1).forEach(([raw,n,s,phone,email])=>{if(!n||!phone)return;let id='';try{id=normalizeId(raw)}catch{}if(id&&used.has(id))id='';const p=newPerson(n,s,phone,id);if(email)p.emails=[email];all.push(p);if(id)used.add(id)});save(all);saveIds(used);m.remove();renderList(root)};r.readAsText(file,'utf-8')}

function renderProfile(root,key){const p=list().find(x=>x.key===key);if(!p)return renderList(root);const items=[
{title:'ID',content:p.id?`<div class="locked-value"><strong>${escapeHtml(p.id)}</strong><span>Закреплён</span></div>`:`<div class="form-grid">${field({label:'ID',name:'id',placeholder:'____',inputmode:'text'})}</div>`},
{title:'Личные данные',content:`<div class="form-grid">${field({label:'Имя',name:'name',value:p.name,required:true})}${field({label:'Фамилия',name:'surname',value:p.surname})}<label class="field"><span>Пол</span><select name="gender"><option value="">Не указан</option><option value="female" ${p.gender==='female'?'selected':''}>Женский</option><option value="male" ${p.gender==='male'?'selected':''}>Мужской</option></select></label>${field({label:'Дата рождения',name:'birthDate',value:p.birthDate||'',type:'date'})}</div>`},
{title:'Контактные данные',content:arrayGroup('Телефон','phones',p.phones,'tel')+arrayGroup('Telegram','telegrams',p.telegrams)+arrayGroup('Email','emails',p.emails,'email')},
{title:'Программа лояльности',value:p.loyalty?.discount?`${p.loyalty.discount}%`:'',content:`<div class="loyalty-content"><label class="field"><span>Скидка</span><select name="discount"><option value="0">Без скидки</option>${Array.from({length:100},(_,i)=>i+1).map(i=>`<option value="${i}" ${i===Number(p.loyalty?.discount||0)?'selected':''}>${i}%</option>`).join('')}</select></label><div class="array-group"><span class="array-label">Назначенные программы</span><div data-programs>${(p.loyalty?.programs||[]).map(v=>`<div class="array-row"><input name="programs" value="${escapeHtml(v)}"><button type="button" class="remove-button">×</button></div>`).join('')}</div>${button('+ Программа',{className:'ui-button--small',data:'data-add-array="programs"'})}</div></div>`},
{title:'Ссылки',content:`<div data-links>${(p.links||[]).map(linkRow).join('')}</div>${button('+ Добавить ссылку',{className:'ui-button--small',data:'data-add-link'})}`},
{title:'Ярлыки',content:`<div class="tag-list">${(p.tags||[]).map(t=>`<span class="tag">${escapeHtml(t)}</span>`).join('')||'<span class="muted">Назначаются из общей системы Настроек.</span>'}</div>`}];
root.innerHTML=`${banner(p)}${accordion(items)}<section class="agreements-summary"><div><span>Согласие ПДН</span><strong>${p.agreements?.personalData?'Дано':'Не дано'}</strong></div><div><span>Согласие на рассылки</span><strong>${p.agreements?.mailings?'Дано':'Не дано'}</strong></div></section><div class="profile-actions">${button('Сохранить',{data:'data-save'})}${button('Назад',{className:'ui-button--secondary',data:'data-back'})}</div>`;
initAccordions(root);root.onclick=e=>{const remove=e.target.closest('.remove-button');if(remove)remove.closest('.array-row')?.remove();const add=e.target.closest('[data-add-array]');if(add)addArray(root,add.dataset.addArray);const link=e.target.closest('[data-add-link]');if(link)root.querySelector('[data-links]')?.insertAdjacentHTML('beforeend',linkRow())};root.querySelector('[data-save]').onclick=()=>saveProfile(root,p.key);root.querySelector('[data-back]').onclick=()=>renderList(root)}
function banner(p){const initial=escapeHtml(name(p).slice(0,1).toUpperCase()||'?');return `<section class="profile-banner"><div class="profile-banner__photo" aria-hidden="true">${initial}</div><div class="profile-banner__body">${p.id?`<span class="profile-id">${escapeHtml(p.id)}</span>`:''}<h1>${escapeHtml(name(p))}</h1><p>${escapeHtml(p.phones?.[0]||'')}</p><div class="metrics"><span><strong>${p.visits||0}</strong><small>записей</small></span><span><strong>${money(p.totalSpent)}</strong><small>сумма</small></span><span><strong>${p.lastVisit?new Date(p.lastVisit).toLocaleDateString('ru-RU',{day:'2-digit',month:'2-digit'}):'—'}</strong><small>посещение</small></span></div></div></section>`}
function arrayGroup(label,name,values,type='text'){return `<div class="array-group"><span class="array-label">${label}</span><div data-array-group="${name}">${(values?.length?values:['']).map(v=>`<div class="array-row"><input type="${type}" name="${name}" value="${escapeHtml(v)}" placeholder="Добавить значение"><button type="button" class="remove-button">×</button></div>`).join('')}</div>${button('+',{className:'ui-button--small',data:`data-add-array="${name}"`})}</div>`}
function linkRow(l={}){return `<div class="array-row link-row"><select name="linkType"><option ${l.type==='Instagram'?'selected':''}>Instagram</option><option ${l.type==='ВКонтакте'?'selected':''}>ВКонтакте</option><option ${l.type==='YouTube'?'selected':''}>YouTube</option><option ${l.type==='Facebook'?'selected':''}>Facebook</option><option ${l.type==='Сайт'?'selected':''}>Сайт</option><option ${l.type==='Другое'?'selected':''}>Другое</option></select><input name="linkUrl" value="${escapeHtml(l.url||'')}" placeholder="URL"><button type="button" class="remove-button">×</button></div>`}
function addArray(root,n){const g=root.querySelector(`[data-array-group="${n}"]`)||root.querySelector('[data-programs]');if(!g)return;const type=n==='phones'?'tel':n==='emails'?'email':'text';g.insertAdjacentHTML('beforeend',`<div class="array-row"><input type="${type}" name="${n}" placeholder="Добавить значение"><button type="button" class="remove-button">×</button></div>`)}
function saveProfile(root,key){const all=list(),p=all.find(x=>x.key===key);if(!p)return;const vals=n=>[...root.querySelectorAll(`[name="${n}"]`)].map(x=>x.value.trim()).filter(Boolean),idInput=root.querySelector('[name="id"]');if(idInput){try{const id=normalizeId(idInput.value);if(id&&(ids().has(id)||all.some(x=>x.id===id&&x.key!==key)))throw Error('Этот ID уже использовался или принадлежит другому профилю.');p.id=id;if(id){const s=ids();s.add(id);saveIds(s)}}catch(e){alert(e.message);return}}p.name=root.querySelector('[name="name"]')?.value.trim()||p.name;p.surname=root.querySelector('[name="surname"]')?.value.trim()||'';p.gender=root.querySelector('[name="gender"]')?.value||'';p.birthDate=root.querySelector('[name="birthDate"]')?.value||'';p.phones=vals('phones');p.telegrams=vals('telegrams');p.emails=vals('emails');p.loyalty={discount:Number(root.querySelector('[name="discount"]')?.value||0),programs:vals('programs')};p.links=[...root.querySelectorAll('[data-links] .link-row')].map(r=>({type:r.querySelector('[name="linkType"]')?.value||'',url:r.querySelector('[name="linkUrl"]')?.value.trim()||''})).filter(x=>x.url);save(all);renderProfile(root,key)}
