import { button, collectWorkplaceSelections, durationPicker, emptyState, entityCard, escapeHtml, iconButton, initDurationPickers, initPhotoField, initWorkplaceSelectors, mountModal, modal, pageHeader, photoField, workplaceSelector } from '../../../ui/ui.js';

const KEY='book.procedures';
const HISTORY_KEY='book.procedures.history';
const read=(key,fallback)=>JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback));
const write=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
const list=()=>read(KEY,[]).filter(x=>!x.deletedAt);
const historyPush=(record,action)=>{const h=read(HISTORY_KEY,[]);h.push({...record,historyAction:action,historyAt:new Date().toISOString()});write(HISTORY_KEY,h)};
const fmtMoney=v=>v===''||v==null?'':`${Number(v).toLocaleString('ru-RU')} ₽`;
const costText=c=>{if(!c||c.free)return '';if(c.mode==='from-to')return `от ${fmtMoney(c.from)}<br>до ${fmtMoney(c.to)}`;if(c.mode==='from')return `от ${fmtMoney(c.from)}`;return fmtMoney(c.amount)};
const durationText=m=>{m=Number(m)||0;const h=Math.floor(m/60),min=m%60;return h?`${h} ч${min?` ${min} мин`:''}`:`${min} мин`};
const summaryCost=p=>{const costs=(p.workplaces||[]).map(w=>w.cost).filter(c=>c&&!c.free);if(!costs.length)return '';if(costs.length===1)return costText(costs[0]);const values=costs.flatMap(c=>[c.amount,c.from]).map(Number).filter(Number.isFinite);return values.length?`от ${fmtMoney(Math.min(...values))}`:''};
function renderList(root,navigateBack){const items=list();root.innerHTML=`<div class="entity-page-header">${pageHeader('Процедуры')}<div class="page-header-action">${iconButton('+',{className:'icon-button--primary',data:'data-add-procedure',aria:'Добавить процедуру'})}</div></div>${items.length?`<div class="entity-list">${items.map(renderRow).join('')}</div>`:emptyState('Процедур пока нет','Добавьте первую процедуру кнопкой «+».')}<div class="profile-actions">${button('Назад',{className:'ui-button--secondary',data:'data-back-procedures'})}</div>`;root.querySelector('[data-add-procedure]')?.addEventListener('click',()=>openForm(root));root.querySelectorAll('[data-procedure]').forEach(el=>el.addEventListener('click',()=>renderCard(root,el.dataset.procedure,navigateBack)));root.querySelectorAll('[data-delete-procedure]').forEach(el=>el.addEventListener('click',e=>{e.stopPropagation();deleteProcedure(root,el.dataset.deleteProcedure,navigateBack)}));root.querySelector('[data-back-procedures]')?.addEventListener('click',navigateBack)}
function renderRow(p){return `<button type="button" class="entity-list-row" data-procedure="${escapeHtml(p.id)}"><span class="entity-list-row__main"><strong>${escapeHtml(p.name)}</strong><small>${durationText(p.duration)}</small></span><span class="entity-list-row__price">${summaryCost(p)}</span><span class="entity-list-row__delete" data-delete-procedure="${escapeHtml(p.id)}">×</span></button>`}
function openForm(root,existing=null){const p=existing||{photo:'',name:'',duration:0,breakDuration:0,workplaces:[]};const html=`<form class="compact-form" data-procedure-form><div class="modal-title"><h2>${existing?'Изменить процедуру':'Процедура'}</h2></div>${photoField({name:'procedurePhoto',value:p.photo||''})}<label class="field"><span>Название *</span><input name="procedureName" required value="${escapeHtml(p.name||'')}" placeholder="Название процедуры"></label>${durationPicker({label:'Длительность',name:'procedureDuration',value:p.duration||0})}${durationPicker({label:'Перерыв',name:'procedureBreak',value:p.breakDuration||0})}<div class="array-group"><span class="array-label">Рабочие места и стоимость</span>${workplaceSelector({name:'procedureWorkplaces',selected:p.workplaces||[],allowMultiple:true,costPerWorkplace:true})}</div>${button('Сохранить',{type:'submit'})}</form>`;const m=mountModal(root,modal(html));initPhotoField(m);initDurationPickers(m);initWorkplaceSelectors(m);m.querySelector('[data-procedure-form]')?.addEventListener('submit',e=>{e.preventDefault();saveProcedure(root,m,existing)})}
function saveProcedure(root,m,existing){const data=new FormData(m.querySelector('[data-procedure-form]'));const name=String(data.get('procedureName')||'').trim();if(!name)return;const selected=collectWorkplaceSelections(m,'procedureWorkplaces');const item={id:existing?.id||crypto.randomUUID(),photo:String(data.get('procedurePhoto')||''),name,duration:Number(data.get('procedureDuration')||0),breakDuration:Number(data.get('procedureBreak')||0),workplaces:selected,createdAt:existing?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(existing)historyPush(existing,'updated');const items=list();write(KEY,existing?items.map(x=>x.id===existing.id?item:x):[...items,item]);m.remove();renderList(root)}
function renderCard(root,id,navigateBack){const p=list().find(x=>x.id===id);if(!p)return renderList(root,navigateBack);root.innerHTML=`${pageHeader(p.name)}${entityCard({image:p.photo||'',initial:(p.name||'?').slice(0,1).toUpperCase(),className:'entity-card--hero entity-card--procedure',top:`<span class="entity-card__duration">${durationText(p.duration)}</span>`,bottom:`<strong class="entity-card__entity-name">${escapeHtml(p.name)}</strong>`,right:`<span class="entity-card__entity-price">${summaryCost(p)}</span>`})}<div class="entity-details"><div><span>Перерыв</span><strong>${durationText(p.breakDuration)}</strong></div>${p.workplaces?.length?`<div><span>Места работы</span><strong>${escapeHtml(p.workplaces.map(w=>w.name||w.workplaceId).join(', '))}</strong></div>`:''}</div><div class="profile-actions">${button('Редактировать процедуру',{data:'data-edit-procedure'})}${button('Удалить',{className:'ui-button--secondary',data:'data-delete-card'})}${button('Назад',{className:'ui-button--secondary',data:'data-back-procedures-card'})}</div>`;root.querySelector('[data-edit-procedure]').onclick=()=>openForm(root,p);root.querySelector('[data-delete-card]').onclick=()=>deleteProcedure(root,id,navigateBack);root.querySelector('[data-back-procedures-card]').onclick=()=>renderList(root,navigateBack)}
function deleteProcedure(root,id,navigateBack){const items=list();const found=items.find(x=>x.id===id);if(!found)return;historyPush(found,'deleted');write(KEY,items.map(x=>x.id===id?{...x,deletedAt:new Date().toISOString()}:x));renderList(root,navigateBack)}
export function renderProcedures(root,navigateBack=()=>{}){renderList(root,navigateBack)}
