import { button, collectCost, collectWorkplaceSelections, costField, emptyState, entityCard, escapeHtml, iconButton, initCostFields, initPhotoField, initWorkplaceSelectors, mountModal, modal, pageHeader, photoField, workplaceSelector } from '../../../ui/ui.js';

const KEY='book.products';
const HISTORY_KEY='book.products.history';
const read=(key,fallback)=>JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback));
const write=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
const list=()=>read(KEY,[]).filter(x=>!x.deletedAt);
const historyPush=(record,action)=>{const h=read(HISTORY_KEY,[]);h.push({...record,historyAction:action,historyAt:new Date().toISOString()});write(HISTORY_KEY,h)};
const fmtMoney=v=>v===''||v==null?'':`${Number(v).toLocaleString('ru-RU')} ₽`;
const costText=c=>c?.free?'':fmtMoney(c?.amount);
function renderList(root,navigateBack){const items=list();root.innerHTML=`<div class="entity-page-header">${pageHeader('Товары')}<div class="page-header-action">${iconButton('+',{className:'icon-button--primary',data:'data-add-product',aria:'Добавить товар'})}</div></div>${items.length?`<div class="entity-list">${items.map(renderRow).join('')}</div>`:emptyState('Товаров пока нет','Добавьте первый товар кнопкой «+».')}<div class="profile-actions">${button('Назад',{className:'ui-button--secondary',data:'data-back-products'})}</div>`;root.querySelector('[data-add-product]')?.addEventListener('click',()=>openForm(root));root.querySelectorAll('[data-product]').forEach(el=>el.addEventListener('click',()=>renderCard(root,el.dataset.product,navigateBack)));root.querySelectorAll('[data-delete-product]').forEach(el=>el.addEventListener('click',e=>{e.stopPropagation();deleteProduct(root,el.dataset.deleteProduct,navigateBack)}));root.querySelector('[data-back-products]')?.addEventListener('click',navigateBack)}
function renderRow(p){return `<button type="button" class="entity-list-row" data-product="${escapeHtml(p.id)}"><span class="entity-list-row__main"><strong>${escapeHtml(p.name)}</strong></span><span class="entity-list-row__price">${costText(p.cost)}</span><span class="entity-list-row__delete" data-delete-product="${escapeHtml(p.id)}">×</span></button>`}
function openForm(root,existing=null){const p=existing||{photo:'',name:'',cost:{amount:'',free:false},about:'',workplaces:[]};const html=`<form class="compact-form" data-product-form><div class="modal-title"><h2>${existing?'Изменить товар':'Товар'}</h2></div>${photoField({name:'productPhoto',value:p.photo||''})}<label class="field"><span>Название *</span><input name="productName" required value="${escapeHtml(p.name||'')}" placeholder="Название товара"></label>${costField({value:p.cost||{},name:'productCost',modes:['amount'],free:true})}<div class="array-group"><span class="array-label">Описание</span><label class="field"><textarea name="productAbout" rows="7" maxlength="5000" placeholder="Описание товара">${escapeHtml(p.about||'')}</textarea></label></div><div class="array-group"><span class="array-label">Рабочие места</span>${workplaceSelector({name:'productWorkplaces',selected:p.workplaces||[],allowMultiple:true})}</div>${button('Сохранить',{type:'submit'})}</form>`;const m=mountModal(root,modal(html));initPhotoField(m);initCostFields(m);initWorkplaceSelectors(m);m.querySelector('[data-product-form]')?.addEventListener('submit',e=>{e.preventDefault();saveProduct(root,m,existing)})}
function saveProduct(root,m,existing){const data=new FormData(m.querySelector('[data-product-form]'));const name=String(data.get('productName')||'').trim();if(!name)return;const item={id:existing?.id||crypto.randomUUID(),photo:String(data.get('productPhoto')||''),name,cost:collectCost(m,'productCost'),about:String(data.get('productAbout')||'').trim(),workplaces:collectWorkplaceSelections(m,'productWorkplaces'),createdAt:existing?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(existing)historyPush(existing,'updated');const items=list();write(KEY,existing?items.map(x=>x.id===existing.id?item:x):[...items,item]);m.remove();renderList(root)}
function renderCard(root,id,navigateBack){const p=list().find(x=>x.id===id);if(!p)return renderList(root,navigateBack);root.innerHTML=`${pageHeader(p.name)}${entityCard({image:p.photo||'',initial:(p.name||'?').slice(0,1).toUpperCase(),className:'entity-card--hero entity-card--product',bottom:`<strong class="entity-card__entity-name">${escapeHtml(p.name)}</strong>`,right:`<span class="entity-card__entity-price">${costText(p.cost)}</span>`})}${p.about?`<div class="entity-details"><div><span>Описание</span><strong>${escapeHtml(p.about)}</strong></div></div>`:''}${p.workplaces?.length?`<div class="entity-details"><div><span>Места работы</span><strong>${escapeHtml(p.workplaces.map(w=>w.name||w.workplaceId).join(', '))}</strong></div></div>`:''}<div class="profile-actions">${button('Редактировать товар',{data:'data-edit-product'})}${button('Удалить',{className:'ui-button--secondary',data:'data-delete-card'})}${button('Назад',{className:'ui-button--secondary',data:'data-back-products-card'})}</div>`;root.querySelector('[data-edit-product]').onclick=()=>openForm(root,p);root.querySelector('[data-delete-card]').onclick=()=>deleteProduct(root,id,navigateBack);root.querySelector('[data-back-products-card]').onclick=()=>renderList(root,navigateBack)}
function deleteProduct(root,id,navigateBack){const items=list();const found=items.find(x=>x.id===id);if(!found)return;historyPush(found,'deleted');write(KEY,items.map(x=>x.id===id?{...x,deletedAt:new Date().toISOString()}:x));renderList(root,navigateBack)}
export function renderProducts(root,navigateBack=()=>{}){renderList(root,navigateBack)}
