import { entityCard, escapeHtml, listEntry, mountModal, modal, timePicker, initTimePickers, initMultiSelect } from '../ui/ui.js';
import { createRecord, deleteRecord } from '../core/record.js';
import { isTimeRangeAvailable, getTimeUsages } from '../core/time-usage.js';
import { getWorkplaces } from '../core/workplace-time.js';

const readList = (key) => { try { const value = JSON.parse(localStorage.getItem(key) || '[]'); return Array.isArray(value) ? value : []; } catch { return []; } };
const people = () => readList('book.people');
const procedures = () => readList('book.procedures').filter((item) => !item.deletedAt);
const clientName = (person) => [person?.name, person?.surname].filter(Boolean).join(' ') || 'Без имени';
const durationText = (minutes) => { const m = Number(minutes) || 0; const h = Math.floor(m / 60); const min = m % 60; return h ? `${h} ч${min ? ` ${min} мин` : ''}` : `${min} мин`; };
const timeToMinutes = (value) => { const match = String(value || '').match(/^(\d{1,2}):(\d{2})$/); return match ? Number(match[1]) * 60 + Number(match[2]) : null; };
const minutesToTime = (value) => `${String(Math.floor(value / 60)).padStart(2, '0')}:${String(value % 60).padStart(2, '0')}`;
function dateKey(date) { const d = date instanceof Date ? date : new Date(date); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`; }
function scopedUsages(date, workplaceId) {
  const day = dateKey(date);
  return getTimeUsages({
    records: readList('book.records').filter((item) => item?.date === day && item?.workplaceId === String(workplaceId || '')),
    breaks: readList('book.journalBreaks').filter((item) => item?.date === day && item?.workplaceId === String(workplaceId || '')),
  });
}
function nextFiveMinutes(from) { const start = timeToMinutes(from); if (start == null) return []; const hourStart = Math.floor(start / 60) * 60, hourEnd = hourStart + 60, result = []; for (let value = Math.ceil(start / 5) * 5; value < hourEnd; value += 5) result.push(minutesToTime(value)); return result; }
function openTimeModal({ date, workplaceId, from, to, onCreated }) {
  const usages = scopedUsages(date, workplaceId);
  const values = nextFiveMinutes(from).filter((value) => isTimeRangeAvailable({ from: value, to: minutesToTime(timeToMinutes(value) + 5), usages }));
  const times = values.map((value) => `<button type="button" class="record-time-option${/:(00|15|30|45)$/.test(value) ? ' is-quarter' : ''}" data-record-time="${value}">${value}</button>`).join('');
  const toggle = `<div class="segment-control segment-control--two" data-record-mode><button type="button" class="is-active" data-record-mode-value="record">Создать запись</button><button type="button" data-record-mode-value="block">Занять время</button></div>`;
  const m = mountModal(document.body, modal(`<div class="record-screen record-screen--time">${toggle}<div class="record-time-list">${times || '<div class="muted">Нет свободного времени</div>'}</div></div>`, { className: 'record-modal record-modal--full' })); if (!m) return;
  const bindTimes = () => m.querySelectorAll('[data-record-time]').forEach((node) => node.addEventListener('click', () => { const selected = node.dataset.recordTime; m.remove(); openProceduresModal({ date, workplaceId, from: selected, to, onCreated }); }));
  m.querySelectorAll('[data-record-mode-value]').forEach((node) => node.addEventListener('click', () => { m.querySelectorAll('[data-record-mode-value]').forEach((item) => item.classList.toggle('is-active', item === node)); if (node.dataset.recordModeValue === 'block') { m.remove(); openBlockEndModal({ date, workplaceId, from, onCreated }); return; } m.querySelector('.record-time-list').innerHTML = times || '<div class="muted">Нет свободного времени</div>'; bindTimes(); })); bindTimes();
}
function workplaceAssignment(procedure, workplaceId) {
  const id = String(workplaceId || '');
  return (procedure?.workplaces || []).find((workplace) => String(workplace?.workplaceId ?? workplace?.id ?? workplace?.key ?? '') === id) || null;
}
function procedureForWorkplace(procedure, workplaceId) { return workplaceAssignment(procedure, workplaceId) ? procedure : null; }
function defaultCost(procedure, workplaceId) {
  const assignment = workplaceAssignment(procedure, workplaceId); const assignmentCost = assignment?.cost; const procedureCost = procedure?.cost;
  const cost = assignmentCost && typeof assignmentCost === 'object' && !assignmentCost.free && (assignmentCost.amount !== '' && assignmentCost.amount != null || assignmentCost.from !== '' && assignmentCost.from != null || assignmentCost.to !== '' && assignmentCost.to != null) ? assignmentCost : procedureCost;
  if (!cost || cost.free) return ''; if (typeof cost === 'number' || typeof cost === 'string') return cost; return cost.amount ?? cost.from ?? '';
}
function openProceduresModal({ date, workplaceId, from, to, onCreated }) {
  const items = procedures().filter((procedure) => procedureForWorkplace(procedure, workplaceId)); const selected = new Map(); let selectionController = null;
  const content = `<div class="record-screen record-screen--procedures"><div class="record-modal-toolbar"><strong>Процедуры</strong><button type="button" class="icon-button icon-button--primary" data-record-add aria-label="Добавить процедуру">+</button></div><div data-record-procedures></div><div class="record-modal-actions modal-actions" data-record-actions></div></div>`;
  const m = mountModal(document.body, modal(content, { className: 'record-modal record-modal--full' })); if (!m) return;
  const syncActions = () => { const hasSelection = selected.size > 0; const actions = m.querySelector('[data-record-actions]'); if (!actions) return; actions.innerHTML = hasSelection ? '<button type="button" class="ui-button ui-button--secondary" data-record-reset>Сброс выбора</button><button type="button" class="ui-button" data-record-next>Далее →</button>' : ''; if (hasSelection) actions.querySelector('[data-record-reset]')?.addEventListener('click', () => { selected.clear(); selectionController?.setSelectedValues([]); }); if (hasSelection) actions.querySelector('[data-record-next]')?.addEventListener('click', () => { const duration = [...selected.values()].reduce((sum, item) => sum + (Number(item.duration) || 0), 0), end = minutesToTime(timeToMinutes(from) + duration), usages = scopedUsages(date, workplaceId); if (!isTimeRangeAvailable({ from, to: end, usages })) { alert('Это время уже занято.'); return; } m.remove(); openClientModal({ date, workplaceId, from, to: end, procedures: [...selected.values()], onCreated }); }); };
  const render = () => { const host = m.querySelector('[data-record-procedures]'); host.innerHTML = items.length ? items.map((procedure) => listEntry({ title: procedure.name || '', subtitle: durationText(procedure.duration), interactive: true, data: `data-procedure-select="${escapeHtml(procedure.id)}"`, aria: `Выбрать процедуру ${procedure.name || ''}`, actionData: `data-procedure-settings="${escapeHtml(procedure.id)}" data-selection-action`, actionAria: `Настройки процедуры ${procedure.name || ''}`, actionIcon: '⚙', className: selected.has(procedure.id) ? 'is-selected' : '' })).join('') : '<div class="muted">Процедур для этого места работы пока нет.</div>'; syncActions(); selectionController?.destroy(); selectionController = initMultiSelect(host, { selectedValues: [...selected.keys()], selector: '[data-procedure-select]', valueAttribute: 'procedureSelect', onChange: (values) => { const next = new Map(); values.forEach((id) => { const procedure = items.find((item) => item.id === id); if (procedure) next.set(id, selected.get(id) || { procedure, cost: defaultCost(procedure, workplaceId), duration: Number(procedure.duration) || 0 }); }); selected.clear(); next.forEach((value, id) => selected.set(id, value)); syncActions(); } }); m.querySelectorAll('[data-procedure-settings]').forEach((node) => node.addEventListener('click', (event) => { event.preventDefault(); event.stopPropagation(); openProcedureSettings(m, items.find((item) => item.id === node.dataset.procedureSettings), selected, selectionController, workplaceId); })); };
  m.querySelector('[data-record-add]').addEventListener('click', () => {}); render();
}
function openProcedureSettings(parent, procedure, selected, selectionController, workplaceId) {
  if (!procedure) return; const current = selected.get(procedure.id) || { procedure, cost: defaultCost(procedure, workplaceId), duration: Number(procedure.duration) || 0 };
  const html = `<div class="record-setting-title">${escapeHtml(procedure.name)}</div><div class="record-setting-note">установите необходимые параметры услуги для данной записи</div><div class="record-setting-row"><span>Стоимость</span><input inputmode="decimal" data-record-cost value="${current.cost === '' ? '' : `${current.cost} ₽`}"></div><div class="record-setting-row"><span>Длительность</span>${timePicker({ name: 'recordDuration', label: '', value: `${String(Math.floor(current.duration / 60)).padStart(2, '0')}:${String(current.duration % 60).padStart(2, '0')}`, minuteStep: 5 })}</div><div class="record-setting-actions"><button type="button" class="ui-button ui-button--secondary" data-record-cancel>Отмена</button><button type="button" class="ui-button" data-record-save>Сохранить</button></div>`;
  const m = mountModal(document.body, modal(`<div class="record-screen record-screen--settings">${html}</div>`, { className: 'record-modal record-modal--panel' })); if (!m) return; initTimePickers(m); m.querySelector('[data-record-cancel]').addEventListener('click', () => m.remove()); m.querySelector('[data-record-save]').addEventListener('click', () => { const rawCost = String(m.querySelector('[data-record-cost]')?.value || '').replace(/[^0-9.,-]/g, '').replace(',', '.'); const value = m.querySelector('[data-time-value]')?.value || '', match = value.match(/^(\d{1,2}):(\d{2})$/); selected.set(procedure.id, { procedure, cost: rawCost === '' ? '' : Number(rawCost), duration: match ? Number(match[1]) * 60 + Number(match[2]) : current.duration }); if (!selectionController?.isSelected(procedure.id)) parent.querySelector(`[data-procedure-select="${CSS.escape(procedure.id)}"]`)?.click(); m.remove(); });
}
function openClientModal({ date, workplaceId, from, to, procedures: selectedProcedures, onCreated }) {
  const all = people(); let filtered = all;
  const content = `<div class="record-screen record-screen--clients"><div class="record-client-toolbar"><input class="record-client-search" data-record-client-search placeholder="🔍 Найти клиента..." autocomplete="off"><button type="button" class="icon-button icon-button--primary" data-record-add-client aria-label="Добавить клиента">+</button></div><div class="record-client-list" data-record-client-list></div></div>`;
  const m = mountModal(document.body, modal(content, { className: 'record-modal record-modal--full' })); if (!m) return; let selectedClient = null;
  const render = () => { m.querySelector('[data-record-client-list]').innerHTML = filtered.map((person) => listEntry({ title: clientName(person), subtitle: person.phones?.[0] || '', image: person.photo || '', initial: clientName(person).slice(0, 1).toUpperCase(), interactive: true, data: `data-record-client="${escapeHtml(person.key)}"`, className: selectedClient?.key === person.key ? 'is-selected' : '', aria: `Выбрать клиента ${clientName(person)}` })).join('') || '<div class="muted">Клиенты не найдены.</div>'; m.querySelectorAll('[data-record-client]').forEach((card) => card.addEventListener('click', () => { selectedClient = all.find((person) => person.key === card.dataset.recordClient) || null; m.remove(); openClientConfirmation({ date, workplaceId, from, to, selectedClient, selectedProcedures, onCreated }); })); };
  m.querySelector('[data-record-client-search]').addEventListener('input', (event) => { const q = event.target.value.trim().toLocaleLowerCase('ru'); filtered = all.filter((person) => clientName(person).toLocaleLowerCase('ru').includes(q) || String(person.phones?.[0] || '').includes(q)); render(); }); m.querySelector('[data-record-add-client]').addEventListener('click', () => {}); render();
}
function openClientConfirmation({ date, workplaceId, from, to, selectedClient, selectedProcedures, onCreated }) {
  const name = clientName(selectedClient); const phone = selectedClient?.phones?.[0] || selectedClient?.phone || ''; const formattedDate = formatConfirmationDate(date); const workplace = findWorkplaceName(workplaceId); const procedureRows = selectedProcedures.map(({ procedure }) => `<div class="settings-row">${escapeHtml(procedure.name)}</div>`).join('');
  const content = `<div class="record-screen record-screen--confirmation form-grid"><div class="settings-list"><div class="settings-row">${escapeHtml(workplace)}</div></div><div class="settings-list"><div class="settings-row">${escapeHtml(formattedDate)}</div><div class="settings-row">${escapeHtml(from)} - ${escapeHtml(to || '')}</div></div><div class="settings-list"><div class="settings-row">${escapeHtml(name)}</div>${phone ? `<div class="settings-row">${escapeHtml(phone)}</div>` : ''}</div><div class="settings-list">${procedureRows || '<div class="settings-row">Процедур пока нет.</div>'}</div><div class="record-modal-actions modal-actions"><button type="button" class="ui-button ui-button--secondary" data-record-confirm-back>Назад</button><button type="button" class="ui-button" data-record-confirm>Подтвердить запись</button></div></div>`;
  const m = mountModal(document.body, modal(content, { className: 'record-modal record-modal--full' })); if (!m) return; m.querySelector('[data-record-confirm-back]').addEventListener('click', () => { m.remove(); openClientModal({ date, workplaceId, from, to, procedures: selectedProcedures, onCreated }); }); m.querySelector('[data-record-confirm]').addEventListener('click', () => { const usages = scopedUsages(date, workplaceId); if (!isTimeRangeAvailable({ from, to, usages })) { alert('Это время уже занято.'); return; } createRecord({ date: dateKey(date), workplaceId, from, to, client: { key: selectedClient.key, id: selectedClient.id || '', name: selectedClient.name || '', surname: selectedClient.surname || '', phone: selectedClient.phones?.[0] || '' }, procedures: selectedProcedures.map(({ procedure, cost, duration: itemDuration }) => ({ id: procedure.id, name: procedure.name, cost, duration: itemDuration })) }); m.remove(); onCreated?.(); });
}
function openBlockEndModal({ date, workplaceId, from, onCreated }) {
  const usages = scopedUsages(date, workplaceId); const start = timeToMinutes(from), endOfDay = start == null ? 0 : 24 * 60; const values = []; for (let value = (start ?? 0) + 5; value <= endOfDay; value += 5) { const end = minutesToTime(value); if (isTimeRangeAvailable({ from, to: end, usages })) values.push(end); }
  const html = `<div class="record-screen record-screen--time"><div class="record-modal-toolbar"><strong>Занять время</strong></div><div class="record-time-list">${values.map((value) => `<button type="button" class="record-time-option" data-block-end="${value}">${value}</button>`).join('')}</div></div>`;
  const m = mountModal(document.body, modal(html, { className: 'record-modal record-modal--full' })); if (!m) return; m.querySelectorAll('[data-block-end]').forEach((node) => node.addEventListener('click', () => { const to = node.dataset.blockEnd, breaksNow = readList('book.journalBreaks'); const item = { id: crypto.randomUUID(), workplaceId: String(workplaceId || ''), date: dateKey(date), from: String(from), to: String(to), createdAt: new Date().toISOString() }; breaksNow.push(item); localStorage.setItem('book.journalBreaks', JSON.stringify(breaksNow)); m.remove(); onCreated?.(); }));
}
function findWorkplaceName(workplaceId) { const workplace = getWorkplaces().find((item) => String(item?.id ?? item?.key ?? '') === String(workplaceId ?? '')); return workplace?.name || workplace?.title || 'Салон красоты'; }
function formatRecordDate(date) { const value = String(date || ''); const match = value.match(/^(\d{4})-(\d{2})-(\d{2})$/); return match ? `${match[3]}.${match[2]}` : value; }
function formatConfirmationDate(date) { const value = date instanceof Date ? dateKey(date) : String(date || ''); const match = value.match(/^(\d{4})-(\d{2})-(\d{2})$/); return match ? `${match[3]}.${match[2]}.${match[1].slice(-2)}` : value; }
function findRecordClient(record) { const client = record?.client || {}; return people().find((person) => String(person?.key ?? '') === String(client.key ?? '')) || people().find((person) => String(person?.id ?? '') === String(client.id ?? '')) || client; }
export function openRecordView(record, { onClose = () => {} } = {}) { if (!record) return; const client = findRecordClient(record); const name = clientName(client); const phone = client?.phones?.[0] || client?.phone || ''; const procedureNames = (record.procedures || []).map((item) => item?.name).filter(Boolean); const workplace = findWorkplaceName(record.workplaceId); const top = `<div class="record-card-topline"><span class="record-card-workplace" data-record-edit-workplace>${escapeHtml(workplace)}</span><strong class="record-card-datetime" data-record-edit-datetime>${escapeHtml(formatRecordDate(record.date))} ${escapeHtml(record.from || '')}</strong></div>`; const clientBlock = `<div class="record-card-client" data-record-edit-client><strong>${record.client?.id ? `${escapeHtml(record.client.id)} ` : ''}${escapeHtml(name)}</strong>${phone ? `<span>${escapeHtml(phone)}</span>` : ''}</div>`; const procedureBlock = procedureNames.length ? `<div class="record-card-procedures" data-record-edit-procedures>${procedureNames.map((item) => `<span>${escapeHtml(item)}</span>`).join('')}</div>` : ''; const card = entityCard({ top: `${top}${clientBlock}`, bottom: '', right: procedureBlock, className: 'entity-card--record', data: 'data-record-card' }); const content = `<div class="record-view"><div class="record-view-card">${card}</div><div class="record-view-actions"><button type="button" class="ui-button ui-button--secondary record-delete-button" data-record-delete>Удалить</button><button type="button" class="ui-button record-apply-button" data-record-apply>Применить</button></div></div>`; const m = mountModal(document.body, modal(content, { className: 'record-modal record-modal--view' })); if (!m) return; m.querySelector('[data-record-delete]')?.addEventListener('click', () => { if (!deleteRecord(record.id)) return; m.remove(); onClose?.(); }); m.querySelector('[data-record-apply]')?.addEventListener('click', () => { m.remove(); onClose?.(); }); m.addEventListener('modal:close', () => onClose?.(), { once: true }); }
export function openRecordCreation(options = {}) { openTimeModal(options); }
