import { accordion, button, emptyState, entityCard, escapeHtml, initAccordions, initPhotoField, mountModal, modal, pageHeader, phoneField, photoField, searchableSelect, select, textareaField, timeInput, workLinks, initWorkLinks, collectWorkLinks } from '../../ui/ui.js';

const PROFILE_KEY='book.profile', WORKPLACES_KEY='book.workplaces', CUSTOM_PROFESSIONS_KEY='book.profile.customProfessions';
const CITIES=['Москва','Санкт-Петербург','Казань','Нижний Новгород','Екатеринбург','Новосибирск','Самара','Ростов-на-Дону','Краснодар','Сочи','Уфа','Воронеж','Пермь','Волгоград','Омск','Тула','Калининград'];
const PROFESSIONS=['Парикмахер','Колорист','Барбер','Визажист','Стилист','Мастер маникюра','Мастер педикюра','Бровист','Лэшмейкер','Косметолог','Массажист','Мастер по наращиванию волос','Мастер перманентного макияжа','Другая'];
const EXPERIENCES=['Без опыта','До 1 года','1–3 года','3–5 лет','5–10 лет','10–15 лет','15–20 лет','Более 20 лет'];
const read=(key,fallback)=>JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback));
const write=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
const getProfile=()=>{const p=read(PROFILE_KEY,null);return p||{key:'profile',name:'',surname:'',phone:'',about:'',photo:'',profession:'',experience:'',professionAbout:''}};
const getWorkplaces=()=>read(WORKPLACES_KEY,[]),saveWorkplaces=(v)=>write(WORKPLACES_KEY,v);
const fullName=p=>[p.name,p.surname].filter(Boolean).join(' ')||'Ваш профиль';
const initial=p=>fullName(p).slice(0,1).toUpperCase()||'?';
const customProfessions=()=>read(CUSTOM_PROFESSIONS_KEY,[]);
const professionOptions=()=>[...new Set([...PROFESSIONS.filter(p=>p!=='Другая'),...customProfessions(),'Другая'])].map(value=>({value,label:value}));

export function render(root){renderProfile(root)}

function profileCard(p){return entityCard({image:p.photo||'',initial:initial(p),className:'entity-card--hero entity-card--profile',top:`<div class="entity-card__profile-phone">${escapeHtml(p.phone||'Телефон не указан')}</div>`,bottom:`<strong class="entity-card__profile-name">${escapeHtml(fullName(p))}</strong>`,right:`<span class="entity-card__profile-profession">${escapeHtml(p.profession||'Профессия не указана')}</span>`})}

function renderProfile(root){const p=getProfile();const profession=p.profession||'';const custom=profession&&!PROFESSIONS.includes(profession)?profession:'';const items=[
{title:'Личные данные',content:`<div class="form-grid">${photoField({name:'profilePhoto',value:p.photo||''})}${fieldRequired('Имя','profileName',p.name,'Ваше имя')}${fieldOptional('Фамилия','profileSurname',p.surname,'Ваша фамилия')}${phoneField({label:'Телефон',name:'profilePhone',value:p.phone||'',required:true})}${textareaField({label:'О себе',name:'profileAbout',value:p.about||'',placeholder:'Коротко о себе'})}</div>`},
{title:'Профессиональные данные',content:`<div class="form-grid">${select({label:'Профессия',name:'profession',value:custom?'Другая':profession,options:professionOptions()})}<div class="profession-custom" data-profession-custom style="display:${custom?'grid':'none'}">${fieldOptional('Своя профессия','customProfession',custom,'Введите профессию')}</div>${select({label:'Опыт работы',name:'experience',value:p.experience||'',options:[{value:'',label:'Не указан'},...EXPERIENCES.map(v=>({value:v,label:v}))]})}${textareaField({label:'О профессии',name:'professionAbout',value:p.professionAbout||'',placeholder:'Расскажите о своей профессии'})}</div>`}
];
root.innerHTML=`${pageHeader('Профиль')}${profileCard(p)}${accordion(items)}<section class="workplaces-section"><div class="section-heading"><h2>Места работы</h2>${button('+',{className:'icon-button icon-button--primary',data:'data-add-workplace',aria:'Добавить место работы'})}</div>${workplaceList(getWorkplaces())}</section><div class="profile-actions">${button('Сохранить',{data:'data-save-profile'})}</div>`;
initPhotoField(root);initAccordions(root);root.querySelector('[name="profession"]')?.addEventListener('change',e=>{const box=root.querySelector('[data-profession-custom]');if(box)box.style.display=e.target.value==='Другая'?'grid':'none'});root.querySelector('[data-save-profile]')?.addEventListener('click',()=>saveProfile(root));root.querySelector('[data-add-workplace]')?.addEventListener('click',()=>openWorkplaceModal(root));root.querySelectorAll('[data-workplace]').forEach(el=>el.addEventListener('click',()=>renderWorkplace(root,el.dataset.workplace)))}

function workplaceList(items){if(!items.length)return emptyState('Мест работы пока нет','Добавьте первое место кнопкой «+».');return `<div class="workplace-list">${items.map(w=>`<button class="workplace-row" type="button" data-workplace="${escapeHtml(w.key)}"><span><strong>${escapeHtml(w.name||'Без названия')}</strong><small>с ${escapeHtml(w.from||'—')} до ${escapeHtml(w.to||'—')}</small></span><span>›</span></button>`).join('')}</div>`}

function openWorkplaceModal(root,existing=null){const w=existing||{photo:'',name:'',city:'',address:'',phone:'',currency:'RUB',from:'09:00',to:'18:00',links:[],about:''};const html=`<form class="compact-form" data-workplace-form><div class="modal-title"><h2>Новое место работы</h2></div>${photoField({name:'workplacePhoto',value:w.photo||''})}${fieldRequired('Название','workplaceName',w.name,'Название места работы')}${searchableSelect({label:'Город',name:'workplaceCity',value:w.city||'',options:CITIES,placeholder:'Начните вводить',required:true})}${fieldOptional('Адрес','workplaceAddress',w.address,'Адрес')}${phoneField({label:'Рабочий телефон',name:'workplacePhone',value:w.phone||''})}${select({label:'Валюта',name:'workplaceCurrency',value:w.currency||'RUB',options:[{value:'RUB',label:'RUB — ₽'},{value:'EUR',label:'EUR — €'},{value:'USD',label:'USD — $'},{value:'GBP',label:'GBP — £'}]})}<div class="work-time-row"><span class="work-time-row__label">График работы</span><div class="work-time-row__fields">${timeInput({label:'с',name:'workplaceFrom',value:w.from||'09:00'})}${timeInput({label:'до',name:'workplaceTo',value:w.to||'18:00'})}</div></div><div class="array-group"><span class="array-label">Рабочие ссылки</span>${workLinks({links:w.links||[],name:'workplace-links'})}${button('+ Добавить ссылку',{className:'ui-button--small',data:'data-add-work-link="workplace-links"'})}</div>${textareaField({label:'О рабочем пространстве',name:'workplaceAbout',value:w.about||'',placeholder:'Коротко о месте работы'})}<div class="form-error" data-workplace-error></div>${button('Сохранить',{type:'submit'})}</form>`;const m=mountModal(root,modal(html));initPhotoField(m);initWorkLinks(m);m.querySelector('[data-workplace-form]').addEventListener('submit',e=>{e.preventDefault();saveWorkplace(root,m,existing)})}

function saveWorkplace(root,m,existing){const data=new FormData(m.querySelector('[data-workplace-form']));const name=String(data.get('workplaceName')||'').trim(),city=String(data.get('workplaceCity')||'').trim();if(!name||!city){m.querySelector('[data-workplace-error]').textContent='Название и город обязательны.';return}const profile=getProfile();const item={key:existing?.key||crypto.randomUUID(),profileId:profile.key,photo:String(data.get('workplacePhoto')||''),name,city,address:String(data.get('workplaceAddress')||'').trim(),phone:String(data.get('workplacePhone')||'').trim(),currency:String(data.get('workplaceCurrency')||'RUB'),from:String(data.get('workplaceFrom')||''),to:String(data.get('workplaceTo')||''),links:collectWorkLinks(m,'workplace-links'),about:String(data.get('workplaceAbout')||'').trim(),createdAt:existing?.createdAt||new Date().toISOString()};const items=getWorkplaces();saveWorkplaces(existing?items.map(w=>w.key===existing.key?item:w):[...items,item]);m.remove();renderProfile(root)}

function renderWorkplace(root,key){const w=getWorkplaces().find(x=>x.key===key);if(!w)return renderProfile(root);const p=getProfile();root.innerHTML=`${pageHeader(w.name||'Место работы')}${entityCard({image:w.photo||'',initial:(w.name||'?').slice(0,1).toUpperCase(),className:'entity-card--hero entity-card--workplace',top:`<div class="entity-card__workplace-title">${escapeHtml(w.name||'Без названия')}</div><span class="entity-card__workplace-hours">с ${escapeHtml(w.from||'—')} до ${escapeHtml(w.to||'—')}</span>${w.phone?`<span class="entity-card__workplace-phone">${escapeHtml(w.phone)}</span>`:''}`,bottom:`<strong class="entity-card__profile-phone">${escapeHtml(p.phone||'Телефон не указан')}</strong><strong class="entity-card__profile-name">${escapeHtml(fullName(p))}</strong>`,right:`<span class="entity-card__profile-profession">${escapeHtml(p.profession||'Профессия не указана')}</span>`})}<div class="workplace-details"><div><span>Город</span><strong>${escapeHtml(w.city||'—')}</strong></div><div><span>Адрес</span><strong>${escapeHtml(w.address||'—')}</strong></div><div><span>Валюта</span><strong>${escapeHtml(w.currency||'—')}</strong></div>${w.about?`<div><span>О рабочем пространстве</span><strong>${escapeHtml(w.about)}</strong></div>`:''}${w.links?.length?`<div><span>Рабочие ссылки</span><strong>${escapeHtml(w.links.map(l=>`${l.type}: ${l.url}`).join(', '))}</strong></div>`:''}</div><div class="profile-actions">${button('Назад',{className:'ui-button--secondary',data:'data-back-workplaces'})}${button('Изменить',{data:'data-edit-workplace'})}</div>`;root.querySelector('[data-back-workplaces]').onclick=()=>renderProfile(root);root.querySelector('[data-edit-workplace]').onclick=()=>openWorkplaceModal(root,w)}

function saveProfile(root){const current=getProfile();const selected=root.querySelector('[name="profession"]')?.value||'',custom=root.querySelector('[name="customProfession"]')?.value.trim()||'';const profession=selected==='Другая'?custom:selected;if(!root.querySelector('[name="profileName"]')?.value.trim()||!root.querySelector('[name="profilePhone"]')?.value.trim())return;if(custom&&!customProfessions().includes(custom))write(CUSTOM_PROFESSIONS_KEY,[...customProfessions(),custom]);write(PROFILE_KEY,{...current,key:'profile',name:root.querySelector('[name="profileName"]').value.trim(),surname:root.querySelector('[name="profileSurname"]')?.value.trim()||'',phone:root.querySelector('[name="profilePhone"]').value.trim(),about:root.querySelector('[name="profileAbout"]')?.value.trim()||'',photo:root.querySelector('[data-photo-value]')?.value||'',profession,experience:root.querySelector('[name="experience"]')?.value||'',professionAbout:root.querySelector('[name="professionAbout"]')?.value.trim()||''});renderProfile(root)}
function fieldRequired(label,name,value,placeholder){return `<label class="field"><span>${escapeHtml(label)} *</span><input name="${escapeHtml(name)}" required value="${escapeHtml(value||'')}" placeholder="${escapeHtml(placeholder||'')}"></label>`}
function fieldOptional(label,name,value,placeholder){return `<label class="field"><span>${escapeHtml(label)}</span><input name="${escapeHtml(name)}" value="${escapeHtml(value||'')}" placeholder="${escapeHtml(placeholder||'')}"></label>`}
