BEGIN;

ALTER TABLE "Profile"
  ADD COLUMN IF NOT EXISTS "photoCropX" INTEGER NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS "photoCropY" INTEGER NOT NULL DEFAULT 50;

ALTER TABLE "Workplace"
  ADD COLUMN IF NOT EXISTS "photoCropX" INTEGER NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS "photoCropY" INTEGER NOT NULL DEFAULT 50;

COMMIT;
