import { accordion, initAccordions } from './accordion/accordion.js';
import { bottomNavigation } from './navigation/navigation.js';
import { entityCard } from './cards/index.js';
import { select } from './selectors/index.js';
import { workLinks, initWorkLinks, collectWorkLinks } from './links/index.js';
import { costField, initCostFields, collectCost } from './cost/index.js';
import { durationPicker, initDurationPickers } from './duration/index.js';
import { workplaceSelector, initWorkplaceSelectors, collectWorkplaceSelections } from './workplaces/index.js';
import { escapeHtml } from './utils/escape-html.js';

export { accordion, initAccordions, bottomNavigation, entityCard, select, workLinks, initWorkLinks, collectWorkLinks, costField, initCostFields, collectCost, durationPicker, initDurationPickers, workplaceSelector, initWorkplaceSelectors, collectWorkplaceSelections, escapeHtml };

export function pageHeader(title, subtitle = '') { return `<header class="page-header"><h1>${escapeHtml(title)}</h1>${subtitle ? `<p>${escapeHtml(subtitle)}</p>` : ''}</header>`; }
export function button(label, { className = '', data = '', type = 'button', aria = '' } = {}) { return `<button type="${type}" class="ui-button ${className}" ${data}${aria ? ` aria-label="${escapeHtml(aria)}"` : ''}>${label}</button>`; }
export function iconButton(label, { className = '', data = '', aria = label } = {}) { return `<button type="button" class="icon-button ${className}" ${data} aria-label="${escapeHtml(aria)}">${label}</button>`; }
export function field({ label, name, value = '', type = 'text', placeholder = '', required = false, readonly = false, inputmode = '' }) { return `<label class="field"><span>${escapeHtml(label)}</span><input name="${escapeHtml(name)}" type="${type}" value="${escapeHtml(value)}" placeholder="${escapeHtml(placeholder)}" ${required ? 'required' : ''} ${readonly ? 'readonly' : ''} ${inputmode ? `inputmode="${escapeHtml(inputmode)}"` : ''}></label>`; }
export function phoneField({ label = 'Телефон', name = 'phone', value = '', required = false } = {}) { return field({ label, name, value, type: 'tel', required, inputmode: 'tel', placeholder: '+7' }); }
export function searchableSelect({ label, name, value = '', options = [], placeholder = 'Начните вводить', required = false } = {}) { const id = `search-${name}-${Math.random().toString(36).slice(2, 8)}`; const opts = options.map((option) => { const item = typeof option === 'string' ? { value: option, label: option } : option; return `<option value="${escapeHtml(item.value)}">${escapeHtml(item.label)}</option>`; }).join(''); return `<label class="field searchable-select"><span>${escapeHtml(label)}</span><input list="${id}" name="${escapeHtml(name)}" value="${escapeHtml(value)}" placeholder="${escapeHtml(placeholder)}" ${required ? 'required' : ''} autocomplete="off"><datalist id="${id}">${opts}</datalist></label>`; }
export function timeInput({ label, name, value = '' } = {}) { return `<div class="time-picker" data-time-picker><span class="field-label">${escapeHtml(label || '')}</span><button type="button" class="duration-picker__button" data-time-open>${escapeHtml(value || 'Выбрать время')}</button><input type="hidden" name="${escapeHtml(name)}" value="${escapeHtml(value)}" data-time-value></div>`; }
export function initTimeInputs(root) { root.querySelectorAll('[data-time-picker]').forEach((host) => host.querySelector('[data-time-open]')?.addEventListener('click', () => openTimePicker(host))); }
function openTimePicker(host) { const hidden = host.querySelector('[data-time-value]'); const current = String(hidden?.value || '09:00'); const [hh, mm] = current.split(':').map(Number); const hour = Number.isFinite(hh) ? hh : 9; const minute = Number.isFinite(mm) ? mm : 0; const hours = Array.from({ length: 24 }, (_, i) => `<option value="${i}" ${i === hour ? 'selected' : ''}>${String(i).padStart(2, '0')}</option>`).join(''); const rounded = (Math.round(minute / 5) * 5) % 60; const minutes = Array.from({ length: 12 }, (_, i) => i * 5).map(i => `<option value="${i}" ${i === rounded ? 'selected' : ''}>${String(i).padStart(2, '0')}</option>`).join(''); const backdrop = document.createElement('div'); backdrop.className = 'modal-backdrop'; backdrop.innerHTML = `<div class="modal-sheet duration-modal" role="dialog" aria-modal="true"><button type="button" class="modal-close" data-time-close aria-label="Закрыть">×</button><div class="modal-title"><h2>Выбор времени</h2></div><div class="duration-wheel"><label class="field"><span>Часы</span><select data-time-hours>${hours}</select></label><label class="field"><span>Минуты</span><select data-time-minutes>${minutes}</select></label></div><button type="button" class="ui-button" data-time-save>Сохранить</button></div>`; document.body.appendChild(backdrop); const close = () => backdrop.remove(); backdrop.addEventListener('click', (e) => { if (e.target === backdrop || e.target.closest('[data-time-close]')) close(); }); backdrop.querySelector('[data-time-save]').onclick = () => { const h = String(Number(backdrop.querySelector('[data-time-hours]').value)).padStart(2, '0'); const m = String(Number(backdrop.querySelector('[data-time-minutes]').value)).padStart(2, '0'); const time = `${h}:${m}`; hidden.value = time; host.querySelector('[data-time-open]').textContent = time; close(); }; }
export function textareaField({ label, name, value = '', placeholder = '', required = false, rows = 4 } = {}) { return `<label class="field"><span>${escapeHtml(label)}</span><textarea name="${escapeHtml(name)}" rows="${rows}" placeholder="${escapeHtml(placeholder)}" ${required ? 'required' : ''}>${escapeHtml(value)}</textarea></label>`; }
export function photoField({ name = 'photo', value = '' } = {}) { const preview = value ? `<div class="photo-field__preview" style="background-image:url('${escapeHtml(value)}')" aria-hidden="true"></div>` : '<div class="photo-field__preview photo-field__preview--empty" aria-hidden="true">Фото</div>'; return `<div class="photo-field" data-photo-field><span class="photo-field__label">Фото</span><label class="photo-field__control">${preview}<span class="photo-field__action">${value ? 'Изменить фото' : 'Добавить фото'}</span><input type="file" accept="image/*" data-photo-input></label>${value ? '<button type="button" class="ui-button ui-button--small photo-field__remove" data-photo-remove>Удалить фото</button>' : ''}<input type="hidden" name="${escapeHtml(name)}" value="${escapeHtml(value)}" data-photo-value></div>`; }
export function initPhotoField(root) { root.querySelectorAll('[data-photo-field]').forEach((fieldRoot) => { const input = fieldRoot.querySelector('[data-photo-input]'), value = fieldRoot.querySelector('[data-photo-value]'), preview = fieldRoot.querySelector('.photo-field__preview'), action = fieldRoot.querySelector('.photo-field__action'); if (!input || !value || !preview || !action) return; input.onchange = () => { const file = input.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { const src = String(reader.result || ''); value.value = src; preview.classList.remove('photo-field__preview--empty'); preview.style.backgroundImage = `url('${src.replaceAll("'", '%27')}')`; preview.textContent = ''; action.textContent = 'Изменить фото'; if (!fieldRoot.querySelector('[data-photo-remove]')) fieldRoot.insertAdjacentHTML('beforeend', '<button type="button" class="ui-button ui-button--small photo-field__remove" data-photo-remove>Удалить фото</button>'); }; reader.readAsDataURL(file); }; fieldRoot.onclick = (event) => { if (!event.target.closest('[data-photo-remove]')) return; value.value = ''; input.value = ''; preview.style.backgroundImage = ''; preview.classList.add('photo-field__preview--empty'); preview.textContent = 'Фото'; action.textContent = 'Добавить фото'; event.target.closest('[data-photo-remove]')?.remove(); }; }); }
export function emptyState(title, text = '') { return `<div class="empty-state"><strong>${escapeHtml(title)}</strong>${text ? `<span>${escapeHtml(text)}</span>` : ''}</div>`; }
export function modal(content, { title = '' } = {}) { return `<div class="modal-backdrop" data-modal><div class="modal-sheet" role="dialog" aria-modal="true" ${title ? `aria-label="${escapeHtml(title)}"` : ''}><button type="button" class="modal-close" data-modal-close aria-label="Закрыть">×</button>${content}</div></div>`; }
export function mountModal(root, html) { root.insertAdjacentHTML('beforeend', html); const m = root.querySelector('[data-modal]:last-of-type'); m?.addEventListener('click', (e) => { if (e.target.matches('[data-modal],[data-modal-close]')) m.remove(); }); requestAnimationFrame(() => m?.querySelector('input,select,textarea,button:not([data-modal-close])')?.focus()); return m; }
